### ISSUE TITLE
How to enable Archives index layout?

### ISSUE THREAD

**Issue by thasophearak** [litten/hexo-theme-yilia#1]
After install the theme, when I attempt go to archive page they still use index layout.
Did I missed something?
![screenshot from 2014-09-08 21 44 28](https://cloud.githubusercontent.com/assets/5785105/4187095/ab535370-3766-11e4-8525-d7a6ae8edcc7.png)

thanks,

**Comment by janestar** [comment]
litten 你好，我在使用这个theme时，进入主页显示全部内容，在根目录下最新的_config.yml里面已经没有archive这个属性了，请问该如何设置呢，我插入的图片在主页可以全部显示，但是点击more进去以后就无法显示啦？

**Comment by janestar** [comment]
litten 你好，我在使用这个theme时，进入主页显示全部内容，在根目录下最新的_config.yml里面已经没有archive这个属性了，请问该如何设置呢，我插入的图片在主页可以全部显示，但是点击more进去以后就无法显示啦？

**Comment by janestar** [comment]
litten 你好，我在使用这个theme时，进入主页显示全部内容，在根目录下最新的_config.yml里面已经没有archive这个属性了，请问该如何设置呢，我插入的图片在主页可以全部显示，但是点击more进去以后就无法显示啦？

**Comment by janestar** [comment]
litten 你好，我在使用这个theme时，进入主页显示全部内容，在根目录下最新的_config.yml里面已经没有archive这个属性了，请问该如何设置呢，我插入的图片在主页可以全部显示，但是点击more进去以后就无法显示啦？

**Comment by janestar** [comment]
litten 你好，我在使用这个theme时，进入主页显示全部内容，在根目录下最新的_config.yml里面已经没有archive这个属性了，请问该如何设置呢，我插入的图片在主页可以全部显示，但是点击more进去以后就无法显示啦？
