### ISSUE TITLE
hexo 3.1.1 每次使用hexo g的指令之后，头像的文件都不见了，头像的图片文件路径是：/public/img/haha.jpg

### ISSUE THREAD

**Issue by jingzhiMo** [litten/hexo-theme-yilia#127]

**Comment by korvin101** [comment]
不要把文件放在`public`目录下，这个目录是执行`hexo g`时生成静态页面文件的目录，每次执行`hexo g`时，会先清空`public`目录，然后，生成新的静态页面，你可以把头像放在`source`目录下，用的时候直接`/haha.jpg`

**Comment by jingzhiMo** [comment]
T_T 谢谢 @korvin101 折腾了好久，终于搞定了
