### ISSUE TITLE
主页文章不折叠

### ISSUE THREAD

**Issue by KongRain** [litten/hexo-theme-yilia#138]
看到您的博客中首页，也就是未点开的博客是折叠的，只显示一部分，然后有一个'more>>'按钮
为什么在我的博客里无论文章多长都会全部显示出来呢？
http://kongrain.github.io/ 
这样的话首页能显示的文章数量就少了，而且要滚动很长才能出现下一篇文章的标题，可能是我哪里没有设置对，您能看出问题在哪吗？谢谢~

**Comment by korvin101** [comment]
使用`<!--more-->`标签截取摘要

**Comment by KongRain** [comment]
真的解决啦！谢谢你~

**Comment by korvin101** [comment]
close吧
