### ISSUE TITLE
您好, 请教一个关于归档的问题

### ISSUE THREAD

**Issue by MakeHui** [litten/hexo-theme-yilia#141]
我设置了归档, 但是点进去却是和首页一样的
难道还有其他什么参数能影响到归档这块的?
http://huyaohui.com/

**Comment by korvin101** [comment]
归档不需要任何设置，默认就是打开的

**Comment by MakeHui** [comment]
可是我这里的归档和首页是一样的, 并没有归档, 非常奇怪..

**Comment by korvin101** [comment]
你是不是做过其它改动，建议先使用`hexo clean`清理生成的静态页面，然后再运行`hexo g`重新生成，运行 `hexo s`，在本地看看是不是正常。

**Comment by MakeHui** [comment]
试过, 并不行, %>_<%..

**Comment by MakeHui** [comment]
原因找出来了, 是我的根目录下的`_config.yml`中的一些属性设置影响到了, 原理就不清楚了, 您看看
```xml
# Archives
## 2: Enable pagination
## 1: Disable pagination
## 0: Fully Disable
archive: 2
category: 2
tag: 2
```
感谢您的解答.. :)

**Comment by korvin101** [comment]
@MakeHui 暂不清楚原因好了就行:smiling_imp:
