### ISSUE TITLE
关于头像设定问题？

### ISSUE THREAD

**Issue by ixiusama** [litten/hexo-theme-yilia#143]
尝试了很多次的修改头像都不成功，不管是png 还是jpg的文件都不行本地放图不行
七牛的图床也不行。我的地址是：ixiusama.github.io
求大神帮忙!小弟在此多谢了。

**Comment by korvin101** [comment]
头像图片`avatar.png`放在`/source/`下，修改主题配置文件`_config.yml`里，
```
avatar: /avatar.png
```

**Comment by ixiusama** [comment]
您好，已经安装您的要求进行了修改，但是并没有什么变化，网页已经上传。

**Comment by korvin101** [comment]
@ixiusama 你改过主题里的什么东西没有

**Comment by korvin101** [comment]
@ixiusama 主题配置文件里`open_in_new`的值，你把true写成ture了

**Comment by ixiusama** [comment]
噗，逗逼了。太感谢了。

**Comment by mzljin** [comment]
怎么解决的

**Comment by swift1994** [comment]
http://zhangzhaopds.github.io/2016/11/18/hexo%E4%B8%BB%E9%A2%98yilia%E7%9A%84%E5%A4%B4%E5%83%8F%E6%97%A0%E6%B3%95%E6%98%BE%E7%8E%B0/
看这个
