### ISSUE TITLE
`About me`

### ISSUE THREAD

**Issue by LeoiOS** [litten/hexo-theme-yilia#151]
`关于我` 中的文字能不能换行？怎么换行？在 _config.yml 里面试了 `/n` `<br>` 都不行。

**Comment by MOxFIVE** [comment]
https://github.com/litten/hexo-theme-yilia/blob/master/layout/_partial/left-col.ejs#L105
``` diff
- <div id="js-aboutme"><%=theme.aboutme%></div>
+ <div id="js-aboutme">可<br>以<br>换<br>行<br>了</div>
```

**Comment by LeoiOS** [comment]
@MOxFIVE 
Thank you!!
