### ISSUE TITLE
分享到位置有问题？

### ISSUE THREAD

**Issue by zhuscat** [litten/hexo-theme-yilia#157]
<img width="333" alt="2015-12-20 3 46 50" src="https://cloud.githubusercontent.com/assets/14963619/11917035/f77d8078-a730-11e5-977f-cd7985a30a8c.png">
如图

**Comment by 7loiter** [comment]
同样是这个问题

**Comment by CharCollins** [comment]
自己修改了主题下面layout/_partial/footer.ejs文件如下，把原来在div层左边的内容移到了右边
<footer id="footer">
  <div class="outer">
    <div id="footer-info">
    	
      	<div class="footer-right">
      		&copy; <%= date(new Date(), 'YYYY') %> <%= config.author || config.title %>
      		<a href="http://hexo.io/" target="_blank">Hexo</a>  Theme <a href="https://github.com/litten/hexo-theme-yilia" target="_blank">Yilia</a> by Litten
      	</div>
    </div>
  </div>
</footer>

**Comment by chenyingsunny** [comment]
在yilia/source/css/_partial/main.styl最后加上
.share_jia{
	padding: 0 40px;
}
这样就和评论对齐了
