### ISSUE TITLE
未开启评论时，footer和share_jia部分内容重叠

### ISSUE THREAD

**Issue by w41ter** [litten/hexo-theme-yilia#158]
![descirption](https://cloud.githubusercontent.com/assets/7908062/11947833/5c220e00-a8a7-11e5-8fc4-3f126f75e26e.jpg)
如图，footer部分和share部分重叠在一起，导致显示混乱。

**Comment by thinkermao** [comment]
经过测试，在edge、chrome和移动端均存在上述问题。
