### ISSUE TITLE
分类以及分页的路径如何设置？

### ISSUE THREAD

**Issue by hugzh** [litten/hexo-theme-yilia#165]
你好，很感谢你的主题分享。最近打算换你的主题，遇到一个问题：列表分页的时候链接的url是不正确的，比如说应该是/page/2/ 在我这里却被渲染成了/page/index.html，导致访问不了。分类也是一样，/categories/xx/被渲染成了/categories/index.html。我想问一下这是应该在hexo的配置里面捣鼓还是在yilia主题的_config里面捣鼓？

**Comment by iblogc** [comment]
这个是个别现象，建议重新下载主题，清理部署目录，重新生成静态页面

**Comment by hugzh** [comment]
@iblogc  谢谢解答！重新把hexo安装了一遍，没有问题了
