### ISSUE TITLE
请问如何更改网站图标？

### ISSUE THREAD

**Issue by Hansen1997** [litten/hexo-theme-yilia#171]

**Comment by hanlindong** [comment]
同问

**Comment by Brances** [comment]
打开你的主题配置文件，找到这个
网络地址：avatar: "http://7xpnu3.com1.z0.glb.clouddn.com/imageuserHead.png"
如果是本地的图片话，头像放在 hexo 的 source文件下
本地 avatar:/图片名称

**Comment by Hansen1997** [comment]
不好意思，我指的是图标而不是头像，就是在保存成书签在书签栏里显示的网站图标，请问如何实现？

**Comment by mritd** [comment]
在那个配置文件里也有
2016年1月20日 下午6:03，"Hansen1997" <notifications@github.com>写道：

**Comment by yf0994** [comment]
我把头像图片放在了根source目录下,但是只有主页的头像起作用了,其他页面头像没有起作用,这是什么原因

**Comment by Hansen1997** [comment]
@mritd 多谢指点，已解决
