### ISSUE TITLE
窄屏幕移动端显示的问题

### ISSUE THREAD

**Issue by hanlindong** [litten/hexo-theme-yilia#173]
<img width="389" alt="2016-01-17 20 05 44" src="https://cloud.githubusercontent.com/assets/13126927/12377361/40da0e40-bd56-11e5-9a9f-50fee78f43f9.png">
<img width="384" alt="2016-01-17 20 05 53" src="https://cloud.githubusercontent.com/assets/13126927/12377362/418669ba-bd56-11e5-92dc-aa8844829eae.png">

你好！
此处 主页 所有文章 一栏与上下文间隙过大，移动端看起来有些不适，但是电脑上就没有这个问题，请问如何解决？
谢谢！

**Comment by iblogc** [comment]
去掉source/css/_partial/main.styl里的`min-height: 150px`

**Comment by hanlindong** [comment]
谢谢！

**Comment by hanlindong** [comment]
非常感谢！
