### ISSUE TITLE
怎么启用disqus

### ISSUE THREAD

**Issue by kawaiiushio** [litten/hexo-theme-yilia#18]
怎么启用disqus  关闭多说

**Comment by litten** [comment]
你好，若使用disqus，请在博客config文件中填写disqus_shortname，并关闭多说评论

**Comment by kawaiiushio** [comment]
感谢！

**Comment by zpike** [comment]
We were unable to load Disqus... 可以翻墙，可以看到别人博客的disqus部分 但是我的却不行。。。
