### ISSUE TITLE
语言如何设置简体中文呢是zh-cn? 头像路径该放哪里呢?

### ISSUE THREAD

**Issue by sunlanda** [litten/hexo-theme-yilia#188]
感谢

**Comment by RyanWangGit** [comment]
* 头像放在`/source/img/avatar.png`，然后`_config.yml`里面`avatar: /img/avatar.png`
 * 在全局`_config.yml`中修改`language: zh-Hans`

**Comment by sunlanda** [comment]
@RyanWangGit   多谢 两条均已试验成功~
