### ISSUE TITLE
无关文件 .DS_STORE

### ISSUE THREAD

**Issue by yxwangcs** [litten/hexo-theme-yilia#189]
在Windows下generate也会去分析这个mac os下的文件产生几个process fail，不过倒是无关痛痒。

**Comment by WangXiZhu** [comment]
今日我也遇到相同的情况，只是更换了主题为yilla就出现了。这个是系统的问题吗？

**Comment by RyanWangGit** [comment]
因为作者用的mac os会生成这个文件但是没有加到`.gitignores`文件中去，导致把这个文件上传了，hexo会认为是非法文件，在文件夹中找找删掉即可。

**Comment by WangXiZhu** [comment]
谢谢

**Comment by WangXiZhu** [comment]
目前在系统中禁用了 .DS-Store 文件，但是编译hexo server还会出现一大堆，但是不影响编译。就是看着烦人

**Comment by leesei** [comment]
This causes error on Hexo 3.2
@litten Please add it to `gitignore`

**Comment by leo-yi** [comment]
删除themes/yilia 目录下, 及子目录下所有的.DS_Store文件即可解决问题.

原因, 这文件是OSX生成的, 跟主题和HEXO没有关系

**Comment by WangXiZhu** [comment]
删除了，系统也会马上生成一个文件。目前就是在OS系统下 出的问题
