### ISSUE TITLE
Windows .DS_Store 导致 Hexo generate 报错. 

### ISSUE THREAD

**Issue by Astone-Chou** [litten/hexo-theme-yilia#198]
虽然可以继续正常生成 html , 但是这种文件还是 ignore 掉吧.

**Comment by tidus5** [comment]
这个问题跟了几天了，hexo 在更新到3.2.0 就会有这个问题， 3.1.1 是可以的。
hexo上作者恢复是，删除这个文件。
[](https://github.com/hexojs/hexo/issues/1807)
[](https://github.com/litten/hexo-theme-yilia/issues/189)

**Comment by Astone-Chou** [comment]
对啊, 加到 ignore 里就好了嘛.

**Comment by tonycheng93** [comment]
删除这个就可以了

**Comment by leo-yi** [comment]
Windwos下请删除yilia目录下及子目录下的.DS_Store文件即可;
这个.DS_Store文件是OSX生成的, 跟Windows没有半毛钱关系, 可以放心删除

**Comment by xiaoshenmao** [comment]
这个文件是记录 Mac 文件夹上的图标位置一些配置信息 ,删掉 或者 ignore忽略掉都可以

**Comment by litten** [comment]
误加的，我的锅，已经删除了的
