### ISSUE TITLE
[请教]侧边栏自定义背景

### ISSUE THREAD

**Issue by wuchangfeng** [litten/hexo-theme-yilia#209]
想要在侧边栏 自定义背景图片就像这样http://luuman.github.io/2016/01/15/Hexo-Theme/，需要做哪些改动呢？Js文件？资源文件？

**Comment by wuchangfeng** [comment]
自问自答一下：F:\Hexo\themes\yilia\source\css\_partial，这个目录下的 main.sty 可以改动

**Comment by clayclayclay** [comment]
@wuchangfeng 可是我根本没有css_partial这个目录呀

**Comment by Johnnyluke** [comment]
同求，新版怎么修改侧边栏背景

**Comment by LnksW** [comment]
没有这个文件夹

**Comment by yansheng836** [comment]
可以参考：<https://www.yansheng.xyz/article/72a91df5.html#1-%E5%B7%A6%E4%BE%A7%E8%BE%B9%E6%A0%8F>
