### ISSUE TITLE
怎么才能实现一篇文章多个标签和主页显示文章概要

### ISSUE THREAD

**Issue by jeasonstudio** [litten/hexo-theme-yilia#212]
如题

**Comment by leo-yi** [comment]
这几个都是HEXO特性, 基本和主题无关.

多标签在文章头部的tag那里指定

tag: tag1 tag2

显示概要的话, 请在正文中用


标签

**Comment by Johnnyluke** [comment]
---
layout: post
title: "个人博客"
date: 2017-03-05 10:00
comments: true
tags: 
	- 随笔
	- hexo
---


可以这样试试

**Comment by wmjtxt** [comment]
tags: [tag1, tag2]
