### ISSUE TITLE
大家都来贴下自己的博客，相互学习下。

### ISSUE THREAD

**Issue by crazy-canux** [litten/hexo-theme-yilia#216]
http://crazy-canux.github.io/

**Comment by lslvxy** [comment]
[http://lslvxy.com](http://lslvxy.com)
域名修改为
[http://lise.io](http://lise.io)

域名再次修改为
[https://imsense.site](https://imsense.site)

以后不会再改了

**Comment by zealoussnow** [comment]
@crazy-canux 如何设置首页，让它只显示每篇文章的一部分而不是全部呢？谢谢。

**Comment by zealoussnow** [comment]
@lslvxy 看了您的博客，请教一下是怎么加上的二维码啊？

**Comment by lslvxy** [comment]
@crazy-canux  文章里面有个 放到摘要后面就行了

> 如果你看到这篇文章，我确信你毫无疑问会认为jQuery是一个使用简便的库。jQuery可能使用起来很简单，但是它仍然有一些奇怪的地方，对它基本功能和概念不熟悉的人可能会难以掌握。但是不用担心，我下面已经把代码划分成小部分，做了一个简单的指导。那些语法看起来可能过于复杂，但是如果进入到它的思想和模式中，它是非常简单易懂的。



下面，我们有了一个插件的基本层次：

前面的就是摘要了

**Comment by lslvxy** [comment]
@crazy-canux  二维码就是一个div浮动在页面上的，可以看下我的源码

**Comment by zealoussnow** [comment]
@lslvxy 非常感谢。

**Comment by jarson7426** [comment]
http://jarson7426.github.io/

**Comment by ydx1013** [comment]
http://www.yuedongxu.cn/

**Comment by zealoussnow** [comment]
https://zealoussnow.github.io

**Comment by isnine** [comment]
www.isnine,me

**Comment by isnine** [comment]
http://www.isnine.me/

**Comment by bsqql123** [comment]
@lslvxy 我知道可以实现tags，怎么实现分类呀？求教

**Comment by bsqql123** [comment]
@lslvxy 谢谢啦，我看到html源码里有个categories，猜到应该是它。
试了一下还真是这样的，在头部加上categories就可以实现分类了

**Comment by touch28** [comment]
http://touch28.github.io/   嘿嘿 欢迎

**Comment by taozhijiang** [comment]
https://taozj.org 哈哈

**Comment by SamenYan** [comment]
http://samenyan.github.io/呦吼

**Comment by zhangolve** [comment]
http://hktkdy.com 海阔天空的云

**Comment by tao12345666333** [comment]
https://moelove.info/

主要内容是  Container/Docker/Golang/Kubernetes/Python

**Comment by xingbofeng** [comment]
http://xingbofeng.com/ Encounter's Blog 欢迎

**Comment by liguanrui** [comment]
http://liguanrui.github.io/

**Comment by Forecheng** [comment]
@zealoussnow 看了你的博客，很漂亮，有一个问题请教下，头像的动画在哪里设？谢谢！

**Comment by zealoussnow** [comment]
@Forecheng http://magicwangs.github.io/post/Hexo-Yilia-%E4%B8%BB%E9%A2%98%E4%BC%98%E5%8C%96%E6%80%BB%E7%BB%93/

**Comment by Forecheng** [comment]
www.forecheng.com

**Comment by ChuanfengZhang** [comment]
http://zhangchuanfeng.me
欢迎访问哈

**Comment by SuperDannyBoy** [comment]
http://superdanny.link
欢迎朋友指导。

**Comment by mrpsweet** [comment]
mrpsweet.github.io 新人初入 还是希望老司机多提意见，带带我

**Comment by ChuanfengZhang** [comment]
@mrpsweet  黄金屋 404啦

**Comment by mrpsweet** [comment]
@ChuanfengZhang 恩 开始用没多久，有些还不熟，需要改进。

**Comment by mrpsweet** [comment]
@lslvxy 有没有发现material的主题有点卡，还是我这边机子的问题

**Comment by qhxin** [comment]
http://qhxin.com/  挺喜欢yilia的

**Comment by lslvxy** [comment]
@mrpsweet  主题速度还可以的,可能是github访问速度比较慢,我现在部署到阿里云上了,感觉还可以.

**Comment by sherryriver** [comment]
都是 yilia的主题啊 那我献丑 上另一个主题  http://sherryriver.com/  求友链 求留言

**Comment by zhangolve** [comment]
@lslvxy 阿里云只是部署一个博客的话，有点浪费，况且阿里云确实略贵。

**Comment by lslvxy** [comment]
@ zhangolve  我不是买的etc,用得web托管,一年199.
或者直接用oss,小流量免费的

**Comment by lslvxy** [comment]
@ zhangolve  我不是买的etc,用得web托管,一年199.
或者直接用oss,小流量免费的

**Comment by zhangolve** [comment]
@lslvxy  你是阿里云香港吧，我看没有备案。

**Comment by taozhijiang** [comment]
@zhangolve 现在虚拟空间200M免费一年，应该是够用了。申请了赶紧备案，后面可以用CDN，价格便宜的多    
https://wanwang.aliyun.com/hosting/free

**Comment by zhangolve** [comment]
想搞个虚拟主机或者vps玩玩，身为前端，也想对后端和linux这块有些了解。但是总觉得备案挺麻烦的。

**Comment by taozhijiang** [comment]
@zhangolve  VPS确实爽，但是如果不是香港的主机，大陆普遍延时很高。   
博客只是写东西的，所以当作生产环境，不应该多折腾。VPS国外便宜的主机很多，挂博客可能会比较慢。

**Comment by zhangolve** [comment]
有道理，谢过楼上了。我会再考虑的。

**Comment by wenboo** [comment]
wenboo.site ^^

**Comment by lengjiaxin** [comment]
[http://coolcat.club](url)

**Comment by xinghalo** [comment]
https://xinghalo.github.io/   xingoo的博客，刚刚从博客园转过来

**Comment by taozhijiang** [comment]
感觉贴的网址很多都挂了。。。

**Comment by howborn** [comment]
[www.fanhaobai.com](https://www.fanhaobai.com)

**Comment by lengjiaxin** [comment]
http://coolcat.club/

**Comment by lengjiaxin** [comment]
http://coolcat.club/

**Comment by pangjunpeng** [comment]
<a href="https://pangjunpeng.com" target="_blank">https://pangjunpeng.com</a>好多前辈都挂掉了:satisfied:

**Comment by reboot1921** [comment]
https://kayla1209.com/
