### ISSUE TITLE
分类功能

### ISSUE THREAD

**Issue by wuchangfeng** [litten/hexo-theme-yilia#226]
如何建立分类功能？如下尝试了，却报错

![](http://7xrl8j.com1.z0.glb.clouddn.com/yilia1.jpg)

![](http://7xrl8j.com1.z0.glb.clouddn.com/yilia2.jpg)

**Comment by firstdream10** [comment]
好像本地访问就会有问题，推送到Github之后就没问题了。。

**Comment by xiefangzhenz** [comment]
我也想搞个这样的分类，但是出来了，点开之后总是路径不对。。。

**Comment by wuchangfeng** [comment]
@xiefangzhenz 分类功能可以解决，我之前在知乎搜索到解决办法，并且我朋友验证可行

https://www.zhihu.com/question/33324071/answer/58775540

**Comment by xiefangzhenz** [comment]
@wuchangfeng 非常感谢，成功了

**Comment by wuchangfeng** [comment]
@xiefangzhenz 不客气，哈哈
