### ISSUE TITLE
网站图标问题

### ISSUE THREAD

**Issue by Vence** [litten/hexo-theme-yilia#228]
请问设置网站图标是这样的吗，就上网站标题左边的小图标

`favicon: /favicon.png`

这个favicon.png放在themes\yilia目录下吗，为什么没有效果？

**Comment by wuchangfeng** [comment]
放在 hexo/source路径下.格式 favicon.ico

**Comment by AsanZhang** [comment]
放在 hexo/source路径下，也还是不管用啊

**Comment by AsanZhang** [comment]
@wuchangfeng 我放在hexo/source路径下，部署后public下是有了，但是网站图标还是不显示。怎解？

**Comment by AsanZhang** [comment]
@Vence 你这个网站图标搞定了没有？

**Comment by wuchangfeng** [comment]
@AsanZhang 图片的命名以及各式没有错吧？

**Comment by wuchangfeng** [comment]
@AsanZhang 我点了你的网站看了一下，标签的图标显示的是自定义的啊

**Comment by AsanZhang** [comment]
@wuchangfeng 哦，我又试了下可以的，是浏览器缓存的问题，3Q!!!

**Comment by oscersong007** [comment]
@wuchangfeng   "GET https://favicon.png/ net::ERR_NAME_NOT_RESOLVED"   这个怎么回事？
