### ISSUE TITLE
github图标不显示

### ISSUE THREAD

**Issue by JohnHow0537** [litten/hexo-theme-yilia#238]
本地测试时候正常,但是部署之后,git图标的圆圈中间没有logo

**Comment by daikanshan** [comment]
我看了你的博客和github上的代码，你把img文件夹里的GitHub.png改为github.png应该就可以了。

**Comment by RyanWangGit** [comment]
问题本质上是git的大小写问题，[Windows 及 OS X 下 git 区分文件大小写问题](http://ryanwang.me/2016/03/06/Windows-%E5%8F%8A-OS-X-%E4%B8%8B-git-%E5%8C%BA%E5%88%86%E6%96%87%E4%BB%B6%E5%A4%A7%E5%B0%8F%E5%86%99%E9%97%AE%E9%A2%98/)

**Comment by JohnHow0537** [comment]
@daikanshan 可以了,谢谢
