### ISSUE TITLE
多说配置问题

### ISSUE THREAD

**Issue by asdf2014** [litten/hexo-theme-yilia#242]
配置好了多说, 也看到正常的提示说, yuzhouwan在使用多说

但是, 之前评论都没能同步过来, 这些评论 都是能在后台看到的

http://yuzhouwan.com/2014/11/02/What-is-the-Node-js/

![image](https://cloud.githubusercontent.com/assets/8108788/15267834/9dbb8534-19ff-11e6-9386-3f9ae74bf72f.png)

**Comment by asdf2014** [comment]
希望有空帮忙看一下哇, 这个主题太漂亮了, 不想再回退回去了 :)

**Comment by asdf2014** [comment]
解决了，close啦

**Comment by Forecheng** [comment]
@asdf2014 在http://duoshuo.com/登陆多说后，找不到“设置”页面，你图片里的设置在哪里？
