### ISSUE TITLE
hexo s 本地调试是正常的，但是hexo d 布署之后样式就不起作用了

### ISSUE THREAD

**Issue by arronf2e** [litten/hexo-theme-yilia#248]
CSS不起作用

**Comment by desmond1121** [comment]
yilia 在 `hexo deploy`时有bug，`main.js`里面构造路径的`_yiliaConfig.rootUrl` 导致所有加载的css/资源文件前面都有一个`undefined`

**Comment by wujunchuan** [comment]
我也是这个问题

**Comment by JayZangwill** [comment]
手动将theme/yilia/source里的main.js和mian.css文件复制到public里面

**Comment by litten** [comment]
@arronf2e @desmond1121 @wujunchuan 
这是因为hexo更新默认配置，但yilia没有及时适配导致… 讲道理是我的锅，抱歉。
但九月份已经做了一次全面升级，更新一下即可。

@JasonMrazW 手工拷贝并不推荐，如果需要做定制，请参考下wiki[《Yilia源码目录结构及构建须知》](https://github.com/litten/hexo-theme-yilia/wiki/Yilia%E6%BA%90%E7%A0%81%E7%9B%AE%E5%BD%95%E7%BB%93%E6%9E%84%E5%8F%8A%E6%9E%84%E5%BB%BA%E9%A1%BB%E7%9F%A5)
