### ISSUE TITLE
本地头像正常，上传后头像不显示

### ISSUE THREAD

**Issue by YangXiaowu** [litten/hexo-theme-yilia#251]
主题很好看，简洁大方
不知道是不是我设置的问题，试过相对路径绝对路径都是这样，在本地显示头像没有任何问题，可以一部署到github头像就不显示了

本地
`<img lazy-src="/images/xiaowu.png" class="js-avatar show" src="/images/xiaowu.png">`

github
`<img lazy-src="/images/xiaowu.png" class="js-avatar">`

貌似是因为使用的https，然后外部js是http的，不知怎么解决呀

地址 [yangxiaowu.github.io](http://yangxiaowu.github.io)

**Comment by mzljin** [comment]
你好，我也有这个问题，你是怎么解决的，还有部署后，菜单，标签那个弹出框也不显示

**Comment by YangXiaowu** [comment]
@mzljin 现在新建都会强制使用https访问，所以一些js没法加载，我是绑定域名解决的，绑定域名后可以不走https

**Comment by mzljin** [comment]
哦，谢谢
