### ISSUE TITLE
去除代码块滑动条

### ISSUE THREAD

**Issue by Simshang** [litten/hexo-theme-yilia#259]
刚刚升级到hexo3.0之后,滑动条显示不正常,请问怎么去掉代码块的滑动条?
![hexo3codeblockbug](https://cloud.githubusercontent.com/assets/9046958/16705801/172625d4-45c8-11e6-8b1f-e763ade7b6d4.JPG)

**Comment by YangXiaowu** [comment]
[issues253](https://github.com/litten/hexo-theme-yilia/issues/253)

**Comment by Simshang** [comment]
前几天自己改代码弄好了 , 详见博客[Hexo去除代码块滑动条 ](http://simtalk.cn/2016/07/07/Hexo%E5%8E%BB%E9%99%A4%E4%BB%A3%E7%A0%81%E5%9D%97%E6%BB%91%E5%8A%A8%E6%9D%A1/)
