### ISSUE TITLE
头像设置问题是因为js脚本用了http

### ISSUE THREAD

**Issue by kemchenj** [litten/hexo-theme-yilia#266]
进去浏览器的console里看了一下就发现，jQuery 1.9.1和MathJax两个的网址因为是http协议的，而现在github page默认使用了https，所以用浏览器打开的时候会默认被block掉

在localhost打开的时候不是用https，所以就不会被block掉

头像那个蹦出来的动效应该跟jquery的那个有关，所以就显示不出来，解决方法有三个：
1. 进去public里，把几个html文件里class为“js-avatar"的那个img标签改成'js-avatar show"，然后不要generate，直接部署上去
2. 关掉动画
3. 把jquery换成https版本，但项目我不太熟，找一下应该能够找到

希望可以把那两个库换成https的版本，基本上很多issue都能解决了

**Comment by litten** [comment]
谢谢，已修复
