### ISSUE TITLE
随笔这边有问题

### ISSUE THREAD

**Issue by SamenYan** [litten/hexo-theme-yilia#269]
大神们，请问我左侧栏添加了随笔。可是点击后右侧区域无法生成目录，只能展示一篇默认的index.md，无法像所有文章那样待目录展示多遍。请问这是什么问题呢？还有就是每篇文章下面的彩色标签是怎么加的？求解答啊啊啊。。。

**Comment by Forecheng** [comment]
发表文章时：
tags: 
    - tags1
    - tags2
这样就行了。
