### ISSUE TITLE
http的都打不开

### ISSUE THREAD

**Issue by GeekerAndyLove** [litten/hexo-theme-yilia#270]
小白请问，在打开http://litten.github.io/
的时候浏览器会显示
This site can’t be reached
The connection was reset.
点击所有文章的时候也是http://yourwebsite.github.io/archives打不开
换成https就可以了，哪位大神帮帮忙，感激不尽Orz

**Comment by maojinyuan** [comment]
这应该是定向重置了吧？跟http://www.google.com一个样，会选择跳到google.hk，加个s防止跳转，而且安全，google现在也支持https了

**Comment by hadesvip** [comment]
我觉得最好的选择自己去买个域名,然后https就可以去除

**Comment by GeekerAndyLove** [comment]
我也是这么想的，但是没有域名的（比如http://litten.github.io/）不是仍然加载不出来吗，前端我不懂，要是能从代码上解决就好了 @hadesvip

**Comment by hadesvip** [comment]
代码无法解决，这个https是github服务器搞的，以前是支持http的，今年全部换成https了，你可以买个域名，然后添加一个CNAME文件，上面写上你的域名我现在的就解决了
yundan.space
