### ISSUE TITLE
hi，大神，这个首页文章怎样不让他完全展示？你的more那个button怎么启用的？

### ISSUE THREAD

**Issue by lizwangying** [litten/hexo-theme-yilia#274]
hi，大神，这个首页文章怎样不让他完全展示？你的more那个button怎么启用的？

**Comment by Verchen** [comment]
tags: [tag1,tag2]
---
上边的是在首页能看到的

下边是要点击more那个button进入详情页才能看到的

**Comment by Verchen** [comment]
\<!--more--\>

**Comment by Verchen** [comment]
tags:  [tag1,tag2]
---
从这往上的内容实在首页能看到的
\<!--more--\>
下边的内容是在详情页能看到的

**Comment by lizwangying** [comment]
@Verchen 试过了，依旧不好用，然后我就换了个主题。。。。。一个完全不展示实际内容的主题。

**Comment by Verchen** [comment]
我的是可以的 ，可能还要more上下都空一行把

**Comment by lizwangying** [comment]
@Verchen 哦，那我试试~谢谢啦
