### ISSUE TITLE
关于头像的解决方法

### ISSUE THREAD

**Issue by TopGrd** [litten/hexo-theme-yilia#279]
我头像用的外链，无法正常显示，看控制台说root不对，应该可以修改下代码，在主题代码layout/_partial/after-footer.ejs，root修改为空：
```js
	var yiliaConfig = {
		fancybox: <%=theme.fancybox%>,
		mathjax: <%=theme.mathjax%>,
		animate: <%=theme.animate%>,
		isHome: <%=is_home()%>,
		isPost: <%=is_post()%>,
		isArchive: <%=is_archive()%>,
		isTag: <%=is_tag()%>,
		isCategory: <%=is_category()%>,
		open_in_new: <%=theme.open_in_new%>,
		root: ''
	}
```
layout\_partial\left-col.ejs里改成如下： 
```html
<img lazy-src="<%=theme.avatar%>" class="js-avatar">
```
**如果你的页面开启https的话**，将\layout\_partial\after-footer.ejs 里的js链接前面的http改为https 
```
<%- js('https://7.url.cn/edu/jslib/comb/require-2.1.6,jquery-1.9.1.min') %>
``` 
同理layout\_partial\mathjax.ejs里也改为 https
```
<script type="text/javascript" src="https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML">
```
经测试，这么修改的话，本地和外链头像都可以，不过你的外链头像如果是http链接，则可能使https失效，不过仍可以访问。
上面的也可以解决tag和category不生效。

**Comment by archerU** [comment]
本地的是可以了，线上的不行

**Comment by TopGrd** [comment]
@archerU 你的头像是外链还是本地的？我的线上可以，可以访问topgrd.github.io看下，之前我的tag和category都不可以，我改了上面的代码都可以了。

**Comment by TopGrd** [comment]
https貌似不可以，其中2个js采用了http的请求
![image](https://cloud.githubusercontent.com/assets/4202848/17658558/234bbf28-62ff-11e6-906f-5e382d5510e3.png)  晚上我再看看

**Comment by TopGrd** [comment]
@archerU 看上面重新编辑过的解决方法，应该ok了。

**Comment by archerU** [comment]
@TopGrd 不好意思这么晚回复。解决了，应该是http的问题。依照你上面的方案把http改成https就可以了。原来的是用外链和本地的都不行。好吧，尴尬了不知道怎么贴图。

- [Warning] The page at https://archeru.github.io/ was allowed to display insecure content from http://ww2.sinaimg.cn/mw690/997884acgw1f6wignzkcuj207s07s0si.jpg. (archeru.github.io, line 261)

[Warning] [blocked] The page at https://archeru.github.io/ was not allowed to run insecure content from http://7.url.cn/edu/jslib/comb/require-2.1.6,jquery-1.9.1.min.js. (archeru.github.io, line 975)

[Warning] Invalid CSS property declaration at: * (style.css, line 178)
[Warning] Invalid CSS property declaration at: * (style.css, line 589)
[Warning] Invalid CSS property declaration at: * (style.css, line 591)
[Warning] [blocked] The page at https://archeru.github.io/ was not allowed to run insecure content from http://7.url.cn/edu/jslib/comb/require-2.1.6,jquery-1.9.1.min.js.

[Error] ReferenceError: Can't find variable: require
	global code (main.js:1)

**Comment by allenn** [comment]
把layout/_partial/after-footer.ejs中yiliaConfig里的root: ' <%=theme.root%>'应该也可以
