### ISSUE TITLE
duoshou评论data-thread-key

### ISSUE THREAD

**Issue by frodoking** [litten/hexo-theme-yilia#28]
这个key在什么地方进行设置的？应为我当前有一个文章集成后不知道莫名的有19条评论。应该调用的key不对。希望解答一下

谢谢

**Comment by litten** [comment]
你好，请提供出问题的文章链接，我帮你查一下问题

**Comment by baininghan** [comment]
http://baininghan.com
1. 如果\yilia\_config.yml 如果Menu配置超过两个之后，下排的subnav 就只能显示一半。
2. 我想知道如何关闭disqus评论，目前我只能注释掉article.ejs中关于disqus的代码才能关闭它？

**Comment by baininghan** [comment]
还有我使用你的主题之后，多说评论框，div 的外边距好像变成0了，没有跟正文对齐。

**Comment by litten** [comment]
@baininghan 
1、由于是左右边栏的设计，menu多了肯定会往下挤subnav，建议不要超过4个~想要多的话只有自行修改样式了。
2、在根目录的_config.yml里，有disqus_shortname字段，保持为空就关闭了dis。

我看到你博客现在是好的了，相信你已找到了方法。

**Comment by haohao007** [comment]
你好 请问多说的key如何配置
 #是否开启多说评论，填写你在多说申请的项目名称 duoshuo: duoshuo-key
这句话感觉不太清晰。
我在主题的_config.yml中加入duoshuo：key（多说新建站点得到的密钥）
好像不起作用 底部仍然显示 True's ME正在使用多说（原本主题就有的）

**Comment by litten** [comment]
@haohao007 你好，请提供下blog地址我定位一下问题

**Comment by haohao007** [comment]
你好，blog地址：haoc.info
更新主题后 出现了两个问题：1.标签不见了 2.主页上面的按钮没响应了
谢谢O(∩_∩)O

**Comment by litten** [comment]
http://haoc.info/js/main.js
这份文件不对，正确应该[这样](https://github.com/litten/hexo-theme-yilia/blob/master/source/js/main.js)。

请检查下```yilia\source\js\main.js```文件是否最新；
如果是最新，怀疑是编译问题…执行```hexo clean```命令后重新```hexo s```再看下是否正常。
good luck…

**Comment by haohao007** [comment]
@litten 你好 更新完主题后可以正常显示了 
可是关于多说评论配置的问题 还没解决
我在配置其他主题时 在主题的 _config.yml中配置 duoshuo_shortname: haocc就可以生效
可是在hexo-theme-yilia这样做 好像不行 底部仍然显示 True's ME正在使用多说
谢谢

**Comment by haohao007** [comment]
@litten 你好 请问 这个主题多说评论的可以自主配置了嘛？

**Comment by litten** [comment]
不好意思，我忘了回复了…抱歉！
你的配置写错了哦，按文档，应该是：``duoshuo: "haocc"``，而不是``duoshuo_shortname: haocc``，修改后试一下。
此外可以参考下这份完整的配置：https://github.com/litten/BlogBackup/blob/master/themes/yilia/_config.yml

**Comment by haohao007** [comment]
@litten 嗯。可以了。谢谢。

**Comment by lan2720** [comment]
你好，刚刚使用hexo
按上面的解决方法我把duoshuo: “xxx” 设置成自己的shortkey之后，还是显示true‘s me正在使用多说
博客地址http://lan2720.github.io/
谢谢啦

**Comment by scq000** [comment]
这个Key 怎么设置啊？　duoshuo:　xxxxxxxxxx　后没有作用啊

**Comment by xiyebai** [comment]
duoshuo: *******设置完了，页面上并没有评论框，只有分享，是不是还要做什么？

**Comment by XElengo** [comment]
试了好久还是用不成多说评论，duoshuo: "github-duoshuo-xelengo" 不起作用，文章下面没有评论框，https://xelengo.github.io/

**Comment by XElengo** [comment]
自己解决了，方法虽然不太好；写死这个地方yilia\layout\_partial\post\duoshuo.ejs  ： var duoshuoQuery = {short_name:"xelengo"};
short_name是用多说网站生成的模板 即 工具-->通用代码中的short_name，即 多说-->设置 那里的域名的第一部分，如：xelengo.duoshuo.com 中的xelengo。因为多说的账户名称可以修改，但注册账号时的多说域名不可修改，且账户名称与域名的第一部分允许不同，而多说评论插件是通过访问多说域名进行显示的。所以可能会出错吧。另外本地缓存，github上的代码，以及多说本身都会影响运行结果。谢谢 @litten 
提供的模板
