### ISSUE TITLE
另一种头像问题

### ISSUE THREAD

**Issue by zhaokuohaha** [litten/hexo-theme-yilia#283]
* 问题:  
    `第一次打开首页`的时候头像和网页图标都无法显示<br>
    点击**`所有文章`**之后二者正常显示<br>
    此时`再次打开首页`, 二者正常显示<br>

原因未明啊

> 附博客地址 : [zhaokuohaha.github.io](https://zhaokuohaha.github.io/)

**Comment by FengDeng** [comment]
#288

**Comment by zhaokuohaha** [comment]
没有解决.但是发现了问题:  是http和https的问题
