### ISSUE TITLE
解决头像的问题

### ISSUE THREAD

**Issue by FengDeng** [litten/hexo-theme-yilia#288]
直接修改layout/_partial/left-col.ejs的第六行和第八行为：

			<img src="<%=theme.avatar%>" class="js-avatar show">
			<img src="<%=theme.avatar%>" class="js-avatar show" style="width: 100%;height: 100%;opacity: 1;">

**Comment by zhanghao-blog** [comment]
正解  谢谢  移动端也要改  嘿嘿

**Comment by tylerdong** [comment]
改了也没有用啊，https://avatars2.githubusercontent.com/u/20137895，我设置成这个地址了还是null

**Comment by tylerdong** [comment]
@FengDeng 
我这里第6行是：<img src="<%=theme.avatar%>" class="js-avatar">
第8行是：<hgroup>
改变第6行和第8行的行为要怎么改变呢？ 我理解的是直接把第6行改成<img src="<%=theme.avatar%>" class="js-avatar show" style="width: 100%;height: 100%;opacity: 1;">这样把？

但是我改了，还是不管用，问一下你那里改完之后运行的那些命令呢？

**Comment by voguke** [comment]
在第六行上直接改
在第八行直接添加第二句，把原来的第八行推到第九行去

**Comment by stevenaces** [comment]
```
<div class="intrude-less">
	<header id="header" class="inner">
		<a href="/" class="profilepic">
			<img src="<%=theme.avatar%>" class="js-avatar">
		</a>
		<hgroup>
		  <h1 class="header-author"><a href="/"><%=theme.author%></a></h1>
		</hgroup>
```
我的layout/_partial/left-col.ejs文件的第3到第10行是这样的，怎么改才能正确显示头像？另外，这个主题的_config.yml中的头像url设置为`avatar: /source/img/headimg.png `,路径下有这个图片

**Comment by 123xiao** [comment]
我也想问这个问题 设置头像不展示

**Comment by voguke** [comment]
@stevenaces 你第六行少写了个show
@123xiao 你按你楼上的写，就是把他少写的加上应该就可以了

**Comment by CChanggg** [comment]
我也遇到了上面的问题 按上面写的方法弄了之后图片还是没有出来 然后我把头像路径改为了```avatar: "img/CChang.png"``` 我图片放在```/source/img/CChang.png```

**Comment by CChanggg** [comment]
又遇到一个问题 改了代码 按照我上面的方法是显示了主页头像的 但是我点击某篇文章头像又不显示了 请问有好的解决方法吗

**Comment by litten** [comment]
@CChanggg 我看你的blog貌似已经解决了？

这种问题，一般都是配置的路径问题。
如果你能区分这三种写法的区别，就应该没问题了
``/source/img/CChang.png``
``./source/img/CChang.png``
``source/img/CChang.png``

**Comment by Earlzs** [comment]
@CChanggg 我也碰到这个问题了，请问是怎么解决的呢~

**Comment by fishenjoy** [comment]
alipay: /img/alipay.png 这样就可以了，路径前面加个斜杠/

**Comment by fishenjoy** [comment]
https://fishenjoy.github.io/img/alipay.png 自己可以测试一下

**Comment by Yelloboy** [comment]
请问next主题设置与这个类似吗？

**Comment by Dandelionboy** [comment]
把你的头像图像放置在yilia/source 文件夹下，然后配置url 写“/头像图片民.格式后缀”。

**Comment by qq1063410652** [comment]
我通过下面方法解决了
`<img src="<%=theme.root%>/<%=theme.avatar%>" class="js-avatar">`

**Comment by yixingshao** [comment]
可能你们的配置是这么写的
_avatar:/img/test.png_
哈哈，有没有发现少了空格
_avatar: /img/text.png__

**Comment by yixingshao** [comment]
可能你们的配置是这么写的
`avatar:/img/test.png`
哈哈，有没有发现少了空格。

**Comment by BearDare** [comment]
可能你们的配置是这么写的
`avatar:/img/test.png`
哈哈，跟下面比较一下，看是不是少了一个空格。
`avatar: /img/test.png`

**Comment by kkewwei** [comment]
我按照上面尝试修改第六行和第八行，也不行，最终我也是直接修改的第六航这句：
既然根据代码生成的访问图片的地址有问题，为何不直接将第六行相对地址换成了一个真实的网络地址：
<img "src="http://xxx.jpg" class="js-avatar">
最终问题解决了。

**Comment by hjk002** [comment]
看了楼上各位前辈的答案  我的已经OK.在次十分感谢各位大佬
只需要改第六行  以及URL就可以了。
avatar: img/touxiang.jpg
头像图片存放在: socurse/img/touxiang.jpg

**Comment by liangqinwei** [comment]
楼上，你是怎么修改了，把修改的第六行，发出来看看

**Comment by liangqinwei** [comment]
完美解决了，
将第六行修改成如下形式：

<img src="<%=theme.root%><%=theme.avatar%>" class="js-avatar"> 






在
#你的头像url   注意，有空格的
avatar: img/myicon.jpg

**Comment by liangqinwei** [comment]
上面看不到第六行 补上第六行修改
<img src="<%=theme.root%>/<%=theme.avatar%>" class="js-avatar">

**Comment by kopitetorres** [comment]
楼上的方法都试了
第一 avatar:img/test.png 不加空格生成时会报错，但加了空格也不现实
第二 加了show标签 依然是null

所以 我直接把left-col.ejs 和 mobile-nav.ejs 里面的<%=theme.avatar%>写死了 不配置了

**Comment by hdq1123** [comment]
解决了, 需要修改上面说的第六行 加个show ,然后avatar: "img/myicon.jpg" 路径需要加上引号,不加双引号显示不出来

**Comment by RainCollector** [comment]
@CChanggg 碰到你一样的问题，主页头像能显示，但是进入某篇文章内部头像就不显示了，按照上面提供的两种第6行修改的方法，并且头像路径设置为avatar:  "img/touxiang.jpg" 以及avatar:  /img/touxiang.jpg，都可以解决主页头像的问题，但都不能解决文章内头像不显示的问题。

**Comment by Johnsonzcode** [comment]
首页可显示头像，文章内部不显示头像和打赏二维码

**Comment by yulimchen** [comment]
> 完美解决了，
> 将第六行修改成如下形式：
> 
> <img src="<%=theme.root%><%=theme.avatar%>" class="js-avatar">
> 
> 在
> #你的头像url 注意，有空格的
> avatar: img/myicon.jpg

感谢感谢，已解决。

**Comment by itzhouq** [comment]
1. 修改blog\themes\yilia\layout\_partial\left-col.ejs第六行
![image](https://user-images.githubusercontent.com/37930443/54656073-3b172800-4aff-11e9-95b0-39085bf1bc94.png)

2. 头像存放的路径\blog\source\img

3. blog\themes\yilia\_config.yml配置文件加上 /img/tx.jpg(注意/img前面有空格)
![image](https://user-images.githubusercontent.com/37930443/54656173-99440b00-4aff-11e9-9071-8f3edf605658.png)

**Comment by wyxy2005** [comment]
不生效的根源是得在根目录 _config.yml 配置avatar 因为root也是那定义的，可以试试看效果，反正我是这么配置后才生效

**Comment by Robbie-Han** [comment]
第六行按照楼主那行复制
配置文件：不要写source
avatar: /img/IMG_4175.JPG

**Comment by 8bun** [comment]
每个版本的hexo的文件夹结构都会不一样，我的是比较新的版本；
1. 头像位于sidebar，其布局位于 ..  \themes\hexo-theme-next\layout\_macro\sidebar.swig定义，你可以打开看看这里面定义头像html代码的地方有没有写错，尤其是红线部分：
![image](https://user-images.githubusercontent.com/37058967/60435215-83380180-9c3b-11e9-983c-c2566570fed9.png)

如果都没有问题，那么请检查自己在/theme/下的_config.yml的avatar是否按要求填写；一般路径都按
 In theme directory (source/images): /images/avatar.gif
 In site directory (source/uploads): /uploads/avatar.gif
应该就是正确的。
如果也正确，再检查定义头像css部分的文件：
.. \themes\hexo-theme-next\source\css\_common\components\sidebar\sidebar-author.styl文件是否写错；
然后，问题基本就解决了（记得修改html内容是会延迟一会才生效的，在本地有时候是不能马上看到的，你最好去自己真正部署的io网站看一下）

**Comment by chengaf** [comment]
> 看了楼上各位前辈的答案 我的已经OK.在次十分感谢各位大佬
> 只需要改第六行 以及URL就可以了。
> avatar: img/touxiang.jpg
> 头像图片存放在: socurse/img/touxiang.jpg

正解！

**Comment by jiema0217** [comment]
一开始路径设置为avatar: img/touxiang.jpg
进过第六行的修改也不起作用
把路径写成avatar: /img/touxiang.jpg
就好了，真神奇，用的yilia的主题，
希望对你们有用。/笑哭

**Comment by WuDier** [comment]
> 可能你们的配置是这么写的
> `avatar:/img/test.png`
> 哈哈，跟下面比较一下，看是不是少了一个空格。
> `avatar: /img/test.png`

棒诶

**Comment by JoeyBling** [comment]
use ```<img src="<%- url_for(theme.avatar) %>" class="js-avatar">```

**Comment by aladdin99** [comment]
> 我也遇到了上面的问题 按上面写的方法弄了之后图片还是没有出来 然后我把头像路径改为了`avatar: "img/CChang.png"` 我图片放在`/source/img/CChang.png` 成功出来了 可以参考下

按照你的方法果然可以，你是人才！！！

**Comment by lulu19940307** [comment]
> 完美解决了，
> 将第六行修改成如下形式：
> 
> <img src="<%=theme.root%><%=theme.avatar%>" class="js-avatar">
> 
> 在
> #你的头像url 注意，有空格的
> avatar: img/myicon.jpg

按照这种方法解决了！非常感谢🙏

**Comment by Russell1997** [comment]
一旦进入文章内，头像就不显示了，怎么办呢？

**Comment by wsuo** [comment]
我是这样解决的，既然他总是显示默认的头像图片，那他肯定有路径，我不需要知道路径在哪里配置，只需要找到那个默认头像然后用我想要的图片把它给替换掉，同名同路径肯定能显示，于是我照做了，成功了！！！自底向上解决问题，另外默认头像的位置是themes\next\source\images\avatar.gif

**Comment by chensming** [comment]
> 我也遇到了上面的问题 按上面写的方法弄了之后图片还是没有出来 然后我把头像路径改为了`avatar: "img/CChang.png"` 我图片放在`/source/img/CChang.png` 成功出来了 可以参考下

我也这样子，但是到了指定的文章下头像就不行了

**Comment by sorrowfeng** [comment]
进入二级页面，头像就不显示了是什么问题?

**Comment by chensming** [comment]
我没有去尝试解决。转而放弃Hexo去用Hugo咯。你可以了解一下Hugo或者换一个主题。不过有朋友和我说过要怎么设置。不过那时忙，就没怎么看了。希望这条回复对你有帮助。------------------ 原始邮件 ------------------
发件人: "一色彩羽"<notifications@github.com>
发送时间: 2020年3月29日(星期天) 下午4:20
收件人: "litten/hexo-theme-yilia"<hexo-theme-yilia@noreply.github.com>;
抄送: "chensming"<654916418@qq.com>;"Comment"<comment@noreply.github.com>;
主题: Re: [litten/hexo-theme-yilia] 解决头像的问题 (#288)




 
进入&#x4E8C;级页面，头像就不显示了是什么问题?
 
&mdash;

**Comment by white-loub** [comment]
我试过以后是这样：
1.虽然不懂原理，但是不用修改第六行（实际上作者的文件里也未修改，但是可以正常显示）；
2.头像文件的根目录是source，因此如果图片放在source文件夹内的img文件夹下，地址应该写为：/img/touxiang.jpg，注意如果写为“img/touxiang.jpg”（没有开头的斜杠），则会导致二级页面头像不显示。

**Comment by JoeyBling** [comment]
参考[hexo-theme-yilia-plus](https://github.com/JoeyBling/hexo-theme-yilia-plus)主题替换文件即可
> https://github.com/JoeyBling/hexo-theme-yilia-plus/blob/master/layout/_partial/left-col.ejs

**Comment by B-ZhaoE** [comment]
朋友们,如果上面方法无法解决，你们可以尝试使用超链接到github库中的头像网页

**Comment by 8bun** [comment]
您好，邮件已收到，如果有什么问题，我会尽快回复。
