### ISSUE TITLE
整合了遇到的问题，可以显示正常，有问题的可以看看

### ISSUE THREAD

**Issue by LinuxSzp** [litten/hexo-theme-yilia#294]
https://linuxszp.github.io/  ，整理了需要修改的地方

**Comment by tianglin** [comment]
lz怎么解决头像不显示的问题

**Comment by LinuxSzp** [comment]
你可以看我整理的那个博客，你从litten主题作者这下载一份新的，按照https://linuxszp.github.io/ 搭建个人博客那篇里面修改的方法修改就可以显示出来，或者你从我的github里面下载已经修改好的yilia
