### ISSUE TITLE
Hexo根目录下的_config.yml中已经有了一个root配置项了，主题里为什么还有一个？

### ISSUE THREAD

**Issue by allenn** [litten/hexo-theme-yilia#297]
Hexo根目录下的_config.yml中已经有了一个root配置项了，主题里为什么还有一个？而且在主题中，有些地方用confg.root，有些地方用themes.root，让人很困惑，而且容易出错，建议直接使用config.root就好

**Comment by LaiLa06** [comment]
https://linuxszp.github.io/

**Comment by litten** [comment]
因为hexo更新了很多个版本，原先不是这样的。
主题兼容一把泪，其次是我的锅，没有及时跟进。
现在已修复。

**Comment by allenn** [comment]
@litten 👍
