### ISSUE TITLE
由root引发的yiliaConfig报错的问题

### ISSUE THREAD

**Issue by Vicfeel** [litten/hexo-theme-yilia#298]
_config.yml中root的默认值是'\'，在_partial/after_footer.ejs文件中声明了var yiliaConfig = { ... root: <%=config.root%>}      这样在generator之后，在页面中出现yiliaConfig = { ... root:/} 浏览器会报错语法无法识别，导致后面用到yiliaConfig语句无法生效，页面显示会出现很多问题，该怎么解决？

**Comment by LaiLa06** [comment]
我也想问这个

**Comment by shishifanbuxie** [comment]
同问，就是这个问题
![image](https://cloud.githubusercontent.com/assets/8510150/18335868/34c5593a-75b5-11e6-8b93-993c32752b99.png)

**Comment by LaiLa06** [comment]
http://xingbofeng.com/2016/09/05/hexo+github%E6%90%AD%E5%BB%BA%E4%B8%AA%E4%BA%BA%E5%8D%9A%E5%AE%A2/

**Comment by LaiLa06** [comment]
http://xingbofeng.com/2016/09/05/hexo+github%E6%90%AD%E5%BB%BA%E4%B8%AA%E4%BA%BA%E5%8D%9A%E5%AE%A2/  这个上面有解决办法
