### ISSUE TITLE
怎么取消github强制使用https

### ISSUE THREAD

**Issue by lowkeyhan** [litten/hexo-theme-yilia#305]
你好，我看你的主页使用的http的链接，我的总是定向的https，而且设置里也不让取消。造成的影响就是标签哪里“所有文章” 这个链接弹出来为空白，用谷歌浏览器调试发现报错是因为弹出式访问了http的页面，所以不能访问。所以想问一下

**Comment by frapples** [comment]
我发现是这个所有文章会请求https://yourname.github.io/archive这个地址，但是这个地址被github重定向到http://yourname.github.io/archive/

chrome默认是禁止https的网页请求非http内容的，于是就这样了。
解决办法是修改代码，让它直接请求https://youname.github.io/archive/。我已经提了pull request了。

**Comment by litten** [comment]
谢谢 @frapples
