### ISSUE TITLE
分享功能的https不兼容的问题怎么处理的啊

### ISSUE THREAD

**Issue by lwb19880121** [litten/hexo-theme-yilia#308]
控制台显示的错误信息Mixed Content: The page at 'https://80sky.github.io/2016/09/22/Canvas%E5%AE%9E%E7%8E%B0%E7%83%9F%E8%8A%B1%E6%95%88%E6%9E%9C/' was loaded over HTTPS, but requested an insecure script 'http://v3.jiathis.com/code/jia.js?uid=1405949716054953'. This request has been blocked; the content must be served over HTTPS.

**Comment by litten** [comment]
已fix，请更新
