### ISSUE TITLE
language 设置报错

### ISSUE THREAD

**Issue by neconano** [litten/hexo-theme-yilia#309]
FATAL can not read a block mapping entry; a multiline key may not be an implicit key at line 8, column 12:
    description:

求真相

**Comment by litten** [comment]
参考：https://github.com/hexojs/hexo/issues/1753

**Comment by neconano** [comment]
@litten 谢谢，虽然大概知道了原因，但不知道如何处理，最后用的其他方式解决的

将zh-hans内容覆盖到de里面了
