### ISSUE TITLE
tags和category在全文显示的文章中出现错位

### ISSUE THREAD

**Issue by bitmingw** [litten/hexo-theme-yilia#31]
首先感谢 @litten 对主题做出的改进！

我在测试时发现了一个bug. 如[这篇博客](http://bitmingw.com)的首页，在PC浏览器中yilia主题把文章的tags和category放在了每篇文章的末尾。对于使用`<!-- more -->`在首页只显示摘要的文章没有什么问题，对全文显示的文章会出现tags和category与文字内容重叠的情况。

建议您修正一下程序逻辑，在没有`<!-- more -->`的情况下依旧在首页的每篇文章生成下划线，用于放置tags和category.

**Comment by litten** [comment]
已修改，谢谢指出
