### ISSUE TITLE
google analytics的追踪代码被添加到了body中，导致google webmaster无法准确验证站点

### ISSUE THREAD

**Issue by allenn** [litten/hexo-theme-yilia#310]
google analytics的追踪代码被添加到了body中，导致google webmaster无法准确验证站点。

根据google analytics的[帮助文档](https://support.google.com/analytics/answer/1008080?hl=zh-Hans)，追踪代码需要放在head标签内，但实际生成的页面中，追踪代码被放在了body里。

**Comment by litten** [comment]
谢谢提醒，已修复
