### ISSUE TITLE
IOS微信打开闪退

### ISSUE THREAD

**Issue by xmsec** [litten/hexo-theme-yilia#311]
IOS端微信打开这个界面闪退，可能是主题原因，能力不足，无法确认，打扰了。
http://blog.xmsec.cc/blog/2016/02/04/Physics-Bird/

**Comment by litten** [comment]
我这儿尝试没发生闪退，请提供下手机型号和iOS版本信息？

**Comment by xmsec** [comment]
5S和6PLUS，微信当前最新版本。也跟微信那边提交了下。是在朋友圈分享后打开闪退的。

**Comment by litten** [comment]
能让微信崩掉的web也是可以立个纪念碑留念一下了…
原因待查，但猜到一个原因，等我验证一下迟些回复你。

**Comment by litten** [comment]
已解决。估计是微信内嵌iframe会引发问题。
