### ISSUE TITLE
github和微博小图标为什么没有颜色？影响总体美观！

### ISSUE THREAD

**Issue by Forecheng** [litten/hexo-theme-yilia#314]
1.github和微博小图标没有颜色，其他的比如豆瓣图标就是绿色的，请问这个在哪里可以更改呢？
2.subnav下的mail该如何配呢？我配的是邮箱地址：“*****@163.com”，这个不行。
#谢谢#

**Comment by Forecheng** [comment]
找到位置了，已修改。

**Comment by clayclayclay** [comment]
@Forecheng 请问一下在哪里修改呀？

**Comment by Forecheng** [comment]
@clayclayclay 这个比较繁琐，在themes\yilia\source\style.js，在里面搜索facebook、douban、weibo等关键字，改变颜色即可。

**Comment by myoneray** [comment]
themes\yilia\source\style.js 中沒有文本结构，好乱，我在修改的themes/yilia/source-src/css/里面的样式　但是发布后还是原效果。想了下是没有编译的问题，要怎么重新编译scss？ @Forecheng

**Comment by Forecheng** [comment]
@myoneray 你说的这个不了解，无法帮助到你，我只是在themes\yilia\source\style.js修改一些颜色值而已，包括微博等图标的颜色，文章标题的颜色，链接的颜色等。

**Comment by litten** [comment]
@myoneray @Forecheng 
“没有文本结构，好乱”是因为经过了压缩合并，以追求最好的性能。
具体编译步骤请参考wiki：[《Yilia源码目录结构及构建须知》](https://github.com/litten/hexo-theme-yilia/wiki/Yilia%E6%BA%90%E7%A0%81%E7%9B%AE%E5%BD%95%E7%BB%93%E6%9E%84%E5%8F%8A%E6%9E%84%E5%BB%BA%E9%A1%BB%E7%9F%A5)

**Comment by myoneray** [comment]
@litten 成功！ thx

**Comment by ghost** [comment]
@myoneray  老铁怎么改的啊？我按照作者的步骤，到`npm run dev`就卡着不动了，没有了后文
