### ISSUE TITLE
favicon被解析成http链接

### ISSUE THREAD

**Issue by ExiaHan** [litten/hexo-theme-yilia#316]
favicon会被解析成 http://favicon.png/
这样的链接，导致无法显式favicon

我把
layout/_partial/head.ejs里第30行
` <link rel="icon" href="<%= config.root %><%- theme.favicon %>">`
去掉`<%= config.root %>`，改成
`<link rel="icon" href="<%- theme.favicon %>">`
后就可以了。

**Comment by Forecheng** [comment]
@ExiaHan 谢谢，正解！

**Comment by litten** [comment]
@ExiaHan 已修复，谢谢提醒
