### ISSUE TITLE
文章列表如何居中显示？

### ISSUE THREAD

**Issue by clayclayclay** [litten/hexo-theme-yilia#317]

**Comment by litten** [comment]
@clayclayclay 不支持此功能，抱歉。
如有特殊需要请自行fork修改，具体编译步骤请参考wiki：[《Yilia源码目录结构及构建须知》](https://github.com/litten/hexo-theme-yilia/wiki/Yilia%E6%BA%90%E7%A0%81%E7%9B%AE%E5%BD%95%E7%BB%93%E6%9E%84%E5%8F%8A%E6%9E%84%E5%BB%BA%E9%A1%BB%E7%9F%A5)
