### ISSUE TITLE
# 是否开启动画效果 animate: true

### ISSUE THREAD

**Issue by myoneray** [litten/hexo-theme-yilia#318]
1>　　# 是否开启动画效果 animate: true  　不起作用　怎么办？
2>       修改SCSS 样式然后之后没有效果,需要怎么做？

**Comment by Forecheng** [comment]
@litten 同问，设置animate: true，确实没动画。

**Comment by litten** [comment]
因为在整改，现已去掉这个配置。请更新一下主题。
