### ISSUE TITLE
Unhandled TypeError错误

### ISSUE THREAD

**Issue by ccwinner** [litten/hexo-theme-yilia#322]
Unhandled rejection TypeError: /Users/../themes/yilia/layout/layout.ejs:14
    12|       <%- partial('_partial/footer') %>
    13|     </div>
 >> 14|     <%- partial('_partial/after-footer') %>
    15|     <%- partial('_partial/tools') %>
    16|     <%- partial('_partial/viewer') %>
    17|   </div>

**Comment by ccwinner** [comment]
是因为JS版本问题吗

**Comment by youtsea** [comment]
@ccwinner themes/yilia目录下需要有个`_config.yml`，具体内容参考`README.md`

**Comment by litten** [comment]
@ccwinner 不好意思，我误删了_config.yml文件，请更新一下。

**Comment by ccwinner** [comment]
好的😀 刚接触不太了解
