### ISSUE TITLE
heroku部署的问题

### ISSUE THREAD

**Issue by wangyeming** [litten/hexo-theme-yilia#324]
你好，我是小白 ，请问该主题支持部署到heroku上吗？

执行 hexo deploy 遇到错误：

Failed to detect set buildpack https://codon-buildpacks.s3.amazonaws.com/buildpacks/heroku/nodejs.tgz

请问该如何解决吗？

**Comment by litten** [comment]
支持。但这个问题不会是yilia和hexo导致。
应该是使用heroku的问题，请详查其官方文档。

（怀疑是推送的目录缺失package.json文件？）

**Comment by wangyeming** [comment]
谢谢，我找到解决办法了，执行下面两行命令：

    heroku buildpacks:set heroku/nodejs
    heroku buildpacks:remove heroku/nodejs

[参考处](http://ryanlion.logdown.com/posts/776050-wow-meet-for-the-first-time-hexo)

具体细节我不太清楚，不过可以确定我的问题和主题是没有关系的，抱歉，打扰到你呢~

**Comment by litten** [comment]
:+1:
