### ISSUE TITLE
请教如何开启小房子菜单？

### ISSUE THREAD

**Issue by geomsx** [litten/hexo-theme-yilia#325]
下载了这个主题，非常好。请问看了几个别人的page，有小房子和弹出菜单，但是我下载的和作者自己的BLOG都没有这个小房子和菜单，请问如何开启？

**Comment by litten** [comment]
@geomsx 小房子是比较旧的版本，因为信息过多不好展示，新版被我去掉了…
如果你比较喜欢它，可以自己使用这个[旧的commit](https://github.com/litten/hexo-theme-yilia/commit/8a1778303b2b0b094b390a994fef04b0ed575c7d)
