### ISSUE TITLE
不好哦意思，弱弱的问一下，写markdown的话图片应该放在哪个目录下

### ISSUE THREAD

**Issue by mrpsweet** [litten/hexo-theme-yilia#327]
不好哦意思，弱弱的问一下，写markdown的话图片应该放在哪个目录下，试了很多次都没有把图片显示出来，谢谢大神了。

**Comment by litten** [comment]
没有统一标准。
我习惯放```/source/assets/```里
供参考：[博客备份](https://github.com/litten/BlogBackup)

**Comment by mrpsweet** [comment]
恩，已经实现了，可以close了谢谢

**Comment by litten** [comment]
👍
