### ISSUE TITLE
弱鸡问问，怎样编辑页面

### ISSUE THREAD

**Issue by liangpu597** [litten/hexo-theme-yilia#330]
弱弱的问一下，超链接字体的样式文件是哪一个？我想修改一下，超链接的字体样式。谢谢！

**Comment by Jemair** [comment]
/yilia/source/main.css
建议先在页面上找到你要修改的类名，再在这个文件里来找
不然要死人的

**Comment by litten** [comment]
修改```/source-src/css/core/_reset.scss```，再编译到```/yilia/source/main.css```里

编译步骤请参考wiki[《Yilia源码目录结构及构建须知》](https://github.com/litten/hexo-theme-yilia/wiki/Yilia%E6%BA%90%E7%A0%81%E7%9B%AE%E5%BD%95%E7%BB%93%E6%9E%84%E5%8F%8A%E6%9E%84%E5%BB%BA%E9%A1%BB%E7%9F%A5)

虽然这样要经过编译，麻烦了一点，但是出于工程化的考虑，也是大势所趋。并且性能才能达到极致。

@Jemair 你的方法也行，但不推崇

**Comment by liangpu597** [comment]
哦，谢谢了！
我去试一下！

在 2016年11月23日 下午12:23，litten <notifications@github.com>写道：
