### ISSUE TITLE
新的主题配置好了，console.log两个错误不是很懂希望有时间帮我看看

### ISSUE THREAD

**Issue by mrpsweet** [litten/hexo-theme-yilia#332]
GET https://v3.jiathis.com/code/jia.js?uid=............
net::ERR_SSL_VERSION_OR_CIPHER_MISMATCH

litten.me:9005/badjs/?id=1&uin=https://mrpsweet.github.io&from=https%3A%2F%…mder%2F&msg=yilia-mrpsweet.github.io&ext=%7B%7D&level=4&_t=.......:1 GET https://litten.me:9005/badjs/?id=1&uin=https://mrpsweet.github.io&from=http…8Cmder%2F&msg=yilia-mrpsweet.github.io&ext=%7B%7D&level=4&_t=.......... net::ERR_CONNECTION_CLOSED

**Comment by litten** [comment]
第一个错误是jiathis不支持https，我已经在想办法解决了，很快会上新版本；

第二个错误其实不是错误，可以忽略，是上报统计用的。我想让用yilia的朋友，能看到自己网站的访问统计报表。实验性功能，我觉得挺好的，请期待

**Comment by mrpsweet** [comment]
thank you  那就等大神更新啦

**Comment by cxw42** [comment]
For English speakers finding this on Google, my problem was that I was trying to access a hexo server as `https://...`.  `http://...` worked fine.
