### ISSUE TITLE
tags and categories 页面不能正确生成 页面没有内容

### ISSUE THREAD

**Issue by zewenwang** [litten/hexo-theme-yilia#336]
已正确定义tags and categories目录，并正确生成相应的文件夹及index.md。
但是tags and categories 列表页是空的
http://www.zewen.win/categories/
http://www.zewen.win/tags/

而对于单个categories或tag的文章列表是有内容的
http://www.zewen.win/categories/Android/
http://www.zewen.win/tags/Android/

**Comment by litten** [comment]
这样是正常的…
对于tags和categories而言，肯定要针对单个关键词才有意义呀
所以hexo本身没有单独生成tags和categories页面的，对于大多数情景，archives页面已经足够了。

如果需要，请到hexo里提issues哈
