### ISSUE TITLE
使用新版本主题之后，disqus评论太宽

### ISSUE THREAD

**Issue by SuperDannyBoy** [litten/hexo-theme-yilia#337]
更新到新的主题之后，发现评论区域太过于贴近左侧。看起来不怎么好看，请问是否需要自己改动布局？
![a4e2f558-78fb-494c-9b0e-4464112cb76b](https://cloud.githubusercontent.com/assets/5237197/20638721/eb597696-b3e9-11e6-919d-c482f7de0c86.png)

**Comment by litten** [comment]
好的，会fix。谢谢提醒

**Comment by wupinlang** [comment]
![image](https://cloud.githubusercontent.com/assets/9389834/21972706/51383748-dbf6-11e6-8778-1ed66b7c1bf6.png)
希望能尽快fix这个问题

**Comment by litten** [comment]
@SuperDannyBoy @wupinlang 
已修改。sorry，忘了这个bug…

**Comment by wupinlang** [comment]
thx :)

**Comment by SuperDannyBoy** [comment]
@litten 感谢
