### ISSUE TITLE
新版本主题“置顶”图钉样式丢失

### ISSUE THREAD

**Issue by SuperDannyBoy** [litten/hexo-theme-yilia#338]
使用置顶之后，发现图钉图标无法显示出来，老版本的是可以的。
有图钉旧版本：
![default](https://cloud.githubusercontent.com/assets/5237197/20699514/ac9461ea-b642-11e6-991e-6dd72a145c22.jpg)
无图钉新版本：
![default](https://cloud.githubusercontent.com/assets/5237197/20699530/c69f066c-b642-11e6-82c8-e1540589df83.png)

**Comment by SuperDannyBoy** [comment]
是否是字体库导致的？

**Comment by litten** [comment]
是的…谢谢提醒。马上修复

**Comment by litten** [comment]
建议先别更新，正在做个大版本，有些新功能包括你想要的打赏。
这两天会提交

**Comment by SuperDannyBoy** [comment]
好的。感谢！
