### ISSUE TITLE
手机版tags只显示一个圈圈

### ISSUE THREAD

**Issue by GaHoKwan** [litten/hexo-theme-yilia#345]
如题

**Comment by litten** [comment]
之前有个版本使用了fetch，结果发现手机覆盖率不行，后来改了。
可能得：1、再更新一下；2、清掉浏览器缓存再试试。

或者你用手机访问下我的正常吗？手机型号也请告知，谢谢。

**Comment by GaHoKwan** [comment]
你的blog也不正常，iPhone5s

**Comment by shuaijunlan** [comment]
我的博客tags也不正常，在uc浏览器不能显示，在Safari可以显示。

**Comment by 0031** [comment]
我也是这个问题，手机端无法显示，安卓

**Comment by litten** [comment]
请更新
