### ISSUE TITLE
点击“所有文章”，提示缺失，按照提示步骤完成后，依然未解决

### ISSUE THREAD

**Issue by coderSkyChen** [litten/hexo-theme-yilia#347]
![_20161207161211](https://cloud.githubusercontent.com/assets/16058650/20960052/63a3cb8a-bc99-11e6-86f1-87bfa590e434.png)

**Comment by litten** [comment]
删掉博客的public文件夹，重新```hexo g```试试。
直到你能看的public文件夹内有生成content.json文件，这个功能才可用。

如果还是不行，到[hexo-generator-json-content](https://github.com/alexbruno/hexo-generator-json-content)问下作者
毕竟我不产生这个插件，只是插件的搬运工…

**Comment by coderSkyChen** [comment]
好勒~谢谢~  我去问问这个的作者吧，还是不能生成content.json。。。。

**Comment by coderSkyChen** [comment]
@litten litten我又来麻烦你啦，查了一个日志，载入hexo-generator-json-content时出错了，插件作者说是版本不兼容问题，然后我就安装了一个1.4低版本的hexo-generator-json-content，也成功的生成了conten。json，但是hexo g之后依然有这个问题。。。。。

**Comment by coderSkyChen** [comment]
@litten 感谢您~~问题已解决
不要安装hexo-generator-json-content最新版
不要安装hexo-generator-json-content最新版
不要安装hexo-generator-json-content最新版
安装2.0的版本的就可以了。。
您做的这个theme真的赞！对伟大的前端充满敬意~~~~~~撒花~~~

**Comment by ckj258** [comment]
@coderSkyChen  这个问题后来怎么解决的？

**Comment by coderSkyChen** [comment]
@ckj258 结束issue的时候我提到了，但是似乎被判为废话了.....
对于我来说，安装hexo-generator-json-content的2.* 版本，解决了此问题。希望对你有参考，主要是版本问题吧。
![qq 20161208111648](https://cloud.githubusercontent.com/assets/16058650/20996361/1573ca56-bd38-11e6-8b6c-f54a2758fbf6.png)

**Comment by RobustCat** [comment]
这个问题应该是插件和Node.js 版本兼容性出现问题导致的。尝试升级/降级 Node.js，或升级/降级 插件可以解决。

**Comment by chewenkai** [comment]
@RobustCat 谢谢，确实是，我认为升级Node.js是正确的。我刚从5.X升级到7.X，问题解决了
