### ISSUE TITLE
克隆新主题，点击所有文章按钮，弹出页面中提示报错--缺失模块

### ISSUE THREAD

**Issue by LuciaMooreLU** [litten/hexo-theme-yilia#349]
环境：
hexo: 3.2.2
hexo-cli: 1.0.2
os: Windows_NT 10.0.10586 win32 x64
http_parser: 2.5.0
node: 4.2.3
v8: 4.5.103.35
uv: 1.7.5
zlib: 1.2.8
ares: 1.10.1-DEV
icu: 56.1
modules: 46
openssl: 1.0.2e

操作：
git clone 新主题，将之前写的文章落入到/source/_posts下，hexo g -d 无报错，点击所有文章，页面提示缺失模块。

![findsomething](https://cloud.githubusercontent.com/assets/16363568/20976612/02a64d36-bcde-11e6-8182-942c64f2c85f.jpg)

过程：
根据提示，我执行了命令
![npminstall](https://cloud.githubusercontent.com/assets/16363568/20976787/93850d42-bcde-11e6-808d-d4c6622e5bec.jpg)

修改了hexo/_config.yml
![jason](https://cloud.githubusercontent.com/assets/16363568/20976844/c1cacf84-bcde-11e6-8902-78d5e2f38404.jpg)

结果是使用hexo g，hexo d报错，页面仍然还是之前的模块缺失
![error](https://cloud.githubusercontent.com/assets/16363568/20976892/ea36dd00-bcde-11e6-97bf-29ea8fe3d9e7.jpg)

报错是加载失败，hexo-generator-json-content

前端小白，上网查询这个报错，可能是我百度/谷歌的姿势不对，故而没找到解决方法。
请求大家帮忙指点一下是我哪个地方操作错误。
在此谢谢了！

**Comment by coderGray1296** [comment]
我也是这个问题，而且tag也显示不出来！！！同求解

**Comment by mrpsweet** [comment]
您克隆主题，然后npm嘛~要根据常理出牌~
我一般这样发布`hexo clean && hexo g && hexo d`

**Comment by zengAlex** [comment]
你的目录不对，要在根目录下安装 @LuciaMooreLU

**Comment by zengAlex** [comment]
你应该先看下hexo 官网的介绍先。先了解下基本的api

**Comment by mrpsweet** [comment]
`http://www.jianshu.com/p/4eaddcbe4d12`
你看看这个只能帮到这了
***希望这个对你有帮助***

**Comment by litten** [comment]
两个问题，
1. node版本太低，需要升级到6.2以上版本；
2. 安装模块的目录不对… 所谓博客根目录，是指```/f/luciaM```呀。

@zengAlex 的建议是对的，先了解下hexo基本的api与目录结构

**Comment by LuciaMooreLU** [comment]
感谢大家的帮助，万分感谢，鞠躬！！！之前深更半夜截图截错了。
主要问题是node的版本太低，升级一下版本即可。已经恢复了。
![jsoncontent](https://cloud.githubusercontent.com/assets/16363568/20997723/2dc4355e-bd43-11e6-98fa-2cc26e84d7e2.jpg)

@coderGray1296 碰到上面截图的情况，升级一下版本哟！

**Comment by lbrant** [comment]
更新node.js就行了
