### ISSUE TITLE
列表下的代码块会有边框

### ISSUE THREAD

**Issue by douxingxiang** [litten/hexo-theme-yilia#35]
如果在列表下添加块级代码，代码会变成这样：
![vnlpp30u 7_q i c5 9awb](https://cloud.githubusercontent.com/assets/1589027/6590841/6bbf4a80-c7f2-11e4-901e-3bad13589579.png)

对应的markdown文件，比如
<pre>
1. 安装Nodejs
2. 安装Chocolatey

        @powershell -NoProfile -ExecutionPolicy unrestricted -Command "iex ((new-object net.webclient).DownloadString('https://chocolatey.org/install.ps1'))" && SET PATH=%PATH%;%ALLUSERSPROFILE%\chocolatey\bin
</pre>
需要在`highlight.styl`文件中
``` css
.article-entry
  pre, code
    font-family: font-mono
    font-size: 1em
  code
    background: color-background
    text-shadow: 0 1px #fff
    padding: 0 0.3em
    border-radius: 0.4em
  pre
    @extend $code-block
    code
      background: none
      text-shadow: none
      padding: 0
      border: none //添加这一行
```

**Comment by litten** [comment]
好的
