### ISSUE TITLE
我的页面显示不全，是因为linux系统的原因吗？还是环境没有配置好

### ISSUE THREAD

**Issue by coderGray1296** [litten/hexo-theme-yilia#350]
您可以直接进入我的博客，目前就是那个状态

**Comment by litten** [comment]
并不是linux的锅… 自己先找下原因。

感觉你还没有熟悉hexo基本命令和_config.yml配置，这些是要先了解的，请多查下文档… 不然我也不知道从何说起。磨刀不误砍柴工，加油

这份是我的现有配置，供你参考：
[BlogBackup](https://github.com/litten/BlogBackup)
