### ISSUE TITLE
我发现一个诡异的事情，评论区是别的评论~

### ISSUE THREAD

**Issue by mrpsweet** [litten/hexo-theme-yilia#351]
`https://mrpsweet.github.io/2016/10/10/git%E5%B8%B8%E7%94%A8%E5%91%BD%E4%BB%A4/`
这是我blog的地址，但是评论应该是这篇blog
`http://nomadlx.github.io/2015/03/15/git%E5%B8%B8%E7%94%A8%E5%91%BD%E4%BB%A4/`
是不是我的细节遗漏了导致这个问题的~~

**Comment by litten** [comment]
因为你跟另外一个人，都写错了_config.yml里的duoshuo配置
没猜错的话，都写的```duoshuo: "true"```？

要把自己申请的duoshuo-key填进去呀

**Comment by mrpsweet** [comment]
```
#是否开启多说评论，填写你在多说申请的项目名称 duoshuo: duoshuo-key
#若使用disqus，请在博客config文件中填写disqus_shortname，并关闭多说评论
#duoshuo : true
mrpsweet-blog : 6d6252c5bd28b
```
应该改成这样的写法对吧

**Comment by litten** [comment]
不对。
```duoshuo: mrpsweet-blog```

你可以找下其他issues，比如[112](https://github.com/litten/hexo-theme-yilia/issues/112)

这份配置，供你参考[BlogBackup](https://github.com/litten/BlogBackup/blob/master/themes/yilia/_config.yml)
