### ISSUE TITLE
无法使用百度统计?

### ISSUE THREAD

**Issue by zhongjun96** [litten/hexo-theme-yilia#354]
貌似没有添加百度统计组件    ,从next过来的,有点不习惯;

**Comment by zhongjun96** [comment]
而且已经有"展开全文'的按钮了,能否把more>> 去除?  `尝试设置为false无法使用 
![baidushurufa_2016-12-9_8-48-3](https://cloud.githubusercontent.com/assets/18225577/21033630/a9fffb2c-bdec-11e6-834a-91af156bd6bb.png)

**Comment by sssvip** [comment]
@zhongjun96 百度统计可以自己加，我是加载footer那一部分的，你可以自己找一下！不懂可以问我

**Comment by zhongjun96** [comment]
@sssvip  OK,已经搞定了 , 不过添加其他社交信息 , 图标无法显示,查看了源码 ,  源码里面已经显示了qq的矢量图标 编号,但是 还是无法显示 , mian.js里也有QQ的图标 ;

**Comment by litten** [comment]
@zhongjun96 百度统计后面加

**Comment by zhongjun96** [comment]
@litten 而且已经有"展开全文'的按钮了,能否把more>> 去除? `尝试设置为false无法使用

**Comment by litten** [comment]
@zhongjun96 先说下设计思路：
“展开全文”的作用是让用户浏览完摘要后，有个按钮可以直接跳到文章页，而不是把视线移回标题，再点击；“more”紧跟在摘要后，会更连贯，也有更强的引导性。（总之每个人都希望用户点进文章页对不对…）所以我感觉不冲突。

之前的版本，我试过把more放在“展开全文”的位置，或者紧跟着摘要而不要“展开全文”。
这两种做法的文章跳转率，都没有现在的高，我是有做过数据流统计的。

但如果这是你的要求，也会满足。稍后版本，置为false后不显示好了。

**Comment by sssvip** [comment]
恩，我也准备回复他的，可以自己fork源码修改下，达到个性化@zhongjun96

**Comment by litten** [comment]
@zhongjun96 
“设置为false后不显示”已实现，请更新。

**Comment by sssvip** [comment]
@litten   (^_^)

**Comment by zhongjun96** [comment]
@litten 辛苦了，半夜更新
