### ISSUE TITLE
请问如果需要添加“知乎”、“豆瓣”等以外，没列出来的社交账户信息，如何显示图标？

### ISSUE THREAD

**Issue by oycfreedom** [litten/hexo-theme-yilia#355]
# SubNav
subnav:
  github: "#"
  weibo: "#"
  rss: "#"
  zhihu: "#"
  #douban: "#"
  #mail: "mailto:litten225@qq.com"
  #facebook: "#"
  #google: "#"
  #twitter: "#"
  #linkedin: "#"# SubNav
subnav:
  github: "#"
  weibo: "#"
  rss: "#"
  zhihu: "#"
  #douban: "#"
  #mail: "mailto:litten225@qq.com"
  #facebook: "#"
  #google: "#"
  #twitter: "#"
  #linkedin: "#"

**Comment by zhongjun96** [comment]
同问

**Comment by litten** [comment]
weixin和qq的确没添到css里
大家还需要什么图标？

**Comment by oycfreedom** [comment]
我想要 简书 罗娟洁 JJ LUO-------- 原始邮件 --------主题：Re: [litten/hexo-theme-yilia] 请问如果需要添加“知乎”、“豆瓣”等以外，没列出来的社交账户信息，如何显示图标？ (#355)发件人：litten 收件人：litten/hexo-theme-yilia 抄送：JJ Luo ,Author weixin和qq的确没添到css里
大家还需要什么图标？

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/litten/hexo-theme-yilia","title":"litten/hexo-theme-yilia","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/litten/hexo-theme-yilia"}},"updates":{"snippets":[{"icon":"PERSON","message":"@litten in #355: weixin和qq的确没添到css里\r\n大家还需要什么图标？"}],"action":{"name":"View Issue","url":"https://github.com/litten/hexo-theme-yilia/issues/355#issuecomment-266333394"}}}

**Comment by litten** [comment]
增加了“简书”“QQ”“微信”3个图标，请更新

**Comment by firedent** [comment]
稍微改一下就可以了，这个是我写的[文章](https://blog.zscself.com/posts/70677220/)

**Comment by zhongjun96** [comment]
@firedent 网站打不开

**Comment by firedent** [comment]
@zhongjun96 我检查了一下，没有问题呀……
