### ISSUE TITLE
新版点“文章”会报错

### ISSUE THREAD

**Issue by BlackHole1** [litten/hexo-theme-yilia#359]
```javascript
Unhandled rejection TypeError: /home/black-hole/Black-hole/github/blog/themes/yilia/layout/layout.ejs:9
    7|     </div>
    8|     <div class="mid-col" q-class="show:isShow,hide:isShow|isFalse">
 >> 9|       <%- partial('_partial/mobile-nav', null, {cache: !config.relative_link}) %>
    10|       <div id="wrapper" class="body-wrap">
    11|         <div class="menu-l">
    12|           <div class="canvas-wrap">

/home/black-hole/Black-hole/github/blog/themes/yilia/layout/_partial/mobile-nav.ejs:22
    20| 					<li><a href="<%- url_for(theme.menu[i]) %>"><%= i %></a></li>
    21| 		        <%}%>
 >> 22| 		        <% if (theme.smart_menu.innerArchive) { %>
    23| 		        	<li><a href="/archives/"><%= theme.smart_menu.innerArchive %></a></li>
    24| 		        <% } %>
    25| 				</ul>

Cannot read property 'innerArchive' of undefined

```

**Comment by BlackHole1** [comment]
再启动一次就好了，可能是配置文件没有生成的问题？

**Comment by yaomo** [comment]
同问， 重启程序也不行， hexo g  hexo s 都会报错

**Comment by ranying666** [comment]
搞了一上午终于找到原因了，因为在windows平台下编辑文件会包括特殊换行符导致只要修改了原配置文件都会出现这个问题。解决办法：在git-bash中编辑_config.yml等文件一点问题没有。
给我点赞~\(≧▽≦)/~

**Comment by BlackHole1** [comment]
奇怪的是，我使用的是ubuntu

**Comment by ranying666** [comment]
你前面说你再重启一次就好，那就不是这个问题，如果是编辑格式导致的问题话执行多次都不行。

**Comment by blaoke** [comment]
我也遇到了这个问题，通过将——config.yml中的friends: false注释，然后就不会出现这种问题了，你可以试试

**Comment by BlackHole1** [comment]
此issue是16年提出，目前已经改用hugo来做，故 close。

**Comment by blaoke** [comment]
你意思是hexo已经不用了吗？



---原始邮件---
发件人: "Black-Hole"<notifications@github.com&gt;
发送时间: 2020年3月5日(周四) 晚上9:48
收件人: "litten/hexo-theme-yilia"<hexo-theme-yilia@noreply.github.com&gt;;
抄送: "Comment"<comment@noreply.github.com&gt;;"blaoke"<420384576@qq.com&gt;;
主题: Re: [litten/hexo-theme-yilia] 新版点“文章”会报错 (#359)



此issue是16年提出，目前已经改用hugo来做，故 close。

**Comment by BlackHole1** [comment]
我个人的博客已经转移到hugo了，个人觉得 hugo 更加适合我
