### ISSUE TITLE
使用列表项的时候样式感觉不太好，不知道怎么改

### ISSUE THREAD

**Issue by ilovelll** [litten/hexo-theme-yilia#36]
代码

```
+ 电脑开机wifi模块需要手动fn启动，解决办法:
<!-- more-->
在/etc/modprobe.d/blacklist.conf 末尾添加 ``blacklist acer-wmi``

+ 电脑无法进行亮度调节,解决办法:
```

样式:
![2015-03-14 00 21 04](https://cloud.githubusercontent.com/assets/5793799/6642539/4bff2e00-c9e0-11e4-8873-392ab3f744c3.png)

内容不应该 紧跟小圆点后面么

**Comment by litten** [comment]
属于bug我稍后改下，请先用*号解决
```
* 电脑开机wifi模块需要手动fn启动，解决办法
```

**Comment by ilovelll** [comment]
使用*号 ，问题依旧

**Comment by litten** [comment]
你好，我这里用*和+都是正常的，bug重现不了。
能否提供一下你的blog地址，和所使用的浏览器，谢谢

**Comment by ilovelll** [comment]
blog：lihongn.tk
浏览器：ubuntu14.10 下Chrome41 和Firefox36均显示不正常

**Comment by litten** [comment]
md编译问题，你的列表里比我多了一层<p>标签导致。
已做一个兼容方案处理，请更新一下即可展示正常。
