### ISSUE TITLE
github图标不显示

### ISSUE THREAD

**Issue by Y00z** [litten/hexo-theme-yilia#361]
导航到个人微博知乎网站github等， github图标不显示。

**Comment by Y00z** [comment]
![default](https://cloud.githubusercontent.com/assets/18053148/21249494/68cce59c-c379-11e6-8ecd-92e74c97b828.png)

**Comment by Y00z** [comment]
![default](https://cloud.githubusercontent.com/assets/18053148/21249513/7e32e04e-c379-11e6-8dbe-0774228c1613.png)

**Comment by litten** [comment]
加得出来，这是浏览器缓存问题，通常这种资源是有过期时间的。
在我这里看是正常的，你也可以清空一下缓存，再刷新看看

**Comment by Y00z** [comment]
微软自带浏览器edge，换行符没解析。

![default](https://cloud.githubusercontent.com/assets/18053148/21250389/c276c936-c37f-11e6-98e7-855b6ecff215.png)

**Comment by litten** [comment]
已修复。
