### ISSUE TITLE
替换后重启hexo s浏览器显示如下信息

### ISSUE THREAD

**Issue by superchao8** [litten/hexo-theme-yilia#364]
<%- partial('_partial/head') %>
<%- partial('_partial/left-col', null, {cache: !config.relative_link}) %>
<%- partial('_partial/mobile-nav', null, {cache: !config.relative_link}) %>
<%- body %>
<%- partial('_partial/footer') %>
<%- partial('_partial/after-footer') %> <%- partial('_partial/tools') %> <%- partial('_partial/viewer') %>

**Comment by superchao8** [comment]
根目录执行：npm install 
惭愧，记得有跟新，可能不是在根目录。

**Comment by litten** [comment]
:+1:
