### ISSUE TITLE
有“展开全文”功能以后，怎么设置在哪里截断文章呢？

### ISSUE THREAD

**Issue by oycfreedom** [litten/hexo-theme-yilia#368]
看到issue里有人提到将加在要截断的文字后面。
但这样的话，文章里会同时显示>> more 和下面的 “展开全文”，比较累赘。
请问有其它的方式吗？

**Comment by litten** [comment]
注意看配置文件
```
# 文章太长，截断按钮文字
excerpt_link: more
# 文章卡片右下角常驻链接，不需要请设置为false
show_all_link: '展开全文'
```

不需要设置为false即可。

这里是设计的思路：[354](https://github.com/litten/hexo-theme-yilia/issues/354)
