### ISSUE TITLE
Cannot read property 'social' of undefined

### ISSUE THREAD

**Issue by huangashz** [litten/hexo-theme-yilia#375]
$ hexo g 报错
Unhandled rejection TypeError: /Users/HZ/newHexo/themes/yilia/layout/layout.ejs:9
    7|     </div>
    8|     <div class="mid-col" q-class="show:isShow,hide:isShow|isFalse">
 >> 9|       <%- partial('_partial/mobile-nav', null, {cache: !config.relative_link}) %>
    10|       <div id="wrapper" class="body-wrap">
    11|         <div class="menu-l">
    12|           <div class="canvas-wrap">

/Users/HZ/newHexo/themes/yilia/layout/_partial/mobile-nav.ejs:24
    22| 			<% var ulWidth = count > 2 ? '70%' : '50%' %>
    23|
 >> 24| 			<% if (theme.mobile.social) { %>
    25| 			<nav class="header-nav">
    26| 				<div class="social">
    27| 					<% for (var i in theme.subnav){ %>

大概报错信息都是找不到这个mobile？，萌新求指导 🤕

**Comment by litten** [comment]
不好意思，我的错
已修复，请更新

**Comment by huangashz** [comment]
👍👍👍👍👏👏👏




Sent from Mail Master
在2016年12月27日 14:42，litten 写道:

不好意思，我的错
已修复，请更新
