### ISSUE TITLE
被百度收录的讨论：百度站长工具主动提交之后迟迟不见收录

### ISSUE THREAD

**Issue by coderSkyChen** [litten/hexo-theme-yilia#379]
@litten 黎大大你好，了解到github屏蔽了百度蜘蛛。
我使用百度站长工具主动提交了个人page，已经3个星期了。
使用 `site:coderskychen.github.io` 查看，还是没有被收录。
想请问一下，您当时被百度收录大概用了多长时间？

**Comment by Latias94** [comment]
建个 coding pages，国内访问也快，还能被收录，在 dnspod 设置下线路类型就好了。

**Comment by coderSkyChen** [comment]
好的，谢谢大家:-)
