### ISSUE TITLE
分类、文章 缺陷&建议

### ISSUE THREAD

**Issue by flashblogs** [litten/hexo-theme-yilia#385]
1.主题中没有categories
2.归档archives 文章时间线可能比较好
3.文章article 内容页内右能 加上 锚定位 （定位到各个大小标题位置，免得文章太长，滚动太麻烦）
4.bug，如果文章内有categories分类，在文章的左下角，分类样式：article-category-link 不能正确显示（是白色），点击分类之后，效果和tags一样。。。

折腾了一天，总的来说，设计的不错，尝试着写了几篇博客，还是有很多细节可以优化，谢谢，加油！:-)

**Comment by litten** [comment]
1、访问 [categories](https://flashblogs.github.io/categories/%E7%94%9F%E6%B4%BB%E5%A8%B1%E4%B9%90/)
2、访问 [archives](https://flashblogs.github.io/archives/)
3、不加。不喜欢锚定位，sorry
4、bug，已修改，谢谢提醒

1和2有链接，如果你需要，自行在菜单加上就好
yilia的设计方向会尝试往单页面去走，所以默认没把这些展示出来

**Comment by flashblogs** [comment]
嗯，感谢回复！
1.可能我没有表述清楚，我的意思是，如果有categories，主题中没有呈现所有分类的页面，比如：生活（156）、技术博客（5）等这种汇总，并且目前主题里面，点击分类跟点击标签tags是一个效果，见图！
【分类、标签分开比较好，有时候写文章，分类太多，还是满重要】
![q1](https://cloud.githubusercontent.com/assets/24887590/21666462/c6e49694-d32c-11e6-8e49-edac9aa83723.jpg)

2. archives时间线，大概意思见图!
![q2](https://cloud.githubusercontent.com/assets/24887590/21666485/d4e4e19a-d32c-11e6-9e41-983504f6f736.jpg)

3.哈哈，任性；但是很多技术类博客、手册文档这种有很多步骤、有锚定位真心方便许多（可以设置文章内容是否呈现锚定位的开关？）

4.尝试单页完全赞同，官方推行引导用户使用单页的同时 若 也可以让用户根据实际需要摆弄一些其他功能也不错（比如分类、归档等）
谢谢
