### ISSUE TITLE
小白不太懂怎么加入多说

### ISSUE THREAD

**Issue by tangs92** [litten/hexo-theme-yilia#389]
配置文档里写
#是否开启多说评论，填写你在多说申请的项目名称 duoshuo: duoshuo-key

不太懂duoshuo-key哪里要填什么？密钥，域名，项目名？？

**Comment by vioRen** [comment]
![](http://i1.piimg.com/567571/0fc3bdd5988e4f55.png)

**Comment by tangs92** [comment]
谢谢，已经调出来了

**Comment by litten** [comment]
谢谢 @vioRen
