### ISSUE TITLE
代码框样式是否可配置？

### ISSUE THREAD

**Issue by maye1029** [litten/hexo-theme-yilia#39]
昨天更新了hexo3.0，顺便更新了yilia，发现代码框的样式变了，请问作者这个样式可以在配置中指定么？我个人比较喜欢原来的黑色背景样式。
![代码](http://maye.qiniudn.com/1.png)

**Comment by litten** [comment]
你好，样式变了是因为之前有个分支提交有问题。昨天已fix，请更新一下。
代码样式由于适配难度和成本偏大，暂时没有配置。

**Comment by wangyunok** [comment]
@litten  thanks
