### ISSUE TITLE
当前最新版本置顶存在问题

### ISSUE THREAD

**Issue by SuperDannyBoy** [litten/hexo-theme-yilia#390]
目前最新版出现这样子：
![32723063-4b70-4996-97b6-a22aeb5251a6](https://cloud.githubusercontent.com/assets/5237197/21666513/0589964c-d32d-11e6-94df-9b57bc88c458.png)
下面是以前旧版本：
![40713de8-9b08-45b4-aca9-879cac5f3c29](https://cloud.githubusercontent.com/assets/5237197/21666514/05beeab8-d32d-11e6-862d-f4fe3dc7d474.png)

**Comment by vioRen** [comment]
我也发现了...背景色没了，全选能看到字，`top: 1`好像也只显示便签不置顶...

**Comment by litten** [comment]
已修复，不好意思
优化标签展示时，又把这个东西忘记了…

**Comment by SuperDannyBoy** [comment]
@litten 感谢，刚刚更新新版本已经fix了。现在我关闭和这个issue。
@vioRen 新版本已经fix。

**Comment by litten** [comment]
@SuperDannyBoy 
另外，如果你置顶时不想显示文章日期，可以在markdown文件前面加上：

```
noDate: true
```

**Comment by stevenjoezhang** [comment]
Hexo 已实现文章置顶参数： hexojs/hexo-generator-index#51
