### ISSUE TITLE
关于在本地一切显示正常 hexo d也可以部署成功 但是打开github page一直是404页面

### ISSUE THREAD

**Issue by shacai** [litten/hexo-theme-yilia#393]
不知道为什么打开github page一直404 之前有成功打开过 不知道哪里出了错 我的仓库配置哪里不对吗

**Comment by shacai** [comment]
一直收到一封github邮件 

The page build completed successfully, but returned the following warning:

You are attempting to use a Jekyll theme, "yilia", which is not supported by GitHub Pages. Please visit https://pages.github.com/themes/ for a list of supported themes. If you are using the "theme" configuration variable for something other than a Jekyll theme, we recommend you rename this variable throughout your site. For more information, see https://help.github.com/articles/adding-a-jekyll-theme-to-your-github-pages-site/.

For information on troubleshooting Jekyll see:

  https://help.github.com/articles/troubleshooting-jekyll-builds

If you have any questions you can contact us by replying to this email.

这是hexo主题啊 怎么一直说不支持 头疼

**Comment by litten** [comment]
你是执行```hexo d```命令推送的？
还是自己去敲```git commit```？

**Comment by shacai** [comment]
执行hexo d命令

**Comment by shacai** [comment]
抱歉作者大大 睡了一觉没有马上回复

**Comment by litten** [comment]
感觉是配置问题
请在根目录的（注意不是yilia目录）的_config.yml里找一下deploy的配置
贴出来看看

**Comment by shacai** [comment]
deploy:
     type: git
     repository: git@github.com:shacai/shacai.github.io.git
     branch: master

**Comment by shacai** [comment]
谢谢作者大大 解决了

**Comment by M-suny** [comment]
每次hexo d 之后，都需要去github里面重新设置一下 域名 这个问题有人遇见吗？

**Comment by seawaylee** [comment]
@shacai 请问您是怎么解决的？我与遇到了同样的问题。

**Comment by ldoublem** [comment]
同问 你是怎么解决的？

**Comment by StoneRen** [comment]
@M-suny 重新设置域名的问题
 在source文件夹下创建一个`CNAME`文件,里面放上你的域名. 具体可以看我的`CNAME`代码 https://github.com/StoneRen/stoneren.github.io/blob/master/CNAME

**Comment by Etoile984816138** [comment]
遇到了同样的问题…请问如何解决的？

**Comment by StoneRen** [comment]
@Etoile984816138 你设置了 CNAME?
如果设置了,看我上面的回答
