### ISSUE TITLE
请问`hexo generate`生成静态文件后，.js和.css直接生成在public文件下了

### ISSUE THREAD

**Issue by barondu** [litten/hexo-theme-yilia#395]
1. 请问`hexo generate`生成静态文件后，.js和.css直接生成在public文件下了。怎么样可以生成在对应的css和js文件夹内，public文件夹太乱了。
2.  @小白，比如自己修改了source-src内的css，需要npm run dev这点没看懂，是要在哪个根目录下运行@litten

**Comment by barondu** [comment]
3. `top: true`或者top: 100只显示标签不能置顶，不知道为什么，已经更新到最新版本

**Comment by litten** [comment]
1、这是hexo本身的设计，无法改变
但作为使用者，是不需要直接操作public文件夹的
反而这样的设计可以缩短静态资源路径，即使你觉得乱，但只要源码目录不乱，就不是大问题

2、在``yilia``文件夹里

3、hexo现在并没有“置顶”功能，但你可以通过设定实现
在文章的markdown文件头部，写一个很大的date（因为hexo是通过时间排序），同时设定noData: true（可以不展示时间）

比如是：
```
date: 2017-12-31 23:59
noData: true
top: true
```

**Comment by barondu** [comment]
了解了！谢了
