### ISSUE TITLE
yilia支持markdown的表格语法吗？

### ISSUE THREAD

**Issue by Stillwater12** [litten/hexo-theme-yilia#396]
表：XMLHttpRequest的readyState值
    | 常量   | 值 | 含义 |
    | :----: | :----: | :----: |
    | UNSENT | 0 | open()尚未调用 |
    | OPENED | 1 | open()已经调用 |
    | HEADERS_RECEIVED | 2 |接收到头信息 |
    | LOADING | 3 | 接收到响应主体 |
    | DONE | 4 | 响应完成 |

这个是我写的一个markdown，结果没有显示出表格的效果。
我想问下是yilia不支持，还是我哪里写错了。

**Comment by litten** [comment]
支持的。
之所以你的没能显示，是因为表格前后需要换行

**Comment by Stillwater12** [comment]
表：XMLHttpRequest的readyState值

|常量|值|含义|
|:----:|:----:|:----:|
|UNSENT|0|open()尚未调用|
|OPENED|1|open()已经调用|
|HEADERS_RECEIVED|2|接收到头信息|
|LOADING|3|接收到响应主体|
|DONE|4|响应完成|

表格前后各空一行
问题已经解决，谢谢litten
