### ISSUE TITLE
多级列表只显示为一级列表？

### ISSUE THREAD

**Issue by qizhihere** [litten/hexo-theme-yilia#40]
hi litten，我使用了hexo-render-pandoc，多级列表如下：

![多级列表](http://7sbq2s.com1.z0.glb.clouddn.com/img_links/github/multi-level-list.png)

而生成的html只有一级列表：

![显示效果](http://7sbq2s.com1.z0.glb.clouddn.com/img_links/github/bug-preview.png)

试过直接用pandoc生成html，是正常的。已经更新了主题，还是一样。请问这是什么原因呢:-*?

**Comment by litten** [comment]
目测是bug，后面我fix下

**Comment by qizhihere** [comment]
好的

**Comment by LouisShark** [comment]
请问这个问题修复了吗 我还是这样
