### ISSUE TITLE
本地显示没问题，deploy到github，出现了网页格式错误。

### ISSUE THREAD

**Issue by Fuxiao7** [litten/hexo-theme-yilia#400]
![](http://p1.bqimg.com/567571/7be7c755322acf0d.png)
这是本地的效果↑

![](http://p1.bqimg.com/567571/4d5f77fc6942faca.png)
传到github之后，变成了这个样子↑

求助下诸位大大，这大概是什么情况，有木有解决方法呀~

**Comment by litten** [comment]
检查下根目录的_config.yml，里面的root字段？
讲道理写/就可以了：
```
root: /
```

**Comment by Fuxiao7** [comment]
果然改了之后就可以了。。感谢大大~非常喜欢您的主题~

**Comment by skykywind** [comment]
root没问题，如果我没买域名的话，url怎么写？ 我也是放在github pages
