### ISSUE TITLE
展示全文功能有问题

### ISSUE THREAD

**Issue by ganchengyuan1990** [litten/hexo-theme-yilia#401]
你好，我目前遇到的情况是首页博文不管有多长，都是完整显示的，那么这样一来展示全文功能就没有意义了，请问应该如何设置呢？

**Comment by vioRen** [comment]
问之前可以看一下历史issue
![issue#399](https://github.com/litten/hexo-theme-yilia/issues/399)

**Comment by wenboo** [comment]
@ganchengyuan1990  

在你 markdown 文章中需要截断的地方添加：



即可。
