### ISSUE TITLE
怎么使网站上的文章能够连到我设定的分类目录里面呢

### ISSUE THREAD

**Issue by iKarenZhao** [litten/hexo-theme-yilia#406]
![1](https://cloud.githubusercontent.com/assets/25225269/22182803/2a46dbba-e0e9-11e6-8439-9644637adc05.jpg)
![2](https://cloud.githubusercontent.com/assets/25225269/22182804/2b1951ee-e0e9-11e6-91bf-5084c8584f0c.jpg)

如图所示，我在markdown文章里写的时候，tags是写的：tags: random thoughts
在yilia的config文件里是：  Random Thoughts: /tags/random thoughts/

但是貌似没有用，我点目录的random thoughts 什么都出不来，求解？

**我自己尝试把“random thoughts”中间的空格删掉，就可以了！所以是tags 后面不能有空格吗？还是说如果是词组要用“”？**

谢谢

**Comment by litten** [comment]
你说得对，因为url是不能有空格的，所以有一种东西叫encode
如果你非要在tags里加空格，请复制括号里的这个迷之空格符：（　）

**Comment by iKarenZhao** [comment]
谢谢，的确第一次听说 encode。。。我还是用这个迷之空格符吧
