### ISSUE TITLE
每天一个issue的节奏！ 求问怎么解决百度无法收录的问题？

### ISSUE THREAD

**Issue by iKarenZhao** [litten/hexo-theme-yilia#408]
百度无法收录github上的博文，所以有什么解决方案么？
我在知乎搜了一个答案，http://hui-wang.info/2016/10/23/Hexo%E6%8F%92%E4%BB%B6%E4%B9%8B%E7%99%BE%E5%BA%A6%E4%B8%BB%E5%8A%A8%E6%8F%90%E4%BA%A4%E9%93%BE%E6%8E%A5/

但是我不明白【 请把您的Hexo博客源文件托管到私有仓库里。】这是什么意思？
如何把hexo托管到私有仓库啊。。私有仓库是不是收费的啊？

求解。。。请尽量详细，因为我完全不懂程序。。github出现在我的世界里才不过一周不到。

**Comment by litten** [comment]
来龙去脉大概是：
百度爬取github太频繁了，甚至引起了github的服务不稳定；
一年多前gitHub直接把百度屏蔽了，也就是说，所有托管到gitHub pages上的静态博客都是无法被百度自动收录到。

---------------

我知道的办法是：
方法一：自己买服务器和域名（比如我），缺点是成本高
方法二：把博客同时部署到国内git平台（比如[coding](https://coding.net/)）和github，缺点是管理比较麻烦，而且还是要买域名。供[参考](http://guochenglai.com/2016/09/26/baidu-crow-github-page/)

---------------

至于你搜到的答案，百度主动提交，我首先没试验过，不敢下结论；
但讲道理github屏蔽了baidu，即使主动提交url也没办法呀
try it & good luck.

但github私有仓库是收费的（而且挺贵），博主建议托管到私有库，是出于安全考虑
因为源码里会带上提交到百度的token（相当于你网站的身份证）

首先要明确，hexo的原理是：把源码目录，编译出public文件夹当成博客内容
再将public提交到github，建立page。

但只要你不把[源码目录](https://github.com/litten/BlogBackup)提交到github，只是提交[博客内容](https://github.com/litten/litten.github.com)，就不需要考虑这问题。

**Comment by iKarenZhao** [comment]
谢谢！我已通过同时部署在coding上 解决了这个问题。话说 我就是不想买虚拟主机才部署在github上的。域名倒是买了 😄。
