### ISSUE TITLE
关于多说的data-thread-key

### ISSUE THREAD

**Issue by vioren** [litten/hexo-theme-yilia#410]
yilia的多说配置文件位于`/layout/_partial/post/duoshuo.ejs`，其中
```
data-thread-key="<%=key%>"
data-title="<%=title%>"
data-url="<%=url%>"
```
这里的key,title,url是在哪里定义的呢？查阅Hexo的文档说明，一般用page.path，page.title，page.permalink，这些页面变量来定义，yilia存在的问题就是如果我new page而不是new post，就是说生成的文章不在_post文件夹下，例如我主页的留言板页面，那么它生成页面的data-thread-key就是undefined的，说明%=key%是不存在的，那么如果多个页面的话，多说评论是无法定位到相关的页面的。是否有解决方案来修补这个问题呢？还是直接使用Hexo的变量page.path，page.title，page.permalink来定义呢？谢谢！

**Comment by litten** [comment]
谢谢提醒，这个我的锅，没考虑到
近期修复吧

**Comment by vioRen** [comment]
好的，没能力pull request，还是需要大家一起测试来提出issue帮助yilia，共建开源社区！
