### ISSUE TITLE
想请问一下首页增加ins怎么设置

### ISSUE THREAD

**Issue by laclys** [litten/hexo-theme-yilia#413]
就是您博客里的相册（把ins关联）

**Comment by litten** [comment]
由于ins被墙，以及它自身的api调整，现在没法通过配置去实现相册
我自己的实现是一个后台爬虫，把相片和数据爬取到服务器里

**Comment by laclys** [comment]
谢谢您了。

**Comment by litten** [comment]
一直想开源这个爬虫，但因为懒……
没解决好，不敢乘谢

return '谢谢您了';

**Comment by laclys** [comment]
很期待这个开源的爬虫！！！
