### ISSUE TITLE
点击所有文章提示模块缺失

### ISSUE THREAD

**Issue by zmdstr** [litten/hexo-theme-yilia#419]
![image](https://cloud.githubusercontent.com/assets/22245597/22854728/d2ded040-f0af-11e6-8688-a075c428c953.png)
按提示操作后
![image](https://cloud.githubusercontent.com/assets/22245597/22854743/0db75bba-f0b0-11e6-9d8d-3df972fe393c.png)
请问这个如何解决啊？

**Comment by maoshunyu** [comment]
同问@litten

**Comment by litten** [comment]
这个错误没遇到过，但估计是格式问题。
请检查下jsonContent字段前后有没有空格之类的，总之yaml要使用严格的缩进。

**Comment by taodaren** [comment]
这个问题之前我也纠结了好几天，后来发现是nodejs版本的问题，把nodejs升级到最新版本即可

**Comment by luojunquan** [comment]
我也遇到这个问题

**Comment by PiscesKnight** [comment]
@taodaren 我升级到6.10了还是不行。。

**Comment by JuniorTour** [comment]
我也遇到了同样的问题，根据提示信息：“ bad indentation of a mapping entry at line 80, column 2:...”。
我觉得是缩进的问题，后来删除了“ jsonContent:”这一句前的一个空格后，问题就解决了。

推荐你们试试。

**Comment by hardmanhong** [comment]
我也遇到这个问题，升级了node.js最新版就解决啦

**Comment by zmdstr** [comment]
@JuniorTour 谢谢，我的问题也解决了。

**Comment by notdp** [comment]
点睛之笔，”请检查下jsonContent字段前后有没有空格之类的，总之yaml要使用严格的缩进。“缩进跟错误提示一样就可以了，谢谢
