### ISSUE TITLE
求问友链和关于我不显示

### ISSUE THREAD

**Issue by maoshunyu** [litten/hexo-theme-yilia#420]
如图
![default](https://cloud.githubusercontent.com/assets/10005716/22861440/dbd50cec-f153-11e6-888b-f5c59f7855ed.PNG)

**Comment by LancelotHolmes** [comment]
我的`关于我`如果在前面尝试添加空格符比如`&emsp;`的话也都不显示，去掉就没问题，不知道你是什么原因，又是怎么解决的，我是后来去掉了，并且隔一句用`<br>`换个行
