### ISSUE TITLE
不知有没有考虑引入音乐呢？

### ISSUE THREAD

**Issue by guokewind** [litten/hexo-theme-yilia#422]

**Comment by guokewind** [comment]
cplayer不错。

**Comment by litten** [comment]
不考虑，抱歉

**Comment by YanCeyMichael** [comment]
真要是很想要音乐的话,你可以这样做,我博客里有一个小技巧操作:https://yanceymichael.github.io
不过加了音乐播放器之后,我总觉得很难受.
也许Litten考虑的是对的.
也许过一个礼拜就把播放器移除掉了.

**Comment by guokewind** [comment]
@YanCeyMichael  我们做了一样的事情呢。 guokewind.github.io
