### ISSUE TITLE
关于主页文章显示全部内容的问题

### ISSUE THREAD

**Issue by PilgrimErick** [litten/hexo-theme-yilia#428]
我的博客主页文章都是显示全部的内容，乍一看铺满全屏，有点冗长（见 [我的博客](http://PilgrimErick.github.io/)）。
我看你的博客主页文章可以只显示一部分，然后用more>>按钮截断，请问怎么做到的？谢谢!

**Comment by PilgrimErick** [comment]
# Content

# 文章太长，截断按钮文字
excerpt_link: more
# 文章卡片右下角常驻链接，不需要请设置为false
show_all_link: '展开全文'
# 数学公式
mathjax: false
# 是否在新窗口打开链接
open_in_new: false

之前以为是配置excerpt_link，结果没有效果

**Comment by gtzh110** [comment]
在文章中想要截断的地方输入 即可显示部分内容。如果要把右下角的展开全文去掉，可以设置show_all_link: false

**Comment by PilgrimErick** [comment]
@gtzh110 谢谢！问题已解决！

**Comment by tidus5** [comment]
@gtzh110   哥，感谢你的回答，但答案准确点啊。 你想想昨晚凌晨1点多，我复制你的答案给我博客30多篇都加上标记，然后发现折叠无效。 再去另一个issue 里找到正确的    是什么样的心情啊。（不过还好后面用 npp 的批量文件替换了）

**Comment by BestDingSheng** [comment]
< !--more-- > 加了没用啊 请问怎么解决的

**Comment by PilgrimErick** [comment]
@BestDingSheng `<!-- more --> `   上面多了空格

**Comment by BestDingSheng** [comment]
@tidus5  怎么解决的

**Comment by BestDingSheng** [comment]
@PilgrimErick  好的 我试试 谢谢

**Comment by BestDingSheng** [comment]
@PilgrimErick  谢谢 解决了

**Comment by BestDingSheng** [comment]
@PilgrimErick  你的.me 的域名须要买吗 能加个QQ交流交流吗

**Comment by PilgrimErick** [comment]
@BestDingSheng  阿里云买的，首年的域名都很便宜

**Comment by tidus5** [comment]
@PilgrimErick  有个问题，如果我A域名第一次买，然后过期了买B域名，然后又过期了。再来买A域名，这时候还能有首年优惠么？

**Comment by losymear** [comment]
如果使用flowchart/mermaid插件的话使用 首页会无法显示图表
