### ISSUE TITLE
怎么自己加js

### ISSUE THREAD

**Issue by Sallylearning** [litten/hexo-theme-yilia#444]
载网上看到一个比较好的效果：在离开和进入页面时改变页面的标题
知道怎么js代码，但是不知道怎么加到自己的博客里面

**Comment by litten** [comment]
如果人人都看[wiki](https://github.com/litten/hexo-theme-yilia/wiki/Yilia源码目录结构及构建须知)，世界将变成美好的人间…

**Comment by Sallylearning** [comment]
thx，我去尝试一下
