### ISSUE TITLE
头像src=“null”

### ISSUE THREAD

**Issue by zgfang1993** [litten/hexo-theme-yilia#445]
头像显示不出来，试了前面的方法，都没有成功。
看之前都是地址前面多了一个null，而我的直接为null了。
![image](https://cloud.githubusercontent.com/assets/14739234/24071569/2ed429f6-0c10-11e7-9ff9-d5d999f9f968.png)

好像<%=theme.avatar%>这句话的avatar没有获取到

我的配置：
![image](https://cloud.githubusercontent.com/assets/14739234/24071576/5326d128-0c10-11e7-9a7c-741c19839f13.png)
![image](https://cloud.githubusercontent.com/assets/14739234/24071579/682af2c0-0c10-11e7-84fa-43a54384e267.png)

**Comment by litten** [comment]
怎么解决的？分享下？

**Comment by zgfang1993** [comment]
大大，这个完全是自己粗心啦，<%=theme.avatar%>avatar没有获取到，肯定是配置文件没有配上。因为我配置到根目录的配置文件了，真是哭笑不得。可能也是第一次配心急容易犯的错，没仔细看文档。大家不要犯我这种错误啦 /(ㄒoㄒ)/~~
