### ISSUE TITLE
怎么启动

### ISSUE THREAD

**Issue by holidaying** [litten/hexo-theme-yilia#447]
怎么启动起来啊？都么有启动服务器的代码

**Comment by litten** [comment]
看了一下你的blog，已经自己解决了，好样的。

**Comment by holidaying** [comment]
畅言需要备案，有没有共享的备案号啊

**Comment by holidaying** [comment]
你的blog写的很细，仔细研究后就可以搞定了。同时还有个问题请教，畅言需要备案，有没有共享的备案号。望不吝赐教

**Comment by litten** [comment]
没有共享备案号，关于评论，我打算用网易云跟帖，但想再观察一段时间
