### ISSUE TITLE
文章置顶只显示“置顶”标签，没有真正置顶

### ISSUE THREAD

**Issue by lqsheng** [litten/hexo-theme-yilia#454]
如图，在文章里将top设为了true，文章标签处多了一个置顶标签，但并没有真正置顶~是我哪里还漏了配置吗？
![default](https://cloud.githubusercontent.com/assets/25112740/24329694/8cd43254-1240-11e7-9486-571d0f1b47e8.png)
![default](https://cloud.githubusercontent.com/assets/25112740/24329697/932b2892-1240-11e7-8e39-310f7b5215a6.png)

**Comment by lqsheng** [comment]
找到解决方案了，原来还要改一处JS

**Comment by stevenjoezhang** [comment]
Hexo 已实现文章置顶参数： hexojs/hexo-generator-index#51
