### ISSUE TITLE
近期提交的貌似生成的网页布局全乱了

### ISSUE THREAD

**Issue by SuperDannyBoy** [litten/hexo-theme-yilia#459]
更新了之后生成的网页布局貌似都乱了

**Comment by litten** [comment]
有截图吗？
我这边没问题呀…

**Comment by SuperDannyBoy** [comment]
我是生成localhost预览的，结果变成下面这样子
![ac080f0b-e53d-4a07-a24f-caa906414ea6](https://cloud.githubusercontent.com/assets/5237197/24449433/d552e2bc-14a9-11e7-8fce-fd6804fcc186.jpeg)

**Comment by litten** [comment]
我这正常，请自行对比下 https://github.com/litten/hexo-theme-yilia/tree/master/source
文件跟本地的是否一样
