### ISSUE TITLE
全局图片预览问题

### ISSUE THREAD

**Issue by RuMengRen** [litten/hexo-theme-yilia#461]
如果我给img标签设定一个宽高（类似缩略图），点击打开预览就变成缩略图搬大小....
总而言之，就是怎么让预览图不继承缩略图的宽高，等比例缩小的img，点开图片也是同样大小

**Comment by RuMengRen** [comment]
好吧，自己解决了，img添加data-size="800|800"  //像素的宽高
main.js中修改
`if (!document.querySelector(".left-col.show")) {
	var n = [],wh;
	t.forEach(function(e, t) {
		var o = (e.getAttribute("data-idx", t), e.getAttribute("data-target") || e.getAttribute("src")),
			r = e.getAttribute("alt");
		wh = (e.getAttribute("data-size")).split("|");
		if (wh == "") {
			wh[0] = e.width;
			wh[1] = e.height
		};
		n.push({
			src: o,
			w: wh[0],
			h: wh[1],
			title: r
		})
	});`

**Comment by litten** [comment]
好吧…这个我没考虑到。
谢谢提供信息和思路。
