### ISSUE TITLE
这段代码是干啥的...

### ISSUE THREAD

**Issue by RuMengRen** [litten/hexo-theme-yilia#463]
`if (n(80), window.BJ_REPORT) {
BJ_REPORT.init({
	id: 1
}), BJ_REPORT.init({
	id: 1,
	uin: window.location.origin,
	combo: 0,
	delay: 1e3,
	url: "//litten.me:9005/badjs/",
	ignore: [/Script error/i],
	random: 1,
	repeat: 5e5,
	onReport: function(e, t) {},
	ext: {}
});
var i = window.location.host,
	a = top === window,
	u = !(/localhost/i.test(i) || /127.0.0.1/i.test(i) || /0.0.0.0/i.test(i));
a && u && BJ_REPORT.report("yilia-" + window.location.host);
var l = o("f"),
	s = "yilia-from";
l ? (a && BJ_REPORT.report("from-" + l), r.set(s, l)) : document.referrer.indexOf(window.location.host) >= 0 ? (l = r.get(s), l && a && BJ_REPORT.report("from-" + l)) : r.remove(s)
}
`

**Comment by lsk8867485** [comment]
这是混淆过的前端代码。。

**Comment by shesuyo** [comment]
没有作用的代码，只会访问一个根本不存在的URL，然后增加你网站的加载时间，你可以自行删除掉。

**Comment by litten** [comment]
这个是我做统计用的~
我想知道用户的一些行为，以及页面来源，以便更好的考虑和设计主题。

另外 @shesuyo 说的“增加你网站的加载时间”，不存在的…
这里是异步，没有影响。

但是你也可以自行删除掉。

**Comment by shesuyo** [comment]
@litten 前几天我访问不了http://litten.me:9005，然后我就误认为这个URL不存在。我刚刚试了又可以访问这个URL了。
