### ISSUE TITLE
用畅言替换多说傻瓜式教程。

### ISSUE THREAD

**Issue by lsk8867485** [litten/hexo-theme-yilia#464]
最近由于多说要关闭， 我自己用畅言替换了多说，不用重新混淆前段代码，不懂代码也可以看懂。博客教程如下： [教程地址](http://www.luck666.cn/2017/03/22/hexo-yilia-changyan/)

**Comment by aimaodeyuer** [comment]
@lsk8867485 我申请的畅言，用的其他网站的备案号，你的博客里面怎么开启评论具体的也没写全啊。

**Comment by lsk8867485** [comment]
@aimaodeyuer 开启评论跟以前的duoshuo一样呀，在yilia的配置文件那里把改成 `duoshuo: true`就可以啦。

**Comment by aimaodeyuer** [comment]
@lsk8867485 能不能把你改的代码贴一下，两个key记得打码哦.duoshuo:true我已经改了。不知道为什么没生效。

**Comment by lsk8867485** [comment]
@aimaodeyuer 哎呀，Sorry，说错了，因为之前是填写duoshuo-Key的，这里你填写畅言给你的key就好，但其实没用上，随便添一组字符串就好。duoshuo: cysJKdsdF

**Comment by zhisheng17** [comment]
@lsk8867485  你好，我是新下载的，发现你说的那个文件duoshuo.ejs中不存在  sid，不知道在哪里修改呢？还请赐教

**Comment by holidaying** [comment]
能否给个备案号

**Comment by litten** [comment]
多谢提供教程
现也已支持
需要的朋友请更新下
再次多谢 @lsk8867485

**Comment by BestDingSheng** [comment]
@litten  没办法备案怎么办

**Comment by BestDingSheng** [comment]
@litten  github服务器 没发备案
