### ISSUE TITLE
root 配置了 /blog/  点击所有文章还是根目录 

### ISSUE THREAD

**Issue by BestDingSheng** [litten/hexo-theme-yilia#465]
![image](https://cloud.githubusercontent.com/assets/13111768/24539105/84a41d32-161f-11e7-9111-1734f6000e2e.png)
我要的效果是这样
![image](https://cloud.githubusercontent.com/assets/13111768/24539134/a16c9390-161f-11e7-8666-3c7d3691b7fb.png)

配置的有问题吗
![image](https://cloud.githubusercontent.com/assets/13111768/24539172/d0b30350-161f-11e7-9e8d-94424bfcd3fa.png)

**Comment by BestDingSheng** [comment]
还有点击头像的链接在哪里配置

**Comment by litten** [comment]
注释含义没写清楚，这个是hexo的锅

应该是：
```
url: https://bestdingsheng.github.io/
root: /myBlog/
```

不过我不建议url里面用驼峰式命名。

头像设置在 yilia/_config.yml 里面的 avatar 字段

**Comment by cexoso** [comment]
我也遇到了类似的问题。
我按这种方式写了
> url: https://bestdingsheng.github.io/
root: /myBlog/

但是还是没有解决，生成的文章链接是没有包含root的

**Comment by wuhou123** [comment]
解决了没，看了很多修改的，还是不成功
