### ISSUE TITLE
照着实现了相册页面，有需要的朋友可以参考

### ISSUE THREAD

**Issue by elsonwx** [litten/hexo-theme-yilia#466]
没什么创新，样式也没处理好，勉强可以用哈哈
https://github.com/elsonwx/photoswipe_album

**Comment by RuMengRen** [comment]
json文件能在提交的时候生成么，我也弄了一个，但是是通过一个程序生成的，不怎么方便

**Comment by elsonwx** [comment]
你可以写一个脚本，每次提交前运行脚本从图片目录生成json文件。

**Comment by litten** [comment]
手动点赞
