### ISSUE TITLE
用网易云跟帖做评论系统，为什么主页下出现了四个评论框？

### ISSUE THREAD

**Issue by 18292843691** [litten/hexo-theme-yilia#467]
用网易云跟帖做评论系统，为什么主页下出现了四个评论框？

**Comment by wangwangteam** [comment]
网易云跟帖怎么安装啊？求教程

**Comment by 18292843691** [comment]
@wangwangteam  恩，你用的是yilia吗？因为四个评论框我不知道怎么解决，我就改用next了。
yilia:网易云跟帖-->后台管理-->获取代码(web代码)-->copy-->打开hexo>theme>yilia>layout>_partial>article.ejs  --> 代码复制到</article>后面，你试试吧，因为我这样安装完主页出了BUG。
next:官方直接配置好了，你把你的跟帖ID输进去就好了。

**Comment by XElengo** [comment]
我用的是网易云跟帖，欢迎讨论，我的博客：xelengo.me

**Comment by litten** [comment]
现在yilia已支持网易云跟帖，请更新一下
至于为什么出现四个… 就让它成为未解之谜吧…
