### ISSUE TITLE
添加支持本页面锚点跳转功能

### ISSUE THREAD

**Issue by PilgrimErick** [litten/hexo-theme-yilia#468]
目前在文章中用html标签 `<a href="#jump" target="_self">跳转到锚点处</a>`  来设置锚点，`target="_self"` 会被js重置为 `target="_blank"`，希望增加一个判断：如果 `a标签为锚点标签` 或者 `主动设置了 _self 这个值` 的情况下，不要重置这个属性。

希望作者考虑并修改下，谢谢！

**Comment by litten** [comment]
好的，谢谢建议，假期争取改好

**Comment by litten** [comment]
已解决，请更新
