### ISSUE TITLE
slider.js插件有在哪里用到么

### ISSUE THREAD

**Issue by RuMengRen** [litten/hexo-theme-yilia#469]
感觉每次都加载了，但不确定哪里有用到

**Comment by litten** [comment]
点击“所有文章”“友链”“关于我”… 这些时，滑动的那部分就是。

只所以分拆成main.js和slider.js，是基于性能考虑
页面一加载会加载核心的main.js
同时异步请求slider.js，因为这部分的功能懒加载更合理
