### ISSUE TITLE
添加instagram相册，替换id后刷新还是你的instagram内容。。。

### ISSUE THREAD

**Issue by ilovelll** [litten/hexo-theme-yilia#47]
已经替换过data-client-id和data-user-id

**Comment by ilovelll** [comment]
还有个不算issue，新版内容加载时的动画感觉太过用力可以稍微淡点

**Comment by guimeisang** [comment]
怎么添加相册

**Comment by litten** [comment]
@guimeisang 

那是两年前，用的v1版本api，现在instagram更新了策略
在一系列复杂审核流程之前，没办法拉到所有照片信息…

所以我也没法通过配置的方法开放给大家
一个悲伤的故事

我的实现暂时是一个node爬虫，但它还有点小问题没有开源

但除去爬虫的前端逻辑，你可以参考下[博客备份]的实现(https://github.com/litten/BlogBackup/tree/master/source/photos)
