### ISSUE TITLE
Markdown文件的渲染问题

### ISSUE THREAD

**Issue by eshibudaoweng** [litten/hexo-theme-yilia#478]
markdwn的渲染不支持有序列表，部署到页面上之后就变成无序列表了。
<img width="372" alt="2017-04-06 10 27 52" src="https://cloud.githubusercontent.com/assets/15830060/24759604/95a09a4a-1b18-11e7-84de-54d0fd81e8ea.png">

**Comment by Seancss** [comment]
我的也是这样，不知道为什么。估计作何不更新了吧，看起来好难受

**Comment by eshibudaoweng** [comment]
@Seancss 作者不更新的话那就只能自己折腾了……另外，markdown脚注渲染也是有问题的。
如果自己折腾好了再来上传进展。

**Comment by Seancss** [comment]
主要是自己也不会鼓捣啊，那么多大神用，都没在意这个吗？

**Comment by litten** [comment]
不好意思，改晚了
之前是好的，应该是2个月前有次样式调整不小心改错了。
请更新一下。

**Comment by eshibudaoweng** [comment]
已更新，感谢作者。
