### ISSUE TITLE
没有到达`/archives/index.html`的链接

### ISSUE THREAD

**Issue by firedent** [litten/hexo-theme-yilia#480]
1. `/archives/index.html`中的`<div class="archive-year-wrap">`里面的链接无法点击。
2. 没有到达`/archives/index.html`、`/archives/:year/index.html`的链接。
3. 没有到达`/tags/*`的链接。查看某一特定tag可以通过左侧的“所有文章”查看，所以我猜这是作者有意而为之。

**Comment by litten** [comment]
archives 问题修复了，请更新；
tags确实是这么设计的，除非您有特别强烈的tags SEO需求。

**Comment by firedent** [comment]
@litten 辛苦了，谢谢及时修复。但是，第二个问题我还是有点不明白，您的意思是说“没有到达/archives/index.html、/archives/: year/index.html的链接，也是和第三点一样的原因”？

**Comment by litten** [comment]
不是这意思~
1. 无法点击是z-index设置有问题，其实里面是有链接的；
2. 这个看你自己的需要，自行配置menu即可：

```
menu:
  归档: /archives/index.html
  2017年度: /archives/2017/index.html
```

**Comment by firedent** [comment]
@litten 懂了懂了，我自己又加了一个类似于friends的菜单。
配置menu:
```
smart_menu：
  archives: '归档'
archives:
  2017年: /archives/2017/
  2016年: /archives/2016/
  2015年: /archives/2015/
  2014年: /archives/2014/
```
更改`tool.ejs`：[代码](https://github.com/firedent/hexo-theme-yilia-modify/commit/880bea6c603b431513bded0bd134ce82d37db835)
如果智能菜单增加一个多级菜单的功能就好了，这样既可以放友链也可以放归档，也许别人还会发现新用途。
