### ISSUE TITLE
Github pages + Hexo 博客 yilia 主题使用畅言评论系统

### ISSUE THREAD

**Issue by zhisheng17** [litten/hexo-theme-yilia#482]
写了个博客记录下，地址：[yilia 主题使用畅言评论系统](http://www.54tianzhisheng.cn/2017/04/13/Hexo-yilia-changyan/)，需要可以参考进行替换原来的多说评论系统。

**Comment by litten** [comment]
谢谢提供记录，yilia现也已支持
