### ISSUE TITLE
请问怎么在侧栏加网易云音乐播放器

### ISSUE THREAD

**Issue by mengxin-FE** [litten/hexo-theme-yilia#483]
请问怎么在侧栏加网易云音乐播放器

**Comment by litten** [comment]
这个需求太具体了，可能不是每个人都想要的，所以也不打算实现，望谅解。
但您可以自己实现，yilia开发请参考wiki：[《Yilia源码目录结构及构建须知》](https://github.com/litten/hexo-theme-yilia/wiki/Yilia%E6%BA%90%E7%A0%81%E7%9B%AE%E5%BD%95%E7%BB%93%E6%9E%84%E5%8F%8A%E6%9E%84%E5%BB%BA%E9%A1%BB%E7%9F%A5)
