### ISSUE TITLE
为什么多说历史评论不能显示

### ISSUE THREAD

**Issue by hubojing** [litten/hexo-theme-yilia#484]
今天才换回yilia主题，但是多说的历史评论无法显示出来，怎么解决？（目前这一个月我还是需要用多说）谢谢。

**Comment by litten** [comment]
中间用了什么主题？

**Comment by hubojing** [comment]
之前用的是hueman主题。

**Comment by litten** [comment]
看了下，是hueman里使用了完整的path做key导致：https://github.com/ppoffice/hexo-theme-hueman/blob/master/layout/comment/duoshuo.ejs

而yilia是使用path的最后一级：https://github.com/litten/hexo-theme-yilia/blob/master/layout/_partial/post/duoshuo.ejs

这个不匹配导致无法显示。

---------------------------
yilia使用path最后一级做key，原因是为了应对域名变更
---------------------------

现在这种情况，唯一的办法就是把多说评论导出，批量删掉前面的域名，再导入了。

**Comment by hubojing** [comment]
我竟然过了这么久才看到......依然感谢作者认真的回复！
