### ISSUE TITLE
头像不显示

### ISSUE THREAD

**Issue by shuangqingfeng** [litten/hexo-theme-yilia#486]
<img src="null" class="js-avatar"> 这个是调试的时候 直接显示null
 这是我配置的路径

avatar: "https://github.com/shuangqingfeng/shuangqingfeng.github.io/tree/master/assets/img.jpg"
希望大神给帮忙解决下

**Comment by LA-Star** [comment]
我也遇到类似的问题了，请问怎么换成自己的头像 @shuangqingfeng

**Comment by shuangqingfeng** [comment]
@LA-Star  我现在也没有解决这个问题

**Comment by litten** [comment]
……… 因为这个链接本身就是404额
另外我不建议使用外链

这里供[参考](https://github.com/litten/BlogBackup)
我习惯把资源放```/source/assets```里，并在_config.yml里引用

**Comment by LA-Star** [comment]
你可以找一个图片放到主题文件夹下的source/img目录，然后在主题文件夹下的_config.yml文件中的“avatar”这一项配置你图片所放的位置。
![image](https://cloud.githubusercontent.com/assets/7287206/25216353/c1be6cb2-25d4-11e7-9bb3-cd5a1f7125b6.png)
![image](https://cloud.githubusercontent.com/assets/7287206/25216372/db654776-25d4-11e7-8f6f-1a671da47d3b.png)

**Comment by shuangqingfeng** [comment]
@litten 我是头像图片是放在/source/assets 
![image](https://cloud.githubusercontent.com/assets/15327236/25321026/e758896a-28dd-11e7-8fdd-70675555a8d4.png)
通过命令行编译推送到github，现在为止还是不显示 
![image](https://cloud.githubusercontent.com/assets/15327236/25321038/0629fc48-28de-11e7-9cd5-fff401659424.png)

这是我在配置文件的引用
![image](https://cloud.githubusercontent.com/assets/15327236/25321043/13a2021c-28de-11e7-8e93-42adbca59efa.png)

**Comment by LA-Star** [comment]
把图片放到主题文件夹下，是主题！是主题！是主题！
![image](https://cloud.githubusercontent.com/assets/7287206/25321250/8be06dc6-28df-11e7-9e22-592a583e111e.png)
然后通过hexo clean命令清理，hexo g 重新生成一下。

**Comment by shuangqingfeng** [comment]
@LA-Star  图片一定要是png吗 
![image](https://cloud.githubusercontent.com/assets/15327236/25321874/90507112-28e4-11e7-8d35-b8cbe81df025.png)
 我现在 放到 
![image](https://cloud.githubusercontent.com/assets/15327236/25321888/9f38bff4-28e4-11e7-8eef-7a8dfcc00246.png)

还是显示不出来

**Comment by shuangqingfeng** [comment]
@LA-Star 可否加个QQ交流下

**Comment by LA-Star** [comment]
316615034 @shuangqingfeng

**Comment by clarkchen** [comment]
config 也要在 theme 中修改

**Comment by Huooo** [comment]
大神，最后怎么解决的？我在首页加载时，图片是有的，公共资源中assets文件在控制台源码中存在，但是点进文章详情页时，在控制台的源码中没有assets文件夹，这个遇见过吗？ @shuangqingfeng

**Comment by xiaogalayy** [comment]
啊，的确，在/themes/yilia/source/img/下面放上自己的头像文件，如WechatIMG1.jpeg，然后在/themes/yilia/下面的配置文件中设置：avatar: /img/WechatIMG1.jpeg，就可以搞定啦！

**Comment by sanyouwu** [comment]
@LA-Star
请问下大神，我的图片已经插入。但是图片怎么做成圆形的，比较美观的方式呢？
![image](https://user-images.githubusercontent.com/32358325/44026065-7d35dbb4-9f24-11e8-891b-6ef8c63ff9ec.png)
