### ISSUE TITLE
hexo有没有文章置顶的配置

### ISSUE THREAD

**Issue by BestDingSheng** [litten/hexo-theme-yilia#493]
现在文章顺序是按照时间来排序的， 能不能让置顶的文章置顶 在最上面呢

**Comment by litten** [comment]
文章markdown最前面的设置里
写上:
top: true
noDate: true

然后日期写大一点…

因为置顶应该是hexo做的事情，之前它没有这个功能，我只能用这种方式实现一下

**Comment by stevenjoezhang** [comment]
Hexo 已实现文章置顶参数： https://github.com/hexojs/hexo-generator-index/pull/51
