### ISSUE TITLE
tags标签重大bug,请litten速速解决。谢谢

### ISSUE THREAD

**Issue by 1-code** [litten/hexo-theme-yilia#497]
主页中，tags不显示样式。进入文章体后正常显示tags样式
并且浏览器不兼容。比如：360安全浏览器，google 浏览器。展现样式不同
目测deploy后一样会出现不同浏览器展现样式不同。

请litten 速速解决。谢谢

**Comment by litten** [comment]
………………
为什么这么多人，就你遇到了这个重大bug
先检查下是不是自己文章tags的设置有问题，好吗？

里面文章的头部供参考：https://github.com/litten/BlogBackup/tree/master/source/_posts

**Comment by 1-code** [comment]
你好，litten。节日愉快！

请问：tags 下 标签是4个英文字符吗？

不知道为什么，刚才本地测试了一下。又没有问题了，难道是缓存问题？

感谢！

**Comment by litten** [comment]
跟英文字符个数无关
具体为什么我也不清楚了，但真有可能是你说的缓存问题
一般执行```hexo clean```后，重新编译就能正常
