### ISSUE TITLE
请教一个问题

### ISSUE THREAD

**Issue by Djwei** [litten/hexo-theme-yilia#498]
请问页面主题的名字怎么修改呢...😄 就是头像下面的博客姓名  我没有找到这个属性  希望可以指点一下 谢谢 🙏

**Comment by 1-code** [comment]
https://github.com/litten/BlogBackup
你好，这里是博主备份，可以看看_config.xml 文件里面的信息。

**Comment by Djwei** [comment]
好的 很感谢🙏
