### ISSUE TITLE
本地运行hexo s 显示效果是正常的，但hexo g 后的html 页面布局乱了，求指导。http://beginnor.github.io/

### ISSUE THREAD

**Issue by beginnor** [litten/hexo-theme-yilia#50]

**Comment by litten** [comment]
现在看起来挺正常呀，是已经好了吗？

**Comment by beginnor** [comment]
样式根据其它人的修改了下main.css ，改完现在是没有点击用户名的折叠菜单了。。

**Comment by litten** [comment]
我估计是缓存（之前hexo有这个bug）影响。

建议fix的步骤：
1、删掉theme/yilia文件夹，重新安装一下；
2、删掉博客根目录的db.json文件；
3、执行一下命令``hexo clean``

这时再hexo g看看。

**Comment by litten** [comment]
折叠菜单的问题，检查下theme/yilia下的_config.yml。
tagcloud，friends，aboutme至少有一个有值时，才会出现。

**Comment by beginnor** [comment]
好的，我找时间再弄下，主题很好用，多谢！

**Comment by bubbleatgit** [comment]
你试试先hexo clean 删除public里已经生成的文件，然后在hexo g , hexo s看看效果

2015-05-10 15:42 GMT+08:00 beginnor <notifications@github.com>:
