### ISSUE TITLE
头像在文章详情页不显示

### ISSUE THREAD

**Issue by Mrshihe** [litten/hexo-theme-yilia#500]

**Comment by Mrshihe** [comment]
已经找到原因，解决了

**Comment by xulei96** [comment]
你好,是什么原因,,我也遇到了

**Comment by desnbo** [comment]
@xulei96  
之前也不小心掉坑了QAQ .. 
这是因为配置文件中头像路径是 **img/me.jpg** ,前面没有` /` 这会导致路径是相对于当前路径的位置,
应修改为 **/img/me.jpg** 相对于根目录下就能正常显示了!
