### ISSUE TITLE
关于文章文字截断

### ISSUE THREAD

**Issue by newJX** [litten/hexo-theme-yilia#502]
发现首页显示文章的时候没有截断文章而是全部显示了，看了配置文件有这个：
# 文章太长，截断按钮文字
excerpt_link: more
但是好像没生效？请问该如何配置？

**Comment by zmdstr** [comment]
你应该在你的文章内容中适当位置添加下标签

这样，文章后面的内容在首页就不显示了。

**Comment by newJX** [comment]
可以了~
感谢~
