### ISSUE TITLE
请教下如图红框中的文字在哪配的，config里面貌似没有类似字段

### ISSUE THREAD

**Issue by vitaminbat** [litten/hexo-theme-yilia#504]
如图:
http://upload-images.jianshu.io/upload_images/1702515-0143b2d0763d872d.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240

**Comment by desnbo** [comment]
博客根目录下的配置文件中  
[BlogRoot]/_config.yml  
subtitle:

**Comment by vitaminbat** [comment]
谢谢！
