### ISSUE TITLE
请教 文章上一篇 下一篇位置相反

### ISSUE THREAD

**Issue by desnbo** [litten/hexo-theme-yilia#505]
文章底部下一篇应该在右边,而我的是相反的
发现问题后有重新clone的最新的主题,问题依旧存在,不知道是什么原因 
[效果如下所示: ](https://desnbo.github.io/)  
![](https://github.com/desnbo/md-images/blob/master/test_1.png?raw=true)
![](https://github.com/desnbo/md-images/blob/master/test_2.png?raw=true)

**Comment by litten** [comment]
请问有找到原因吗，能否分享下？
看到这问题，我没能重现也没找到原因

**Comment by desnbo** [comment]
@litten  并不知道具体原因, 中间添加过一些功能插件后无意间发现正常了,
我也感觉挺奇怪.

**Comment by NoahDragon** [comment]
是由於Hexo的代碼造成的，更新最近版本即可修復。

**Comment by litten** [comment]
ok，谢谢@NoahDragon 提供信息

**Comment by desnbo** [comment]
感谢 @NoahDragon 的帮助,谢谢 :simple_smile:
