### ISSUE TITLE
请教一个/photo的问题

### ISSUE THREAD

**Issue by pengpn** [litten/hexo-theme-yilia#507]
我安装这个主题后，也可以像您的blog那样有个photo的展示吗
那这些图片放在哪个文件夹下面？

**Comment by litten** [comment]
不行，这个是额外自己做的，并不通用
但您可以参考下实现源码：https://github.com/litten/BlogBackup/tree/master/source/photos

图片放哪里其实都没关系，但github page有大小限制，图片多了不建议放github page里
