### ISSUE TITLE
如何截取文章长度

### ISSUE THREAD

**Issue by tdyhacker** [litten/hexo-theme-yilia#51]
文章列表页显示的文章内容太长了，请问怎么在列表页截取文章内容，显示文章的预览

**Comment by xiajinchun** [comment]
你这就是在列表页面显示每片文章的摘要嘛，在你要显示的摘要部分的后面加上`<!--more-->`这一行，那么在列表页面就显示这一行前面的文章内容，他们称之为 摘要。希望能够帮助你。

**Comment by tdyhacker** [comment]
@xiajinchun 我现在就是这样做的，但是没办法做到自动吗？

**Comment by xiajinchun** [comment]
@tdyhacker 自动应该不行吧，这个毕竟生成的是静态html文件，我也不太清楚了:)。

**Comment by tdyhacker** [comment]
@xiajinchun 你现在就是这样做的么？

**Comment by xiajinchun** [comment]
@tdyhacker 对呀，通过`<!--more-->`来控制的。

**Comment by litten** [comment]
多谢 @xiajinchun 热心回答。

@tdyhacker 目前hexo还有其他的静态博客，都是通过``<!--more-->``来让用户自主控制。尽管简单的自动分割可以实现，但有许多场景不太现实。

有些内容在中间被截断不太好，比如表格，代码段，诗句，比如截断成“逼死强迫症患者还不简”
