### ISSUE TITLE
网易跟帖 如果是git page 会提示url或者站点有问题的错误～

### ISSUE THREAD

**Issue by mrpsweet** [litten/hexo-theme-yilia#510]
网易跟帖 如果是git page 会提示url或者站点有问题的错误～
如题 。那么是否需要买个域名

**Comment by litten** [comment]
之前没听说网易云跟帖需要域名备案呀，具体是提示什么错误？
还有你是怎么配置的？

能否贴一下

**Comment by djming** [comment]
在其他文章里面看到似乎是github域名导致的url已存在，所以应该是需要自己弄个域名，我现在也在找其他的留言系统。。。

**Comment by jazhLeo** [comment]
关于畅言无备份使用，可以来我blog看下。jazhleo.github.io

**Comment by mrpsweet** [comment]
@djming 回去使用你的方式 thanks
