### ISSUE TITLE
所有文章列表下文章链接错误且无时间

### ISSUE THREAD

**Issue by djming** [litten/hexo-theme-yilia#511]
你好，我使用的环境是node 7.9.0，yillia的配置文件只修改头像介绍之类的，在本机测试的时候有时候也会出现缺失模块的问题问题，但是缺失模块的时候列表里面仍然有文章。。。
发到gitpage上就没有这种提示了，但是列表项指向的地址是”/undefined“，而且时间显示是“NaN-NaN-NaN”
￼
![82137c39-050c-47cd-a029-5594d04b77a5](https://cloud.githubusercontent.com/assets/11514804/26058015/89fe7248-39ae-11e7-94be-437d2e68ad5c.png)

**Comment by litten** [comment]
看现象是，生成的列表有问题：https://djming.github.io/content.json?t=1494855076758
而正常是这样的结构：http://litten.me/content.json?t=1494855076758

是不是在_config.yml里写的配置有问题，要注意严格的换行和缩进
这个给你参考下：
https://github.com/litten/BlogBackup/blob/master/_config.yml

**Comment by djming** [comment]
是了是了，之前在vim里面编辑失误，用sublime打开才发现后面几行少了两个空格，竟然一直没看出来。。。感谢，这个主题很好看！
