### ISSUE TITLE
 把GithubPage搬迁到虚拟主机之后，发现Tag标签部分不能正常使用了

### ISSUE THREAD

**Issue by itgoyo** [litten/hexo-theme-yilia#513]
@litten 
up主，你好
我把我github上面的工程项目完全的搬迁到自己的虚拟主机，就出现了这个问题，但是在自己itgoyo.github.io上边显示是能正常显示的，不知道是什么引起的，所以想请up主帮解答一下，谢谢。
![](http://i2.muimg.com/588926/1a50a9e40782068a.png)

-----

我在想是不是我上传的方式不对，我用的是使用FTP工具上传到服务器的，而不是使用hexo d 提交，因为不知道怎么在_config.yml怎么配置，毕竟还要输后台的账号密码什么的，和提交到github上边不同感觉，麻烦up主，或者看见此问题，能解答的朋友帮忙解答一下，吴童鞋在此先谢过各位朋友。

**Comment by litten** [comment]
搬迁到虚拟主机后的域名是什么？
我得看看具体情况才知道

**Comment by itgoyo** [comment]
虚拟主机的域名: http://mkosto.gotoip11.com/
由于还没有备案,chrome可能会提示危险链接什么的
谢谢up主抽空帮解答.

**Comment by litten** [comment]
这个文件，是用来展示文章列表的：http://mkosto.gotoip11.com/content.json?t=1495163571930
只要它正常，你的博客就正常。

现在看起来是服务器配置问题导致额，根据它的提示尝试一下吧。

另外使用这个插件，能hexo d到后台，比ftp会方便些：https://github.com/hexojs/hexo-deployer-rsync

**Comment by itgoyo** [comment]
嗯,好的,content.json确实显示异常
这个插件是个好东西
谢谢up主
![](http://omvbl46i3.bkt.clouddn.com/17-5-19/3164599-file_1495164168637_17b12.jpg)

**Comment by itgoyo** [comment]
还有刚刚说的Tag问题解决了,虚拟主机上的域名不能识别.json文件
在后台设置一下MIME映射
```
.json             application/octet-stream
```
![](http://omvbl46i3.bkt.clouddn.com/17-5-19/51655893-file_1495165123562_ddc.png)
