### ISSUE TITLE
移动端点more后文字显示不全

### ISSUE THREAD

**Issue by SecondCorwin** [litten/hexo-theme-yilia#514]
你好，点more来显示全部时，因为网页的上面总会有“主页”那一栏，所以遮盖了部分more之后的文字导致每次都要往上翻一点，请问这个应该怎么调整？

**Comment by litten** [comment]
这个是锚点，标记读到的位置，进入文章详情页后，就到达那个位置
之所以要做这个，是因为之前有人投诉，说应该这样……………
这就很尴尬了

所以现在“more”是锚点，“展开全文”不记录位置而在顶端。

有这个要求的人还比较少，我决定暂时不调整。抱歉兄弟。

**Comment by SecondCorwin** [comment]
谢谢你的回复，好的，能理解，谢谢！
