### ISSUE TITLE
网易云跟帖无法配置

### ISSUE THREAD

**Issue by rokudol** [litten/hexo-theme-yilia#515]
按照wiki上的配置方法，将网易云跟帖的productKey写在了theme的_config的wangyiyun中，值是'value'，但是正式环境中，始终无法显示评论框，请问具体该怎么配置？value需不需要用引号括起来？需要的话是单引号还是双引号呢？

**Comment by holidaying** [comment]
有空格的

**Comment by rokudol** [comment]
@holidaying 有在最前面添加一个半角空格，但依然不行，value我也试过不加引号，加单引号，双引号。。都不行= =

**Comment by holidaying** [comment]
我的是可以的

**Comment by rokudol** [comment]
@holidaying 能把你theme目录下的_config配置的网易云跟帖发给我看看吗？

**Comment by holidaying** [comment]
![image](https://cloud.githubusercontent.com/assets/12896717/26339596/973f665c-3fbb-11e7-82fd-f872f131527e.png)

**Comment by rokudol** [comment]
@holidaying 我还是不行= =你是用的nexT主题吗？

**Comment by holidaying** [comment]
yaila主题

**Comment by rokudol** [comment]
@holidaying 好吧，谢谢，我试了试还是不行。。畅言倒是可以

**Comment by holidaying** [comment]
没有

**Comment by holidaying** [comment]
![image](https://cloud.githubusercontent.com/assets/12896717/26350591/58c0acda-3fe6-11e7-8a13-72196c8b2ebf.png)正确的是wangyiyun这个字段用不上主要是gentie_productKey

**Comment by rokudol** [comment]
我也看了源码了，确实没找出问题。。。然后换成了next就可以了。。。也只是把productKey放上去就行了，不知道错在哪里，不过还是谢谢你！
