### ISSUE TITLE
如果yilia更新了，我自己怎么更新？

### ISSUE THREAD

**Issue by LiuGuoGY** [litten/hexo-theme-yilia#525]
比如litten改bug完，我怎么更新主题？

**Comment by XElengo** [comment]
我是把自己主题里的文章和图片那两个文件夹，还有配置文件先单独拿出来，然后down litten的框架，覆盖本地已有的旧版本。再把自己的配置文件，文章放到对应的位置。重新编译。就这样。个人建议更新之前先备份自己的博客和旧框架。

**Comment by tidus5** [comment]
我用的是 git submodule命令。  theme里的 yilia 单独作为子模块。
要更新，首先把建一个  pr 到自己 fork 的yilia 项目，  然后主页项目cd 到yilia下，git pull 就行了

**Comment by seawaylee** [comment]
我也想知道有没有好办法@litten

**Comment by litten** [comment]
其实是一个git使用的问题。

1. 普通用户基本只会修改_config.yml文件，这时只要``git pull``下来即可；
2. 如果你有修改源文件，做了一些编译工作，建议自行fork，再选择性merge我这边的更新。

@tidus5 提供的方法也非常好。总之方法有很多，前提是你理解了git。
