### ISSUE TITLE
请问可以改变正文和代码区字体大小吗？

### ISSUE THREAD

**Issue by yehuohan** [litten/hexo-theme-yilia#529]
请问可以改变正文和代码区字体大小吗？有点小，看着眼睛不舒服

**Comment by wenboo** [comment]
1，markdown 一级二级三级等格式，如 # / ## / ###
2，代码区黑色确实不好看 :(

**Comment by Sodaoo** [comment]
markdown 可以实现高亮 , 

``` [language]
.................
```
就可以了

比如 👍 
```cpp
,,,,,,,,,,,,,
,,,,,,,,,,,
```
是可以高亮的

**Comment by Sodaoo** [comment]
\`\`\`python
你的代码
\`\`\`

**Comment by yehuohan** [comment]
高亮我知道，我指的是代码区里面的字体有点小，不知道怎样变大点

**Comment by Demian101** [comment]
嘿嘿嘿

修改代码块的背景色和字体大小 :
找到这个文件 :
blog\themes\yilia\source\main.507b3a.css
搜索 :.article-entry .highlight,对应背景和字体颜色即可

**Comment by Demian101** [comment]
我就是真么改的.  https://sodaoo.github.io/2017/11/15/LeetCode-3/

**Comment by yehuohan** [comment]
666~

**Comment by donk3yzz** [comment]
blog\themes\yilia\source-cre\highlight.css 我觉得应该是改这个文件比较合适吧。。。[Yilia源码目录结构及构建须知](https://github.com/litten/hexo-theme-yilia/wiki/Yilia%E6%BA%90%E7%A0%81%E7%9B%AE%E5%BD%95%E7%BB%93%E6%9E%84%E5%8F%8A%E6%9E%84%E5%BB%BA%E9%A1%BB%E7%9F%A5)也说source-src是source的源文件，😂但是我不会改23333
