### ISSUE TITLE
移动端显示时遇到的几个问题

### ISSUE THREAD

**Issue by xiajinchun** [litten/hexo-theme-yilia#53]
作者，你好：
很喜欢你的这个主题，很简约，在使用的过程中，遇到几个问题，前2个问题都是在移动端时候适配的问题，我也尝试修复，但是没能解决 :(

1.在手机端（或者直接将浏览器宽度调至最小）回展现出移动端的样式来，但是发现此时用fancybox图片展示的时候，如果遇到图片原始长度较长，就不能够正常显示（手机端效果更明显），下面是我遇到的情况截的图，我看到了你的博客也会出现这样的问题。
![586dec48-b919-48fb-af8a-c3b146add68b](https://cloud.githubusercontent.com/assets/4453349/7451762/1c123992-f287-11e4-9059-7f000a2b2ee0.png)

2.用平板衡平的时候，在主页显示文章标题的时候，标题过长会覆盖后面的日期显示。

![de30d8da-f09c-4088-971d-14a816e20835](https://cloud.githubusercontent.com/assets/4453349/7451910/16f690d2-f289-11e4-9042-ea8b8a2c386b.png)

3.主题在高清屏（如Retina）上显示是，有些图片（如Subnav和多说分享）由于像素问题会失真，我尝试使用FontAwesome来解决。

以上问题请作者赐教，我尝试在本地解决，然后pull request，谢谢。

**Comment by litten** [comment]
好的，谢谢。赐教不敢当。

1、是fancybox兼容性问题，体验不够好，下个版本我决定在移动端取缔掉它，可以先不改动哈；
2、属于bug，固定一下标题的最大宽度可解决；
3、之前方案考虑欠缺，多谢提醒，subnav用iconfont方案可解决像素问题；多说分享就貌似没太大办法了
