### ISSUE TITLE
想问下这个是用markdown语法对嘛，但是输入数学公式的时候无效

### ISSUE THREAD

**Issue by cherrygh** [litten/hexo-theme-yilia#532]
--最近用这个做笔记，markdown语法用$$\mu$$输入数学公式，在其他编辑器上显示没问题，但是在这个主题下并没有转化成数学公式形式，想问下这是所有hexo主题存在的问题还是yilia存在的问题，还是我使用方法不对（原谅我是个小白），最后谢谢分享~
补充--问题解决了 修改主题下的_config文件中的数学公式，改为true。
啊好丢人这么简单的问题也来问--还是感谢分享

**Comment by secsilm** [comment]
@cherrygh 我想请教下多行公式显示不了（`\begin{aligned}`）以及 `_` 被当做斜体标识的问题你怎么解决的？
