### ISSUE TITLE
如何给文章加密？

### ISSUE THREAD

**Issue by hi-yo-coco** [litten/hexo-theme-yilia#533]
尝试在文章内部加入如下代码，但没有任何效果。求大腿。

<script>
    if("12345678"==prompt("请输入密码"))
    {
        alert("正确");
    }
    else
    {
        alert("错误");
        location="http://blog.laphets.com"; #返回网站，请自定义
    }
</script>

**Comment by hi-yo-coco** [comment]
已解决。请参考 https://crackcer.com/hexo-aes-password.html

**Comment by litten** [comment]
还有这种操作……？

**Comment by Kkkb** [comment]
链接失效了，可以再提供一下加密方法吗？
供参考[hexo-blog-encrypt](https://github.com/MikeCoder/hexo-blog-encrypt)
