### ISSUE TITLE
左侧的小房子按钮没有了

### ISSUE THREAD

**Issue by AgoniNemo** [litten/hexo-theme-yilia#534]
<img width="280" alt="9929af09-c492-4413-b5dd-a75de11b437b" src="https://user-images.githubusercontent.com/13228978/27010266-bff4b31a-4ed2-11e7-9fc6-b704daf3b9dd.png">

**Comment by RuMengRen** [comment]
字体文件没加载吧

**Comment by mrpsweet** [comment]
看看报错

**Comment by AgoniNemo** [comment]
@mrpsweet 没有报错

**Comment by mrpsweet** [comment]
请问 你的主页怎么做的@AgoniNemo

**Comment by AgoniNemo** [comment]
@mrpsweet 从别人那里爬下来的，你想用也可以爬我的，修改下就可以了

**Comment by mrpsweet** [comment]
好像没有看到你的项目目录结构~~~~~~(>_<)~~~~

**Comment by AgoniNemo** [comment]
首页入口是另外做的，不在博客的目录时，这周找个时间我把教程放到我博客里吧

**Comment by AgoniNemo** [comment]
@mrpsweet 首页入口是另外做的，不在博客的目录时，这周找个时间我把教程放到我博客里吧

**Comment by mrpsweet** [comment]
@AgoniNemo  谢谢，你做的主页非常棒 我学会了 一定奥推广一波☺️

**Comment by AgoniNemo** [comment]
@mrpsweet 由于上周比较忙，这周末抽了个时间写了个教程，已放到博客上，你可以看下，有什么不明白可以留言，评论系统用的是默认的，要翻墙，你也可以在这里留言给我。

**Comment by mrpsweet** [comment]
http://www.jianshu.com/p/4eaddcbe4d12 我看了简书上的搭建方法，之后github.io里就有文件了，博主所说的现在你的备份之后再放在io上  是放哪个文件呢？还有就是想请教一下怎么用hexo创建新的页面。

**Comment by AgoniNemo** [comment]
@mrpsweet [备份](https://git.oschina.net/AgoniNemo/backup)文件点这里，上次写教程的时候忘记加上了。要说明一点的是，首界面（比如：username.github.io）与博客主界面（创建的时候是Respository name填写的是blog,而真实的地址是：username.github.io/blog）是两个不同的仓库，所以是不会有被清除的情况的。

**Comment by mrpsweet** [comment]
嗯嗯，谢谢 已经捣鼓出来了。万里长征感觉还剩最后两步。
1、使用yilia的主题layout生成不了，所以现在暂时还是用的landspace的主题。
2、好想想你一样的用域名，而不是用github这种形式展现自己的blog。

**Comment by Alone-123** [comment]
你的博客地址是 @AgoniNemo

**Comment by AgoniNemo** [comment]
@Alone-123 [博客地址](https://agoninemo.github.io/)
