### ISSUE TITLE
希望litten大佬可以出个返回顶部功能

### ISSUE THREAD

**Issue by XnU132** [litten/hexo-theme-yilia#535]
@litten  说下个人的体会，本渣在写一些博文（其实就是些日记吧）或是浏览其他博主的博客的时候，发现有的文章实在太长，如果没有“返回顶部”这么一个按钮，要使用鼠标中键一直滚一直滚才能翻到顶部的话实在有点恐怖或者说是不方便。虽然尝试过使用网友的方法使用js在页面右下角添加一个按钮，实现这么个功能，不过本人照着他的教程来似乎不太成功。按钮可以显示出来，但是实际功能却没法实现。操作步骤应该是没问题的，反复检查了好几遍也没发现什么毛病，不知道是不是主题的原因、、
具体什么原因，刚接触前端没多久的某渣想找也不知道从何找起，于是就希望大佬可以出个教程讲讲这么个小功能的实现方法（无奈本渣学的不是计算机，HTML什么的都只会些皮毛，完全就是以兴趣作为动力靠自学来满足自己的愿望，所以还请大佬讲的稍微详细点！谢谢！）

**Comment by litten** [comment]
好的，返回顶部和toc功能，提要求的人挺多。本周会支持。

靠兴趣学东西最好不过了，坚持&加油。

**Comment by itgoyo** [comment]
强势围观还有坐等 litten大大的新版本

**Comment by LiuGuoGY** [comment]
坐等升级

**Comment by GoNtte** [comment]
期待更新

**Comment by iCyris** [comment]
期待更新。

**Comment by litten** [comment]
已更新，不好意思……突发事情有点多，食言了。
希望不算太晚

**Comment by XnU132** [comment]
没事的大佬，前段时间某渣也是忙着复习准备末考，没时间弄这个东西，现在刚放假正好有时间可以看一下

**Comment by XnU132** [comment]
大佬辛苦了
