### ISSUE TITLE
有问题

### ISSUE THREAD

**Issue by LiuGuoGY** [litten/hexo-theme-yilia#539]
@litten 
![qq 20170621134622](https://user-images.githubusercontent.com/24603342/27368953-0f4b55f6-5688-11e7-820f-229fea02d3b3.png)
请作者查看原因。
手机端Chrome浏览器和Safari浏览器，不能完全加载。

**Comment by litten** [comment]
https://github.com/litten/hexo-theme-yilia/issues/528

上报用的，不需要采集时我会关掉。
另外这是异步加载，不影响你网站的性能，请放心
