### ISSUE TITLE
duoshuo shortkey设置正确但是评论区仍显示true's me正在使用多说

### ISSUE THREAD

**Issue by lan2720** [litten/hexo-theme-yilia#54]
你好，刚刚使用hexo
我把duoshuo: “xxx” 设置成自己的shortkey之后，还是显示true‘s me正在使用多说
博客地址http://lan2720.github.io/
谢谢啦

**Comment by bubbleatgit** [comment]
https://github.com/litten/hexo-theme-yilia/issues/60
一样的问题
