### ISSUE TITLE
希望解决https下不安全的问题

### ISSUE THREAD

**Issue by LiuGuoGY** [litten/hexo-theme-yilia#541]
主页时，chrome提示安全，但是进入到具体某一篇时，chrome显示
![qq 20170625023718](https://user-images.githubusercontent.com/24603342/27511041-79ad3bd4-594f-11e7-9ca1-11a431074bd7.png)

急切希望作者解决这个问题。

盼复！

**Comment by cexoso** [comment]
imho 这个应该不关作者的事

**Comment by LiuGuoGY** [comment]
@cexoso 同样的设置，next主题就是安全的，我估计这个可以解决，但不知道什么原因

**Comment by RuMengRen** [comment]
我的貌似就没问题

**Comment by LiuGuoGY** [comment]
@RuMengRen `貌似` 这个词很好

**Comment by wangdabaoqq** [comment]
这个是网站链接的问题跟作者没有关系呀

**Comment by LiuGuoGY** [comment]
@wangdabaoqq 是网站元素里有http成分，但是我找不到。。

**Comment by litten** [comment]
http://osllzmq34.bkt.clouddn.com/%E6%96%B0%E5%BB%BAAssets_folder.png-shuiyin

@LiuGuoGY 因为你的这张图片是http…

**Comment by litten** [comment]
还有二维码：
http://s.jiathis.com/qrcode.php?url=https://www.liuguogy.cn/posts/2972fe6e/

**Comment by litten** [comment]
http://s.jiathis.com/qrcode.php?url=https://www.liuguogy.cn/posts/2972fe6e/

好像jiathis的二维码生成，只支持http，这个我没有太好的办法；
如果你用https，直接在配置里使用图片吧

**Comment by LiuGuoGY** [comment]
@litten 谢大佬回复，但是这张图是之后加的，请看主页第二页，上面就是小绿锁，但是点进没有图片的文章里，小绿锁就没了，求litten大佬解决，万分感谢！

**Comment by LiuGuoGY** [comment]
@litten 多谢，我试试！

**Comment by LiuGuoGY** [comment]
@litten 大佬，请问直接在哪个文件里如何改？

**Comment by LiuGuoGY** [comment]
@litten 大佬，我yilia根目录npm install 失败，好多错误，有一条让我设置代理好像，请问怎么解决？

**Comment by LiuGuoGY** [comment]
铛铛铛铛，小绿锁回来了

**Comment by litten** [comment]
@LiuGuoGY 666
