### ISSUE TITLE
点击tag部分文章不显示

### ISSUE THREAD

**Issue by CTBUmyq** [litten/hexo-theme-yilia#545]
点击我的error的tag，但是 部分error标签的文章未被显示，且标签的颜色不一样。标签的颜色是随机还是根据浏览量？难道是我tags的格式的原因？tags格式使用的是 - tagName的方式。

**Comment by LiuGuoGY** [comment]
首先，不要有tab，必须使用空格，其次，使用格式
tags:
- 标签1
- 标签2

**Comment by CTBUmyq** [comment]
@LiuGuoGY   格式没错且使用的空格，很尴尬

**Comment by CTBUmyq** [comment]
@LiuGuoGY  ok了，更新了一下模版就ok了
