### ISSUE TITLE
如何自定义主页。

### ISSUE THREAD

**Issue by mrpsweet** [litten/hexo-theme-yilia#546]
如题，本小白对模板引擎不熟悉。只会html js css  自己写了个主页，不知道怎么加进来，望大神们告知。

**Comment by RuMengRen** [comment]
我曾经写了一个，在head里面写一段JS，具体作用就是检查cookie，如果不存在则跳转到主页，存在不做操作，主页中负责更新或添加这个cookie。

**Comment by RuMengRen** [comment]
RBR，无意义

**Comment by mrpsweet** [comment]
我见到一个人写的是  写的html 然后点击之后才进入blog 昨天我看了些hexo的文档，奈何魔都天热，着实不想写代码。[你可以看看](agoninemo.github.io)

**Comment by LiuGuoGY** [comment]
@mrpsweet 主页很漂亮

**Comment by litten** [comment]
@mrpsweet 我的相册就是加进来的，参考这个[目录结构](https://github.com/litten/BlogBackup/tree/master/source/photos)

**Comment by xiaoshenmao** [comment]
@mrpsweet不管是增加了自定义首页,还是装了hexo改文章目录的插件,导致搜索现在用不了了

**Comment by mrpsweet** [comment]
@xiaoshenmao 不知道你说的搜索是不是在`所有文章`下的搜索，这个地方我刚刚试了一下貌似可以用。

**Comment by mrpsweet** [comment]
@RuMengRen 基本上解决的差不多了，就是加载主页的时候有点慢其他的小bugs还是有的。
   最后说一句<font color=#0099ff size=4 face="黑体">吾王美如画</font>
