### ISSUE TITLE
Chrome下，窄屏的Navigation呼不出来

### ISSUE THREAD

**Issue by uulee** [litten/hexo-theme-yilia#55]
**反馈一个issue**
Chrome下，将视口调整到窄屏显示，点击导航，导航出不来。

**Comment by pengrun** [comment]
我也存在这个问题

**Comment by litten** [comment]
作为个浏览你blog的用户，这种非要调小屏幕再看文章的奇怪操作其实很少…
但的确算是个bug，之前的窄屏事件统一绑定是touchend
放后续移动端优化里再统一处理

**Comment by BlackHole1** [comment]
已解决，在/ylia/source/js/mobile.js文件的第92行改成
```javascript
ctn.addEventListener("touchend", function(event){
	show();
	event.preventDefault()
}, false);
```

**Comment by uulee** [comment]
@BlackHole1 Thanks!
Chrome 下已验证。Issue 关闭。
