### ISSUE TITLE
畅言没有提交评论按钮

### ISSUE THREAD

**Issue by CoderWuao** [litten/hexo-theme-yilia#552]
畅言评论框没有左右框线,也没有按钮了, 博主自己的也是一样, 什么原因呢?

**Comment by litten** [comment]
什么浏览器？另外请截图一下，语言描述需要脑补…

**Comment by CoderWuao** [comment]
chrome哦, 是这个样子的
![image](https://user-images.githubusercontent.com/22411671/27991295-6de25496-64a4-11e7-8d9c-6f1a58d37d01.png)

**Comment by CoderWuao** [comment]
昨天都还是好好的, 今天就这样了,页面显示一直在加载
