### ISSUE TITLE
litten大佬，弱弱的问一句，toc的背景色如何更改？

### ISSUE THREAD

**Issue by XnU132** [litten/hexo-theme-yilia#554]
就是那个鼠标置于toc按钮上方时弹出来的天蓝色半透明的对话框（也就是目录。。），某渣真的很想知道这个背景色是在哪个地方定义的，以前就尝试过将分享按钮和打赏按钮的背景色修改为自己想要的颜色，可是失败了，原因是找不到设置该属性的位置。。尴尬 =_=!!   本不想暴露自己的智商想将此事掩埋于心的，可是某渣实在是忍不住了 （>_<）求教求教，谢谢谢谢！！

**Comment by litten** [comment]
来，告诉你找代码的方法。

开发者工具定位到想修改的元素，看到它的className是``tooltip-content``

![20170710220140](https://user-images.githubusercontent.com/2024949/28021744-88610caa-65bb-11e7-92ef-66b1591f885d.png)

然后无论你是用sublime还是vscode或其他编辑器，都有全局搜索关键字功能的。搜``tooltip-content``，
就能找到是在这里[aside.scss](https://github.com/litten/hexo-theme-yilia/blob/master/source-src/css/aside.scss)

**Comment by XnU132** [comment]
原来如此原来如此  感谢大佬指点

**Comment by XnU132** [comment]
感觉这对小白来说还是有点难度啊、、弄了好久还是没找到定义toc小尖尖部分的代码，不过大部分颜色都被本渣改了，就是显示出来有些突兀，不知突兀的那部分到底要如何修改、、还望大佬指点一下下！！

**Comment by XnU132** [comment]
呃呃  又花了点时间，可算是找到了

**Comment by zangbo** [comment]
您好，请问那个尖尖部分的代码找到了吗，我也没找到 @XnU132

**Comment by XnU132** [comment]
其代码在/source/fonts/tooltip.4004ff.svg  修改fill后面的值即可 @zangbo

**Comment by HaoLiuwide** [comment]
您好，我修改aside.scss后还是没有变化，咋办？
![Snipaste_2019-10-18_16-54-44](https://user-images.githubusercontent.com/45302756/67080708-5d257580-f1c8-11e9-9cad-b57d28074328.png)
