### ISSUE TITLE
js-avatar头像设置图片仅显示一半

### ISSUE THREAD

**Issue by admiralanker** [litten/hexo-theme-yilia#555]
![image](https://user-images.githubusercontent.com/24274374/28023356-4dbecb00-65c0-11e7-8571-100e48c8caa5.png)
![image](https://user-images.githubusercontent.com/24274374/28023501-a8105d6c-65c0-11e7-80a6-5b086d45423d.png)

**Comment by admiralanker** [comment]
经过观察使用同主题的其他人的blog，猜测是图片本身的问题，然后尝试了多次像素修改，发现需要使用宽度不高于高度的图片就会正常显示了

**Comment by litten** [comment]
请自行裁剪图片成正方形。

也许你会疑问，为啥我不用css裁剪呢？
因为众口难调，如果不是正方形，有些人希望拉伸，有些人希望居中裁剪。
之前yilia是居中裁剪的，恰好一姑娘用到，我把人家的大长腿给剪没了…
非常惭愧，从那以后yilia的头像只有等比缩放。

（另外并没有固定宽高，你看的面板是computed吧，宽高是灰置的）

**Comment by admiralanker** [comment]
感谢litten的主题分享和及时帮忙解决问题
