### ISSUE TITLE
请问您的代码怎样给所有网页加网页左侧小图标

### ISSUE THREAD

**Issue by Simplehippo** [litten/hexo-theme-yilia#557]
就像这样
![1](https://user-images.githubusercontent.com/24547457/28098586-b2d73b74-66e9-11e7-8813-ecf507becc91.png)

**Comment by Simplehippo** [comment]
您好,我已经知道了,十分感谢您的主题~
解决方法如下:
1.用git方式pull,push
      在github博客代码根路径下加一个图标图片,更名为favicon.png
2.hexo方式
      在hexo博客本地的public文件夹根路径加一个图标图片,更名为favicon.png,然后hexo g,hexo d

**Comment by litten** [comment]
👍
