### ISSUE TITLE
分类导航怎么添加

### ISSUE THREAD

**Issue by bubbleatgit** [litten/hexo-theme-yilia#56]
分类导航怎么添加

**Comment by ghw** [comment]
# Header
 menu:
-  主页: /
-  所有文章: /archives
-  # 随笔: /tags/随笔
+  主页: /notes/
+  归档: /notes/archives/
+  财会: /notes/categories/财会
+  技术: /notes/categories/技术
+  其它: /notes/categories/其它

酱紫，，

**Comment by cikichen** [comment]
有没有办法一个菜单对应多个标签

**Comment by flashblogs** [comment]
@ghw  hexo的主题分类，专门有一个页面的（多见时间线），这个主题没有把。。另外加了categories 文章的左下角的categories样式还有问题
