### ISSUE TITLE
标签更新后，旧标签还会存在

### ISSUE THREAD

**Issue by zsqosos** [litten/hexo-theme-yilia#561]
bug复现步骤
1. 创建新文章a，设置tags为b
2. 编译并预览，标签中出现b标签
3. 修改文章a的tags，将b改为c
4. 编译并预览，标签中显示b和c。并不是c将b替换，而是以前的旧标签b还会存在

编译前已执行hexo clean，编译后依然会存在旧标签

**Comment by zsqosos** [comment]
可能是缓存问题，已解决

**Comment by litten** [comment]
描述得很清楚，点个赞 👍 

怀疑是缓存时，除了执行hexo clean，还可以试下删除根目录的db.json
