### ISSUE TITLE
在浏览器显示的title的图标怎么设置？

### ISSUE THREAD

**Issue by AmazingLynch** [litten/hexo-theme-yilia#564]
首先，想感谢您提供这么好看的主题。想问下，怎么设置网站的title那里的图标。（就是在浏览器选项卡那里title旁边的图标）。

**Comment by litten** [comment]
参考下：https://github.com/litten/hexo-theme-yilia/issues/557

那个叫``favicon ``，请在根目录的``_config.yml``里设置，跟你的头像放在同样的路径即可
