### ISSUE TITLE
刷新时头像闪动，npm run dev 报错

### ISSUE THREAD

**Issue by zsqosos** [litten/hexo-theme-yilia#566]
1. 更新后刷新主页或者点击主页按钮，头像会闪一下才出现。而您的博客不存在这样的问题，您的博客点击主页或刷新时头像不会出现闪动。[详情请点击](http://zsqos.xin)，在点击下一页、点击其他目录、点击头像、点击作者名称时，都会出现头像闪动这个问题，请问这是什么原因？
2. 修改source-src目录内的文件后，执行`npm run dev` 或 `npm run dist`打包，会报错，错误信息如下
![2017-07-20 00-14-32](https://user-images.githubusercontent.com/21467874/28377865-c7d3ccd4-6ce0-11e7-8995-f1bd22ee257f.png)

3. 报错原因为`source-src/js/viewer.js`目录下的`photoSwipe`模块未找到，`viewer.js`中的引入的如下
![2017-07-20 00-20-08](https://user-images.githubusercontent.com/21467874/28378281-4081fcea-6ce2-11e7-99a1-8a4235af074b.png)
而`node_modules`中`photoswipe`目录如下
![2017-07-20 00-29-00](https://user-images.githubusercontent.com/21467874/28378431-b36b832a-6ce2-11e7-92c9-1f00c57b5f8d.png)
发现`viewer.js`中引入模块名与`node_modules`文件名不一致，`viewer.js`中的引入为`photoSwipe`，`node_modules`中的文件夹名为`photoswipe`，所以需将`viewer.js`中的`photoSwipe`的`S`改为小写，如下
![2017-07-20 00-37-25](https://user-images.githubusercontent.com/21467874/28378733-c847a8ea-6ce3-11e7-812c-a2a9e7c5d002.png)
修改后打包正常，建议修改代码。

**Comment by LiuGuoGY** [comment]
@zsqosos 求教怎么弄npm install，我求了 @litten 几天了，都没回答我，网上搜了一大堆，都有问题，我在hexo根目录npm install没问题，但是在yilia根目录下npm install就报错，求指教。

感谢万分！

**Comment by zsqosos** [comment]
@LiuGuoGY yilia目录下运行npm install不应该有问题，你可以将错误信息贴出来

**Comment by LiuGuoGY** [comment]
@zsqosos 
Log如下，多谢！
[2017-07-20T13_19_52_853Z-debug.txt](https://github.com/litten/hexo-theme-yilia/files/1162442/2017-07-20T13_19_52_853Z-debug.txt)

**Comment by zsqosos** [comment]
头像闪动问题已解决，原因是我使用了头像使用了图床。

**Comment by Azha3** [comment]
@zsqosos 想请教你，你的统计数据是怎么在页面上显示的？

**Comment by zsqosos** [comment]
@Azha3 统计数据用的是[不蒜子](http://busuanzi.ibruce.info/)
