### ISSUE TITLE
请问如何设置网站404页面

### ISSUE THREAD

**Issue by Azha3** [litten/hexo-theme-yilia#571]
有想法插入腾讯公益404页面，不知道代码应该插在哪一块
求助大神们指教

**Comment by Azha3** [comment]
解决方法：
新建404.html页面放到source目录下面。（注意，不要放到source下的post里面）
放在source下的文件会被上传但不会被解析到文章里面
<!DOCTYPE html>
<html>
<head>
	<meta charset="UTF-8">
	<title>404</title>
</head>
<body>
	自定义
</body>
</html>
或者 加入腾讯公益
<!DOCTYPE html>
<html>
<head>
	<meta charset="UTF-8">
	<title>404</title>
</head>
<body>
	<script type="text/javascript" src="//qzonestyle.gtimg.cn/qzone/hybrid/app/404/search_children.js" charset="utf-8" homePageUrl="http://yoursite.com/yourPage.html" homePageName="回到我的主页"></script></script>
</body>
</html>
再次hexo  d -g即可

**Comment by litten** [comment]
👍

**Comment by shdjllajksd** [comment]
👍
