### ISSUE TITLE
如何将github.io博客转到域名网站上？

### ISSUE THREAD

**Issue by mrpsweet** [litten/hexo-theme-yilia#574]
准备买一个域名，不知道如何将github.io转到域名上。前端小白，望楼主海涵。

**Comment by itgoyo** [comment]
看到没人回答，我就回答算了，弄一个CHNAME映射，还有就是你用别人的东西要知道原理，你只是把别人的首页加了进去，导致你只能访问主页，但是跳转是进不了你的hexo文章目录，如果你要加你现在的主页，那你的Github要有两个仓库，一个是你现在的主页，一个是hexo目录

**Comment by mrpsweet** [comment]
@itgoyo  谢谢。我是昨晚弄得，原理其实不是很明白。我用的github.io仓库的时候用了主页，那么hexo目录用什么仓库名字(无辜脸)。就算弄好了/blog该怎么连接两者~~
第二个问题是，我以为是在hexo目录里开一个blog的页面，然后用现在的主页，点击之后连接到我hexo目录页面。
求老司机带路

**Comment by itgoyo** [comment]
你弄一个 yourid.github.com的仓库里边丢index主页，你在弄一个blog仓库，把index引向你的地址就可以了，详细的你可以看看你之前参照人的个人仓库

**Comment by mrpsweet** [comment]
嗯，谢谢昨晚尝试了一下，现在已经可以用了。冒昧的问一句我如果买一个域名，怎么才能把github.io
上的东西搬运到我的网站上。

**Comment by itgoyo** [comment]
@mrpsweet CHNAME文件直接丢到你github仓库，里面写上你的域名

**Comment by mrpsweet** [comment]
用了yilia的主题之后layout报错生成不了，所以只能用原来的主题了landspaec(自带的)

**Comment by MironChen** [comment]
我昨天才刚刚完成 Hexo+Yilia+自定域名的设置，很顺利啊

**Comment by mrpsweet** [comment]
麻烦贴一下你看的网址  我试着弄一下

**Comment by MironChen** [comment]
http://www.jianshu.com/p/1d427e888dda
https://yq.aliyun.com/articles/64953
第二个查IP可以直接填GitHub的IP
