### ISSUE TITLE
主题会发送一个请求到https://litten.me:9005/badjs/，并且地址不可达

### ISSUE THREAD

**Issue by kong36088** [litten/hexo-theme-yilia#580]
这个是什么请求？是作者对站点做的数据上报统计？
![qq 20170806123136](https://user-images.githubusercontent.com/11497913/29000631-aa987888-7aa3-11e7-8c21-200c430b66b4.png)
![qq 20170806123147](https://user-images.githubusercontent.com/11497913/29000635-bcda8c20-7aa3-11e7-838d-d67ee5fad992.png)

**Comment by levin950825** [comment]
@kong36088 把 
`hexo-theme-yilia/source/main.266c1c.js` 里面的所有内容都清空

**Comment by litten** [comment]
@kong36088 请看下这里：https://github.com/litten/hexo-theme-yilia/issues/528

我不一定会常开这个服务，通常是在主题更新后几天会开启。帮助分析和设计。
它是异步的，并不会对性能产生影响，请放心
