### ISSUE TITLE
实现相册时预览大图时报错

### ISSUE THREAD

**Issue by darrenfantasy** [litten/hexo-theme-yilia#581]
你好，我的blog用的是其他的主题，但是想实现相册功能，就照着你的主题来实现了，但是现在遇到问题就是点击预览的时候报错，这是我的相册：http://darrenfantasy.com/album/   能不能有空的时候帮我分析下什么原因导致这个错误的呢？谢谢啦

**Comment by darrenfantasy** [comment]
已解决

**Comment by xiaweizi** [comment]
@darrenfantasy 怎么实现大图效果
