### ISSUE TITLE
在谷歌浏览器上会报错

### ISSUE THREAD

**Issue by anyao** [litten/hexo-theme-yilia#585]
name: 
?id=1&uin=https://annyao.cn&msg=yilia-annyao.cn&ex…tps%3A%2F%2Fannyao.cn%2F&level=4&_t=1502528801666
litten.me/badjs
status: (failed)
net::ERR_CONNECTION_CLOSED

initator:
main.266c1c.js:8
Script

**Comment by litten** [comment]
https://github.com/litten/hexo-theme-yilia/issues/580
https://github.com/litten/hexo-theme-yilia/issues/528

**Comment by anyao** [comment]
嗯，好吧。就可能会逼死强迫症。
