### ISSUE TITLE
innerArchive的小bug

### ISSUE THREAD

**Issue by Viciberty** [litten/hexo-theme-yilia#589]
不知能否请问下，能否调整innerArchive指向的链接呢，因为我用的是xxx.me/blog，但是innerActive的搜索结果会指向根域名，更改设置里的root也没用

**Comment by Freeruzy** [comment]
自己修改slider js  filter  改变返回的路径，不能编译的直接修改编译完成的文件
查找urlformat定位，之后改返回路径

**Comment by aibucai** [comment]
不是很明白楼上说的，具体该怎么操作，什么slider js filter....

**Comment by litten** [comment]
是一个bug，已经修复了。更新就好
