### ISSUE TITLE
首页文章列表，动态显示逻辑可能需要修改

### ISSUE THREAD

**Issue by korvin101** [litten/hexo-theme-yilia#59]
我也不知道是不是这样说了，这个问题和屏幕高度、浏览器高度有关，请看截图，看上去全站只有两篇文章，其实后面还是有文章的，只要下移动一点点就显示出来了。[http://iblogc.com/](http://iblogc.com/)
![ashampoo_snap_2015 05 10_00h19m57s_002_chrome legacy window](https://cloud.githubusercontent.com/assets/3283023/7551028/19668e32-f6ab-11e4-94ed-89d021df1aa2.png)

**Comment by litten** [comment]
好的，谢谢反馈，这里逻辑的确需要再完善下

**Comment by litten** [comment]
已优化动画逻辑。
另外提供了个_config.yml配置项```animate```，如果不需要动画也可以设为false

**Comment by korvin101** [comment]
晚上回去更新试试:smile:
