### ISSUE TITLE
设置头像 支付宝 微信收款 没反应

### ISSUE THREAD

**Issue by 123xiao** [litten/hexo-theme-yilia#590]
avatar: /assets/blogImg/tx.gif

# 打赏
# 打赏type设定：0-关闭打赏； 1-文章对应的md文件里有reward:true属性，才有打赏； 2-所有文章均有打赏
reward_type: 2
# 打赏wording
reward_wording: '谢谢你请我吃糖果'
# 支付宝二维码图片地址，跟你设置头像的方式一样。比如：/assets/img/alipay.jpg
alipay: /assets/img/zhifubao.png
# 微信二维码图片地址
weixin: /assets/img/weixin.png

# 目录
# 目录设定：0-不显示目录； 1-文章对应的md文件里有toc:true属性，才有目录； 2-所有文章均显示目录
toc: 1
# 根据自己的习惯来设置，如果你的目录标题习惯有标号，置为true即可隐藏hexo重复的序号；否则置为false
toc_hide_index: true
# 目录为空时的提示
toc_empty_wording: '目录，不存在的…'

# 是否有快速回到顶部的按钮
top: true

这是我的配置

**Comment by litten** [comment]
你的图片在文件夹里的位置，能截个图给我看吗？

我从配置看不出太多的东西，得对照文件位置去看。但我直观感觉你的存放位置有点混乱…？
``/assets/blogImg/tx.gif``与``/assets/img/zhifubao.png``

**Comment by Drowned-fish** [comment]
头像是要求放在哪个文件夹下？还是路径要从哪开始写
