### ISSUE TITLE
tag

### ISSUE THREAD

**Issue by sleafummer** [litten/hexo-theme-yilia#595]
![image](https://user-images.githubusercontent.com/12785925/29559107-b63b47c8-8760-11e7-9678-f3f2d804b09c.png)
![image](https://user-images.githubusercontent.com/12785925/29559115-ba0e1dc6-8760-11e7-92c4-798126e9aae7.png)

**Comment by sleafummer** [comment]
![issue](https://user-images.githubusercontent.com/12785925/29559031-841482c8-8760-11e7-85c1-188f02040687.png)
![issuce png2](https://user-images.githubusercontent.com/12785925/29559052-92f14d80-8760-11e7-84c6-03b0879b6ca8.png)

请问是什么导致的？

**Comment by litten** [comment]
请详细看下hexo里多个tags的写法，供参考：https://raw.githubusercontent.com/litten/BlogBackup/master/source/_posts/history-of-browser-useragent.markdown
