### ISSUE TITLE
主页头像等图片加载正确，到了第二页或者详情页后图片加载不。

### ISSUE THREAD

**Issue by mrpsweet** [litten/hexo-theme-yilia#598]
主页头像等图片加载正确，到了第二页或者详情页后图片加载不。 这个问题很诡异，因为到了第二页第三页 理论上侧边栏的头像位置加载图片路径是一样的。`(index):48 GET https://mrpsweet.github.io/blog/page/2/assets/img/avatar.jpg 404 ()` 我看到一个这样的错误 博主有没有好的意见。🙃

**Comment by litten** [comment]
设置头像的配置请写一下？

**Comment by wu95** [comment]
请问，我的也是这样，到了详情页面头像就不显示了，有什么解决办法吗，copy主题是最新的

**Comment by mrpsweet** [comment]
#你的头像url
`avatar: assets/img/avatar.jpg` @litten 全路径应该是`blog-github/source/assets/img/avatar.jpg`
`theme`与`source`文件夹同级

**Comment by litten** [comment]
请改成``avatar: /assets/img/avatar.jpg``试试

发现有很多同学没分清这3种路径写法的区别：
``xxx/yyy``
``/xxx/yyy``
``./xxx/yyy``

**Comment by mrpsweet** [comment]
`/xx`代表绝对路径
修改后： `https://mrpsweet.github.io/assets/img/avatar.jpg` 是报的404 error
是不是因为我的主页是个index.html
所有的blog 放在blog的仓库里 导致的。
主页地址：`https://github.com/mrpsweet/mrpsweet.github.io`
blog地址：`https://github.com/mrpsweet/blog`

**Comment by litten** [comment]
哦，那就应该是``avatar: /blog/assets/img/avatar.jpg``
试下可以吗？

**Comment by mrpsweet** [comment]
Thank you~  是的路径的问题  我太缺乏思考了，再次感谢O(∩_∩)O~
