### ISSUE TITLE
多说配置问题

### ISSUE THREAD

**Issue by duxinfeng** [litten/hexo-theme-yilia#60]
按照您的提示，我的Blog里面还是显示True's ME正在使用多说，多些不忙的时候帮我看看 http://duxinfeng.com

**Comment by duxinfeng** [comment]
已经解决了。 duoshuo: duoshuo-key 填错了。

登录多说后设置域名，比如xxxx.duoshuo.com，那么duoshuo-key就是xxxx

**Comment by bubbleatgit** [comment]
这个其实也是作者写的不够明白,我当时也捣鼓了下

**Comment by sjy** [comment]
谢谢 我也遇到了这样的问题。
