### ISSUE TITLE
添加 Gitment 评论系统的支持

### ISSUE THREAD

**Issue by StarryFK** [litten/hexo-theme-yilia#601]
**RT，希望能加入对 [Gitment](https://github.com/imsun/gitment) 这一评论系统的支持**

**Comment by frapples** [comment]
支持，国内各种评论系统相继倒闭。对搭建在github上的博客来说，gitment这个是最靠谱的了

**Comment by xiaoshenmao** [comment]
自己添加的,可观看效果 https://xiaoshenmao.github.io/blog/

**Comment by StarryFK** [comment]
是直接在主题内加的代码么？

Sent from my BlackBerry - the most secure mobile device

**Comment by iCyris** [comment]
的确现有的Gitment的教程对yilia的适配感觉不太好，评论区抵在了两边，跟文章区不太对应。

**Comment by litten** [comment]
@StarryFK @iCyris @frapples 已经支持，请更新

**Comment by iCyris** [comment]
感谢～

**Comment by StarryFK** [comment]
@litten 感谢大大

**Comment by ibambooooo** [comment]
对呀 yilia 怎么调整样式
