### ISSUE TITLE
index 主页文件路径不正确，就是主页的路径，在哪里修改

### ISSUE THREAD

**Issue by qingfenger** [litten/hexo-theme-yilia#606]
是发布到github之后路径找不到，在本地一样的路径没有问题，是什么原因啊

![qq 20170904151801](https://user-images.githubusercontent.com/13749686/30015710-7deda8a6-9184-11e7-906d-2a0afaea0561.jpg)
![qq 20170904151828](https://user-images.githubusercontent.com/13749686/30015723-8fa6410c-9184-11e7-897f-078e99034746.jpg)

**Comment by litten** [comment]
网址发一下？

**Comment by qingfenger** [comment]
https://qingfenger.github.io/fullstack.github.io/

**Comment by litten** [comment]
hexo配置问题，检查下根目录的_config.yml（注意不是yilia目录下的）的root设置

应该是 ```root: /fullstack.github.io/```

**Comment by qingfenger** [comment]
嗯嗯，好了，谢谢
