### ISSUE TITLE
所有文章点击显示的文章列表路径少了root路径

### ISSUE THREAD

**Issue by qingfenger** [litten/hexo-theme-yilia#608]
这是配置
![image](https://user-images.githubusercontent.com/13749686/30032302-bd604f00-91c7-11e7-9354-0a7d805e404d.png)
现象
![image](https://user-images.githubusercontent.com/13749686/30032371-1cad9c4c-91c8-11e7-91be-e8bcf9c1b4fc.png)
![image](https://user-images.githubusercontent.com/13749686/30032439-8bde4198-91c8-11e7-9bbb-990af2b290c4.png)
该怎么解决啊

**Comment by xiaoshenmao** [comment]
修改slider js filter 改变返回的路径，不能编译的直接修改编译完成的文件
查找urlformat定位，修改需要返回的路径

**Comment by litten** [comment]
看起来是个bug

**Comment by litten** [comment]
@qingfenger 已经修复，请更新

**Comment by qingfenger** [comment]
@litten 嗯嗯，好了，谢谢
