### ISSUE TITLE
为什么没有小房子了？感觉主题风格和一些其他yilia博客不一致

### ISSUE THREAD

**Issue by tony-yin** [litten/hexo-theme-yilia#612]
我下载了yilia，按照步骤搭建了博客，但是感觉风格和一些其他使用yilia的用户都有出入，比如作者litten的博客没有小房子，文章截断左侧有more代码等等，我还看一些其他人的，比如http://blog.damonare.cn/2016/11/26/Hexo%E6%8A%98%E8%85%BE%E8%AE%B0/

有很多人都类似这样的，我想知道怎么能搞成这样，更好看一些

**Comment by tony-yin** [comment]
我下载了yilia，按照步骤搭建了博客，但是感觉风格和一些其他使用yilia的用户都有出入，比如作者litten的博客没有小房子，文章截断左侧有more代码等等，我还看一些其他人的，比如http://blog.damonare.cn/2016/11/26/Hexo%E6%8A%98%E8%85%BE%E8%AE%B0/，有很多人都类似这样的，我想知道怎么能搞成这样，更好看一些

**Comment by litten** [comment]
小房子是两年前的设计了…这个设计我也很喜欢，但按交互设计来说也有它的弊病，思前想后在3.0版本去掉了。另外yilia是一个开源项目，有些朋友喜欢自行fork，按照自己的思路做了修改。

如果你喜欢小房子，可以找一下Yilia3.0之前的版本：https://github.com/litten/hexo-theme-yilia/tree/415d35deade88c3e5da9b4ed4add093cf5cf5ff8，它还在。

最后谢谢你的喜欢。

**Comment by tony-yin** [comment]
谢谢你
