### ISSUE TITLE
litten老哥，“关于我”是不是有字数限制？

### ISSUE THREAD

**Issue by 656025633** [litten/hexo-theme-yilia#615]
字数多的时候会报这个异常：ERROR Theme config load failed.
ERROR Process failed: _config.yml
YAMLException: can not read a block mapping entry; a multiline key may not be an implicit key at line 111, column 1

**Comment by jazhLeo** [comment]
换行了？

**Comment by litten** [comment]
没有限制。检查你的_config.yml文件，冒号之后要加一个空格。
因为yaml看起来可以写得很随意，其实限制很多，要注意遵守它的规则

供参考：
http://www.ruanyifeng.com/blog/2016/07/yaml.html?f=tt
