### ISSUE TITLE
求一个路径问题：markdown引入的图片点击查看全文后就没有了

### ISSUE THREAD

**Issue by Yanzengyong** [litten/hexo-theme-yilia#617]
我应该这么做？？？

**Comment by Yanzengyong** [comment]
已经解决了，文章路径source/_post/xxx.md, 图片路径source/img/xxx.png    在文章中引用的时候![](../img/xxx.png)无法在点击全文后显示；应该用![](/img/xxx.png)

**Comment by litten** [comment]
👍

**Comment by zhoujingchao** [comment]
66666
