### ISSUE TITLE
首页为何直接显示全文 没有more

### ISSUE THREAD

**Issue by BeGoodBOY** [litten/hexo-theme-yilia#619]
我的首页全文就直接展开了 没有more 设置如下
# 文章太长，截断按钮文字
excerpt_link: more
# 文章卡片右下角常驻链接，不需要请设置为false
show_all_link: '展开全文'
# 数学公式
mathjax: false
# 是否在新窗口打开链接
open_in_new: false

**Comment by litten** [comment]
https://github.com/litten/hexo-theme-yilia/issues/399

**Comment by BeGoodBOY** [comment]
多谢 么么哒
