### ISSUE TITLE
Cannot read property 'innerArchive' of undefined

### ISSUE THREAD

**Issue by mzq1210** [litten/hexo-theme-yilia#620]
请问_config.yml中配置了smart_menu.innerArchive，但是主题文件好多地方都找不到这个变量的原因是什么？

**Comment by yaomo** [comment]
解决了么？同样的问题

**Comment by ranying666** [comment]
有时候正常，有时候报这个错，完全没找到原因。用上一个版本时没有遇到这个问题，更新后才出现的

**Comment by ranying666** [comment]
搞了一上午终于找到原因了，因为在windows平台下编辑文件会包括特殊换行符导致只要修改了原配置文件都会出现这个问题。解决办法：在git-bash中编辑_config.yml等文件一点问题没有。
给我点赞~\(≧▽≦)/~
