### ISSUE TITLE
为什么会显示历史的标签？

### ISSUE THREAD

**Issue by baolintian** [litten/hexo-theme-yilia#624]
我之前写好了一篇文章，使用了hexo generate，之后又修改了文章的标签，但是历史的标签还保存着。请问是怎么回事？
![tag](https://user-images.githubusercontent.com/30475927/30812726-262e934e-a23e-11e7-94da-ec411c688667.png)

**Comment by baolintian** [comment]
知道了 
使用hexo clean
hexo generate就可以了

**Comment by litten** [comment]
👍
