### ISSUE TITLE
最新commit的修复畅言阻塞可能引起了新的bug

### ISSUE THREAD

**Issue by vioren** [litten/hexo-theme-yilia#626]
尝试在PC使用Chrome打开文章详情页，正常浏览显示，使用手机或者浏览器的开发者模式模拟手机，进入详情页则直接白屏，打开console调试，提示找不到id为SOHU的div，预计是js提前加载，此时页面还未加载完毕，故阻塞异常，在几款浏览器测试均可复现。

**Comment by litten** [comment]
谢谢提供信息，会修复

**Comment by tywei90** [comment]
解决了吗？我也遇到了

**Comment by litten** [comment]
已经修复了，忘了回复
