### ISSUE TITLE
头像及网站名称处URL错误

### ISSUE THREAD

**Issue by lemurhh** [litten/hexo-theme-yilia#627]
URL的path部分为当前页面的path加上null，如下：
<img width="960" alt="default" src="https://user-images.githubusercontent.com/25481476/31186227-a76f2d0a-a960-11e7-8b65-afb6e170d5cf.PNG">

**Comment by litten** [comment]
多谢提供bug信息

**Comment by fy5220** [comment]
这个问题修复了么?

**Comment by litten** [comment]
已经修复了，有点迟不好意思
