### ISSUE TITLE
main.507b3a.js总是发起一个失败的请求???

### ISSUE THREAD

**Issue by mystic-cg** [litten/hexo-theme-yilia#630]
Request URL:http://litten.me:9005/badjs/?id=1&uin=http://litten.me&msg=yilia-litten.me&ext=%7B%7D&from=http%3A%2F%2Flitten.me%2F2017%2F07%2F09%2Fprevent-spiders%2F&level=4&_t=1507438384756
Referrer Policy:no-referrer-when-downgrade
Request Headers
Provisional headers are shown
Referer:http://litten.me/2017/07/09/prevent-spiders/
User-Agent:Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3218.0 Safari/537.36
Query String Parameters
view source
view URL encoded
id:1
uin:http://litten.me
msg:yilia-litten.me
ext:{}
from:http://litten.me/2017/07/09/prevent-spiders/
level:4
_t:1507438384756
@litten 这是你自己的博客,依然有这个问题???

**Comment by mystic-cg** [comment]
这是我这边发起的请求
Request URL:https://litten.me:9005/badjs/?id=1&uin=https://caoyu.info&msg=yilia-caoyu.info&ext=%7B%7D&from=https%3A%2F%2Fcaoyu.info%2Fmy-first-blog.html&level=4&_t=1507437602975
Referrer Policy:no-referrer-when-downgrade
Request Headers
Provisional headers are shown
Referer:https://caoyu.info/my-first-blog.html
User-Agent:Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3218.0 Safari/537.36
Query String Parameters
view source
view URL encoded
id:1
uin:https://caoyu.info
msg:yilia-caoyu.info
ext:{}
from:https://caoyu.info/my-first-blog.html
level:4
_t:1507437602975

**Comment by litten** [comment]
参考：https://github.com/litten/hexo-theme-yilia/issues/528
https://github.com/litten/hexo-theme-yilia/issues/580

**Comment by mystic-cg** [comment]
好的,了解了!谢谢!

**Comment by beautycss** [comment]
同样是这个问题，但是现在问题是现在请求一直无相应，阻塞了页面加载。
