### ISSUE TITLE
js加载失败

### ISSUE THREAD

**Issue by Azha3** [litten/hexo-theme-yilia#631]
我打算新建一个黄历版块（模仿您的相册版块）
可是js文件（或者直接放在html或ejs里）无法被加载，直接复制网页源码到本地html文件里则可以运行，这是为什么呢？

**Comment by litten** [comment]
请问是怎么引用js文件的呢，有没有可访问的链接让我看一下？

**Comment by Azha3** [comment]
@litten [](http://azha.site/Almanac/)这个是我的链接谢谢！

**Comment by litten** [comment]
为什么说是“加载失败”呢？
这是加载成功了，运行时的语法出错呀…

![image](https://user-images.githubusercontent.com/2024949/31348920-beb3ca6e-ace6-11e7-9ac0-09ee63cf0f29.png)

**Comment by Azha3** [comment]
好的 我再看看 谢谢指导！

**Comment by Azha3** [comment]
@litten 
![image](https://user-images.githubusercontent.com/19308130/31396301-a243c37c-ae15-11e7-87e3-4b8f3b79a7aa.png
我的js文件在source文件夹里没加载出来，但已经上传了，只好把所有的js文件内容复制到ejs文件里，这样可以运行但是显得很冗杂。检查了博主的网页代码，发现是包含js文件(ins.js)的，不知道是否是因为我使用yilia主题但是样式没设置好的原因，求解？
