### ISSUE TITLE
仅对自己可见

### ISSUE THREAD

**Issue by vinniegogo** [litten/hexo-theme-yilia#635]
你好，有没有什么配置能使某篇文章仅对自己可见？

**Comment by litten** [comment]
不支持。hexo是静态博客，不能识别怎样才算“自己”。
但有个比较粗浅的加密方案，可以参考下：https://github.com/litten/hexo-theme-yilia/issues/533

**Comment by vinniegogo** [comment]
试过了 ，赞👍
