### ISSUE TITLE
字体太大怎么调整

### ISSUE THREAD

**Issue by yhyzgn** [litten/hexo-theme-yilia#636]

**Comment by Azha3** [comment]
源代码里找font-size改字号

**Comment by litten** [comment]
需求太特殊了，只能自行fork，参考[wiki](https://github.com/litten/hexo-theme-yilia/wiki/Yilia%E6%BA%90%E7%A0%81%E7%9B%AE%E5%BD%95%E7%BB%93%E6%9E%84%E5%8F%8A%E6%9E%84%E5%BB%BA%E9%A1%BB%E7%9F%A5)自行修改

或者…站远一点看屏幕…
