### ISSUE TITLE
国内coding增加博客评论系统了，仿gitment，望添加

### ISSUE THREAD

**Issue by krissss** [litten/hexo-theme-yilia#641]
[这里这里](http://yangconghou.coding.me/Comments/?utm_source=newsletter&utm_medium=email&utm_campaign=2017-10)

**Comment by hearain528** [comment]
给你点个赞，，因为我用的就是coding.net..所以一直想为啥coding.net没有这功能，，居然在这里找到了

**Comment by hearain528** [comment]
https://www.hearain.club/2017/11/07/Hexo%E7%9A%84yilia%E4%B8%BB%E9%A2%98%E4%B8%AA%E6%80%A7%E5%8C%96-%E5%A2%9E%E5%8A%A0%E8%AF%84%E8%AE%BA%E5%8A%9F%E8%83%BD/
成功示例

**Comment by EVINK** [comment]
我也成功了!
https://code.evink.me/2017/10/14/Hexo:%20%E4%B8%BA%E5%8D%9A%E5%AE%A2%E5%A2%9E%E5%8A%A0coding-ment%E8%AF%84%E8%AE%BA%E7%B3%BB%E7%BB%9F/

**Comment by hearain528** [comment]
恭喜

**Comment by Yanzengyong** [comment]
@hearain528 你好，看了下你的博客 请问怎么加阅读量？

**Comment by hearain528** [comment]
@Yanzengyong 
这篇博客里面有https://www.hearain.club/2017/02/27/Hexo%E7%9A%84yilia%E4%B8%BB%E9%A2%98%E4%B8%AA%E6%80%A7%E5%8C%96-%E5%A2%9E%E5%8A%A0%E6%96%87%E7%AB%A0%E9%98%85%E8%AF%BB%E9%87%8F/
