### ISSUE TITLE
菜单无法配置分类和标签页

### ISSUE THREAD

**Issue by StormMaybin** [litten/hexo-theme-yilia#648]
你好，我想请问一下怎么配置菜单分类和标签！谢谢

**Comment by goodryb** [comment]
菜单请编辑_config.yml中smart_menu部分
![](https://ws3.sinaimg.cn/large/006tKfTcgy1flautdazo9j308g04v3yx.jpg)

标签请编辑 _config.yml中的menu部分
![](https://ws2.sinaimg.cn/large/006tKfTcgy1flaur3pzx4j305b03e3yk.jpg)

**Comment by litten** [comment]
多谢 @goodryb 解答
