### ISSUE TITLE
“yilia”, which is not supported by GitHub Pages 本地部署没有问题

### ISSUE THREAD

**Issue by AlwaysYang** [litten/hexo-theme-yilia#651]
本地显示一切都正常 不知道为什么一直部署失败
github一直给我发邮件
The page build completed successfully, but returned the following warning:

You are attempting to use a Jekyll theme, “yilia”, which is not supported by GitHub Pages. Please visit https://pages.github.com/themes/ for a list of supported themes. If you are using the “theme” configuration variable for something other than a Jekyll theme, we recommend you rename this variable throughout your site. For more information, see https://help.github.com/articles/adding-a-jekyll-theme-to-your-github-pages-site/.

For information on troubleshooting Jekyll see:

https://help.github.com/articles/troubleshooting-jekyll-builds

If you have any questions you can contact us by replying to this email.
我明明是 hexo主题 不知道为什么一直不支持

**Comment by litten** [comment]
卸载hexo重装试试，这个问题我没遇到过，但不是主题的问题。

可参考下其他issue：https://github.com/hexojs/hexo/issues/2588
