### ISSUE TITLE
如何删除一个已存在的标签? 

### ISSUE THREAD

**Issue by Sodaoo** [litten/hexo-theme-yilia#653]
我把所有含有这个标签的文章 都删掉了, 但是还是有多余的标签....

求问怎么删除标签?

**Comment by Sodaoo** [comment]
解决了...本地标签多余没法删除  ,但是上传到github 后 , 多余的标签就会自动消失了 .

**Comment by litten** [comment]
👍

**Comment by ddshiyu** [comment]
> 解决了...本地标签多余没法删除 ,但是上传到github 后 , 多余的标签就会自动消失了 .

请问下你是怎么解决的，，为什么我上传到GitHub 还是有多余的标签
