### ISSUE TITLE
博客部署上线后出现badjs错误

### ISSUE THREAD

**Issue by inklife** [litten/hexo-theme-yilia#655]
使用`hexo generate`生成静态文件之后托管静态文件部署，控制台有一个get请求错误：
`litten.me:9005/badjs/?id=1&uin=http://www.91qiao.cn&msg=yilia-www.91qiao.cn…ao.cn%2F2017%2F11%2F05%2Fdebian-install-note%2F&level=4&_t=1510809680502:1 GET http://litten.me:9005/badjs/?id=1&uin=http://www.91qiao.cn&msg=yilia-www.91…qiao.cn%2F2017%2F11%2F05%2Fdebian-install-note%2F&level=4&_t=1510809680502 net::ERR_CONNECTION_REFUSED`
而直接使用`hexo server`则没有报错信息。
请问一下我该如何解决呢？

**Comment by uncn** [comment]
我遇到的问题和你一样

**Comment by litten** [comment]
参考：#528

我不一定会常开这个服务，通常是在主题更新后几天会开启。帮助分析和设计。
它是异步的，并不会对性能产生影响

**Comment by inklife** [comment]
感谢解惑。之前就是疑问为什么部署了CDN之后浏览器还是一直在转，明明资源文件也不大，查了一下原来是有个请求失败。不喜欢浏览器一直转圈，就像 #585 一样，可能要逼死强迫症吧。
