### ISSUE TITLE
使用新主题后老是有资源加载超时

### ISSUE THREAD

**Issue by uncn** [litten/hexo-theme-yilia#657]
加载超时的链接里 老是会出现 http://litten.me:9005/badjs/?id=1&uin 这样的链接，怎么解决？

![tim 20171118102441](https://user-images.githubusercontent.com/7308778/32976110-6d0824c4-cc4b-11e7-9258-c0980096aed6.png)
![tim 20171118102648](https://user-images.githubusercontent.com/7308778/32976111-6d383f38-cc4b-11e7-9278-bb2a12bd6052.png)

**Comment by uncn** [comment]
刚找到了这个js，不清楚这段代码是什么意思？

![tim 20171118104503](https://user-images.githubusercontent.com/7308778/32976288-f9d1979e-cc4d-11e7-8f0e-cf8b40f74c6e.png)

**Comment by litten** [comment]
参考：#528

我不一定会常开这个服务，通常是在主题更新后几天会开启。帮助分析和设计。
它是异步的，并不会对性能产生影响

**Comment by uncn** [comment]
这个统计对功能有影响：
1、加载超时的时间一般是21秒左右
2、最要命的是返回顶部的按钮只有在21秒超时后才会显示出来，你可以从收集的网站里随便找一个打开返回顶部功能的网站看看。
