### ISSUE TITLE
为啥我单独修改打赏配置g之后不更新呢...

### ISSUE THREAD

**Issue by nyahui** [litten/hexo-theme-yilia#659]
是我不小心动了什么格式吗
<img src="https://s1.ax1x.com/2017/11/20/21qMD.png" alt="21qMD.png" border="0" />

**Comment by litten** [comment]
你设置了 reward_type: 1，那在文章对应的md文件头部，有进行设置吗？

**Comment by nyahui** [comment]
不是，1是我后来试验时没改回去......我一开始是1，然后改了打赏图片跟文字，G之后没反应，然后我改成0再G了一遍，结果还是文章里边还是原来的打赏窗口和内容.就是说关闭打赏也要在文章里设置吗？我MD里还没加过什么设置，是这个问题吗？

**Comment by nyahui** [comment]
我把原文件覆盖了一次，这次改都没问题了.....谢谢

**Comment by nyahui** [comment]
我改完1之后想改reward:true结果发现根本不知道哪改。。百度也查不到。我试探着在MD头部加[reward]true之类的结果发现不是这样的...还有TOC的也是 要怎么加啊

**Comment by nyahui** [comment]
好吧找到了emmmm
