### ISSUE TITLE
gitment评论插件不生效

### ISSUE THREAD

**Issue by yc90s** [litten/hexo-theme-yilia#661]
配置完gitment相关的参数，登录后评论区并没有显示Init按钮，仍然是Error：not found

**Comment by ziyziyziy888** [comment]
我也是求解答
![image](https://user-images.githubusercontent.com/22311977/34859862-5a2fddc8-f794-11e7-8ec6-f64899e0b322.png)

**Comment by zhangxiaoshang** [comment]
@ziyziyziy888 你的`gitment_repo`不对 应该是`ziyziyziy88.github.io`

**Comment by ziyziyziy888** [comment]
弄成功了~~感谢  ：D

**Comment by lollipoppp** [comment]
求教，我也是这个问题，登录和授权都可以，但是就是显示Error: Not Found。
`#5、Gitment
gitment_owner: 'lollipopp'      #你的 GitHub ID
gitment_repo: 'lollipopp.github.io'          #存储评论的 repo
gitment_oauth:
  client_id: 'caa0391b38aab0193449'           #client ID
  client_secret: '8ee75a57445e77471602a77fcee355ab142102ce'       #client secret
`
我的博客地址是：https://www.lollipoppp.com/

**Comment by lixiao1k** [comment]
@lollipoppp 參考我的博文，可以解決你的問題http://sheltonlee.cn/2018/01/29/hexo-blog/
