### ISSUE TITLE
开启 disqus 后评论区下方有别人在别的博客下的评论

### ISSUE THREAD

**Issue by secsilm** [litten/hexo-theme-yilia#677]
如题，这是啥情况，为啥在自己的文章下面还有别人在别的博客留下的评论？

![](https://i.imgur.com/uubcmRI.png)

**Comment by secsilm** [comment]
解决了，原来是需要一个 shortname

**Comment by emperinter** [comment]
请问在哪里修改shortname

**Comment by secsilm** [comment]
@emperinter 在主题目录下的 `_config.yml` 文件里，找到 `disqus_shortname` 这一项，在后面写上你的 disqus 用户名。

**Comment by emperinter** [comment]
谢谢！已解决！
