### ISSUE TITLE
样式没有改变问题

### ISSUE THREAD

**Issue by liboyue23** [litten/hexo-theme-yilia#69]
根据你讲述的，下周你的主体，然后pull，然后更改根目录_config.yml文件如图：
![image](https://cloud.githubusercontent.com/assets/11264082/7978242/c2cb2284-0ac5-11e5-8fba-55c61176dfb1.png)
然后访问localhost:4000还是原主题样式
小白新手，请多指教

**Comment by SeriousMa** [comment]
执行hexo generate了么?

**Comment by liboyue23** [comment]
执行了，现在好了，clean一下就好了

**Comment by litten** [comment]
@liboyue23 好的

hexo万能调试方法：
1. hexo clean 试一下
2. 删除根目录db.json 试一下
3. 更新版本试一下
4. 换台电脑试一下
