### ISSUE TITLE
支付宝无法显示图像

### ISSUE THREAD

**Issue by bleedingfight** [litten/hexo-theme-yilia#690]
# yilia _config.yml配置付下
```bash 
31 root: /
 46  reward_type: 2
 47 # 打赏wording
 48 reward_wording: '多谢你的支持!'
 49 # 支付宝二维码图片地址，跟你设置头像的方式一样。比如：/assets/im    g/alipay.jpg
 50 alipay: ‘/assets/AliPay.jpg’
```
我的目录一结构~/Hexo/:这里我我用hexo init初始化后写了博客。然后在这里没有assets目录，为了放置支付宝二维码，我新建了这么一个目录，然后放入文件AliPay.png。本地无法显示图像，上面弹出一个图像未加载完成的图标。
我看了反馈有人说图片太大，因为我的支付宝二维码使用手机上的保存按钮得来的AiliPay.png，于是我将它剪裁了变成了alipy.png(676, 672),然后hexo g，hexo s本地查看发现还是一样，仿佛图像没有加载完成一样，于是我又将图像剪裁为了300x300的png图像，依旧一样。然后我以为格式是不是有问题，于是我转化成了60x60的jpg依旧不行。是我哪里没有设置正确么？有人能告诉我一下吗？

***还有一个问题:root:/是不是表示的我的hexo init目录为根目录？/assets表示根目录下（而不是linux系统的根目录）的assets吗？***

> 我的系统是Deepin15.4，相关信息如下:
hexo: 3.4.4
hexo-cli: 1.0.4
os: Linux 4.9.0-deepin4-amd64 linux x64
http_parser: 2.7.0
node: 10.0.0-pre
v8: 6.3.292.48-node.5
uv: 1.18.0
zlib: 1.2.11
ares: 1.13.0
modules: 60
nghttp2: 1.29.0
openssl: 1.0.2n
icu: 60.1
unicode: 10.0
cldr: 32.0
tz: 2017c

我挺喜欢这个主题的，不想因为这个问题换一个，希望有了解的同学帮我看一下，多谢了。不知道如何在留言中上传图片，附上了我的github.io地址：https://bleedingfight.github.io/2018/01/07/arch/

**Comment by luojinghui** [comment]
@bleedingfight 
这是我的配置，注意格式，图片引用会以项目目录的`source`作为起点，即`/img/w1.png`访问的是`/source/img/w1.png`
```js
# 打赏基础设定：0-关闭打赏； 1-文章对应的md文件里有reward:true属性，才有打赏； 2-所有文章均有打赏
reward_type: 1
# 打赏wording
reward_wording: '谢谢你请我吃糖果'
# 支付宝二维码图片地址，跟你设置头像的方式一样。比如：/assets/img/alipay.jpg
alipay: "/img/apply.png"
# 微信二维码图片地址
weixin: "/img/w2.png"
```
我的博客： [blog](http://luojh.me)

**Comment by luojinghui** [comment]
@bleedingfight 刚才查看了你的代码，请检查你的图片名称是否正确，我更改为"/img/AliPay.jpg"，加载正常。

**Comment by bleedingfight** [comment]
@luojinghui 我刚刚又尝试了一下，现在可以了，应该是我把图像的名称设置错了，不好意思耽误你时间了！多谢你的帮助。多谢！
