### ISSUE TITLE
多说配置

### ISSUE THREAD

**Issue by doeralex** [litten/hexo-theme-yilia#7]
您好，非常喜欢您做的这个主题，现在正在使用，嘿嘿。
在主题的配置文件_config.yml中，“duoshuo”的默认值是“true”，但是上面写的注释是“填写你在多说申请的项目名称”，请问这是什么意思？

**Comment by Forecheng** [comment]
@litten 太谢谢，这个多说的设置页面在他们主页中找不到。^.^

**Comment by ranchoddas** [comment]
貌似成功了
