### ISSUE TITLE
console报错

### ISSUE THREAD

**Issue by ncc0706** [litten/hexo-theme-yilia#704]
Request URL:https://litten.me:9005/badjs/?id=1&uin=https://blog.xlinyu.com&msg=yilia-blog.xlinyu.com&ext=%7B%7D&from=https%3A%2F%2Fblog.xlinyu.com%2F&level=4&_t=1

**Comment by JulianHang** [comment]
有强迫症的同学非要修改的话，可以在根目录下找到source-src/js/report.js文件，将里面的id注释掉或者去掉即可。不过建议最好不好去掉，原因可以见 #580 ，感谢大神提供的主题。
