### ISSUE TITLE
数学公式渲染只有第一个起效果 ，后面全部变成了latex符号。。。。

### ISSUE THREAD

**Issue by bestpredicts** [litten/hexo-theme-yilia#709]
更新一下问题
$$
w=w-{\frac{\partial J(\theta)}{\partial w}}
$$
上面这样是正常渲染，但是加上一个就不行了
$$
w=w-a*{\frac{\partial J(\theta)}{\partial w}}
$$
就无法渲染

**Comment by bestpredicts** [comment]
已经解决是hexo默认的markdown解析器冲突导致的 请更换pandoc

**Comment by YosefQiu** [comment]
怎么更换呢，可以说一下吗

**Comment by tinscon** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
