### ISSUE TITLE
导入主题如何更改头像图片？

### ISSUE THREAD

**Issue by liboyue23** [litten/hexo-theme-yilia#71]
没找到在哪里更换主题头像，还有如何在md文件里面上传图片？小白一个请博主指教

![image](https://cloud.githubusercontent.com/assets/11264082/7984812/4bb7b41c-0afe-11e5-9e89-862350d05273.png)
![image](https://cloud.githubusercontent.com/assets/11264082/7984855/ad661ef6-0afe-11e5-8612-1efce69164aa.png)

**Comment by litten** [comment]
在 yilia 目录下的_config.yml里，有个avatar字段，你可以填写相对或绝对地址展示头像。
供[参考](https://github.com/litten/BlogBackup/blob/master/themes/yilia/_config.yml)。

**Comment by zhubo1234** [comment]
怎么改啊
