### ISSUE TITLE
粗体显示不对？

### ISSUE THREAD

**Issue by JZQT** [litten/hexo-theme-yilia#72]
使用Markdown语法的\*\*粗体\*\*显示的时候发现浏览器标签解析正确，为strong，但是显示却是正常文字，是CSS没写对么？

**Comment by litten** [comment]
粗体是设置的 ```blod: 300```，这样在mac下显示会比较好，可能windows渲染得不太好导致。后面fix下

**Comment by litten** [comment]
已修改
