### ISSUE TITLE
如何备份源文件

### ISSUE THREAD

**Issue by liboyue23** [litten/hexo-theme-yilia#73]
上传到github上面的都是general好的html，但是我怕md文件丢失，该如何保存呢？

**Comment by litten** [comment]
最理想的方法是：hexo支持在_config.yml里写备份git路径，然后一个命令就提交上去了。
然而目前并没有……

我自己是用一个还不是太麻烦的方法，把blog根目录作为另一个git项目：[https://github.com/imweb/blogBackup](https://github.com/imweb/blogBackup)

平时只执行一个简单的*.sh 或 *.bat文件可以实现一键备份&发布。
