### ISSUE TITLE
关于分类页面的问题

### ISSUE THREAD

**Issue by chineselzh** [litten/hexo-theme-yilia#74]
@litten 我使用下面的菜单配置，但分类无效
about页面可以响应，但categories点击后页面无内容！可以确定我的文章都有分类的。。。
请问这个怎么处理呢？谢谢！
menu:
  主页: /
  分类: /categories
  归档: /archives
  关于: /about

**Comment by litten** [comment]
我印象中没有 ```/categories``` 这个页面哦。
如果你某篇文章带了分类，比如叫“工具”，```/categories/工具```这个页面是有的

**Comment by chineselzh** [comment]
@litten 好的，谢谢！呵呵。。。
