### ISSUE TITLE
哥们，可以加个掘金图标吗

### ISSUE THREAD

**Issue by crazysunj** [litten/hexo-theme-yilia#746]

**Comment by liang-pusheng** [comment]
添加新图标可以参考一下这篇博客，虽然我没看懂。。。[https://blog.zscself.com/2017/01/09/70677220/](https://blog.zscself.com/2017/01/09/70677220/)

**Comment by crazysunj** [comment]
没看懂，但是搞好了！

**Comment by plasmacell** [comment]
请教怎么弄得？可以分享一下经验吗？

**Comment by liang-pusheng** [comment]
请问怎么弄得，可以分享一下经验吗？ @crazysunj

**Comment by crazysunj** [comment]
按照那哥们说的来就行了，我不太懂前端。
