### ISSUE TITLE
和 hexo@3.1.1的兼容性问题

### ISSUE THREAD

**Issue by sqrthree** [litten/hexo-theme-yilia#77]
* **执行操作**: 安装最新版的 `hexo` 之后, 使用 `hexo init` 自动部署项目, 安装依赖之后,(其中 `"hexo-server": "^0.1.2"` ). 执行 `hexo server` 命令.
* **问题现象**: 访问页面为空白, 控制台显示 `WARN  No layout: index.html`
* **执行环境**:  
```
hexo: 3.1.1
os: Darwin 14.3.0 darwin x64
http_parser: 2.3
node: 0.12.2
v8: 3.28.73
uv: 1.4.2-node1
zlib: 1.2.8
modules: 14
openssl: 1.0.1m
```

**Comment by litten** [comment]
我的环境是正常的，说明不是兼容问题：
```
hexo: 3.1.1
os: Windows_NT 6.1.7601 win32 x64
http_parser: 2.3
node: 0.12.3
v8: 3.28.71.19
uv: 1.5.0
zlib: 1.2.8
modules: 14
openssl: 1.0.1m
```

出现这种情况有可能是找不到index.ejs源文件。
请检查下```themes/yilia/layout/``` 文件夹里是否有```index.ejs```文件，以及目录结构是否与[yilia layout](https://github.com/litten/hexo-theme-yilia/tree/master/layout)保持一致

**Comment by sqrthree** [comment]
不好意思, 刚发现是我 `pull` 下来之后忘了修改主题名字导致的, 现在把文件夹名字改成 `yilia` 之后就好了.😂

**Comment by guanruihua** [comment]
自定义主题, 用最新版本后也出现该问题, 老版本没问题
