### ISSUE TITLE
长链接不会自动换行

### ISSUE THREAD

**Issue by msdx** [litten/hexo-theme-yilia#801]
貌似很长的链接不会自动换行。
见 http://www.githang.com/2018/12/10/AndroidManifest-Permissions/#more

**Comment by geekinglcq** [comment]
的确好像不会换行。但是这样直接把这么大一长串地址写在正文里也不好看嘛。  
可以这样写：  
```
（见 [这里](https://android.googlesource.com/platform/frameworks/base.git/+/3714141d287c965ea3451831dd5167f63f8db87b) ）。
```   

效果：  
（见 [这里](https://android.googlesource.com/platform/frameworks/base.git/+/3714141d287c965ea3451831dd5167f63f8db87b) ）。

**Comment by msdx** [comment]
@geekinglcq 这个我知道。有的博客我会发在其他地方，有的链接会被替换掉。

**Comment by viosay** [comment]
@msdx 在`article-inner.scss`中给`.article-entry`标签的子标签`p`加`word-break: break-word;`和`overflow-wrap: break-word;`样式就好了,然后重新打包下。

**Comment by msdx** [comment]
@viosay 
请问是这样子吗？

```
--- a/source-src/css/article-inner.scss
+++ b/source-src/css/article-inner.scss
@@ -79,6 +79,8 @@
   padding-left: 7.6923%;
   p{
     margin-top: 10px;
+    word-break: break-word;
+    overflow-wrap: break-word;
   }
   p code,li code{
     padding: 1px 3px;
```

**Comment by viosay** [comment]
@msdx 是的，还需要把主题再用npm 打包下

**Comment by msdx** [comment]
@viosay 请教一下如何打包，具体打包命令是？我是做android开发的，对这一块一窍不通

**Comment by viosay** [comment]
@msdx 看一下项目的wiki就知道了，很简单，不过litten的依赖都是陈旧的了，得折腾一下，我刚开始也对前端不太熟悉，摸索摸索就好了。实在不行的话就在项目里srouce里直接修改下打包好的main.css用是没问题的...
可以看下我的博客<https://inplus.top>

**Comment by msdx** [comment]
@viosay 谢谢
