### ISSUE TITLE
在主题中使用来必力，出现的bug

### ISSUE THREAD

**Issue by ivalue2333** [litten/hexo-theme-yilia#805]
我不是很确定这个bug是主题的bug还是来必力的bug，希望大家能给我参考，参考，本人前端较差...
问题是这样的。我的一些页面可以正常加载来必力，一些页面不能正常加载来必力，我测试了可能出现的原因，发现，如果在文章中使用一些markdown的语法，会导致来必力的加载失败。附上两张来必力加载后的网页代码截图
[未正常加载来必力](http://plgobp3oi.bkt.clouddn.com/laibili/_1.png)
[正常加载来必力](http://plgobp3oi.bkt.clouddn.com/laibili/_2.png)
可以看到两个的区别是正常加载的多了一个iframe。
但是不知道为什么会出现这个问题。是bug吗？还是什么问题?

未正常加载来必力的网页：https://ivalue2333.github.io/2019/01/27/github-blog/
正常加载来必力的网页：https://ivalue2333.github.io/2019/01/26/test-blog/

!!!Note，由于作者长期不维护，我已经换了主题，所以这个bug我决定关闭，但是这个问题并没有得到解决。

**Comment by reece15** [comment]
> 我不是很确定这个bug是主题的bug还是来必力的bug，希望大家能给我参考，参考，本人前端较差...
> 问题是这样的。我的一些页面可以正常加载来必力，一些页面不能正常加载来必力，我测试了可能出现的原因，发现，如果在文章中使用一些markdown的语法，会导致来必力的加载失败。附上两张来必力加载后的网页代码截图
> [未正常加载来必力](http://plgobp3oi.bkt.clouddn.com/laibili/_1.png)
> [正常加载来必力](http://plgobp3oi.bkt.clouddn.com/laibili/_2.png)
> 可以看到两个的区别是正常加载的多了一个iframe。
> 但是不知道为什么会出现这个问题。是bug吗？还是什么问题?
> 
> 未正常加载来必力的网页：https://ivalue2333.github.io/2019/01/27/github-blog/
> 正常加载来必力的网页：https://ivalue2333.github.io/2019/01/26/test-blog/
这个bug你解决了吗  我的情况是只有手机端可以加载（调试模式模拟手机缩放也可以），桌面浏览器就不行 非常奇怪

**Comment by godnesszsp** [comment]
me too
