### ISSUE TITLE
请问资源占用太大怎么解决

### ISSUE THREAD

**Issue by meerci** [litten/hexo-theme-yilia#816]

**Comment by iHTCboy** [comment]
你说什么占用资源？

**Comment by yiyingcanfeng** [comment]
> 你说什么占用资源？

![Snipaste_2019-07-04_15-15-07](https://user-images.githubusercontent.com/39869232/60646692-8e26a800-9e6e-11e9-9cdb-507e6416f290.png)

![Snipaste_2019-07-04_15-12-14](https://user-images.githubusercontent.com/39869232/60646523-23756c80-9e6e-11e9-8654-52f0ed10d0d0.png)

不知为何，CPU占用比较高，不管是在首页还是在某一篇文章的页面

**Comment by meerci** [comment]
应该是后台动画插件
