### ISSUE TITLE
发现有个请求失败

### ISSUE THREAD

**Issue by shanlanCoding** [litten/hexo-theme-yilia#820]
这个应该是你用来做统计的请求吧？请求结果是失败的。
![image](https://user-images.githubusercontent.com/44717382/59065487-64b24500-88df-11e9-9c02-ef42a9e77acd.png)

**Comment by Z1tao** [comment]
我也遇到了同样的问题，会导致页面加载转圈比较久。

**Comment by shanlanCoding** [comment]
> 我也遇到了同样的问题，会导致页面加载转圈比较久。

我直接换主题了。有next，pure，目前都试过，正在用pure。另外GitHub pages国内访问太慢，我已经使用netlify托管，只需要把hexo源码push到Git，netlify可以自动部署。

**Comment by moxia** [comment]
修改main.0cf68a.js里的if(n(197),window.BJ_REPORT)为if(n(197),false)
@shanlanCoding @Z1tao

**Comment by shanlanCoding** [comment]
> 修改main.0cf68a.js里的if(n(197),window.BJ_REPORT)为if(n(197),false)
> @shanlanCoding @Z1tao

谢谢，不过我已经改用pure主题了。 @moxia
