### ISSUE TITLE
请问有人知道怎么才能让sql代码行号贴边吗?

### ISSUE THREAD

**Issue by Cqh-i** [litten/hexo-theme-yilia#840]
如下图:
![image](https://user-images.githubusercontent.com/44899283/64070492-c3dfe580-cc93-11e9-9f1f-9c56c1bb8927.png)
链接: https://cqh-i.github.io/2019/08/31/转载-MySQL索引原理及慢查询优化/

**Comment by colorfulsweet** [comment]
你可以把table上面的width:100%去掉
然后调整父元素的背景色   来弥补效果上的差别即可

**Comment by colorfulsweet** [comment]
至于造成这个表现的原因, 说起来比较啰嗦, 正好今天有空   我也研究了一下
发个邮件给你吧

**Comment by Cqh-i** [comment]
> 你可以把table上面的width:100%去掉
> 然后调整父元素的背景色 来弥补效果上的差别即可

有效, 谢谢

**Comment by Cqh-i** [comment]
> 至于造成这个表现的原因, 说起来比较啰嗦, 正好今天有空 我也研究了一下
> 发个邮件给你吧

感谢指导
