### ISSUE TITLE
在yml文件里设置头像怎么没用啊

### ISSUE THREAD

**Issue by zhoushiwang99** [litten/hexo-theme-yilia#847]
![image](https://user-images.githubusercontent.com/43675156/66922845-727c9180-f05a-11e9-98b2-06563e6f091f.png)
![image](https://user-images.githubusercontent.com/43675156/66922870-79a39f80-f05a-11e9-9032-41fdacf9c156.png)
![image](https://user-images.githubusercontent.com/43675156/66922895-845e3480-f05a-11e9-9778-536a70f6da61.png)
![image](https://user-images.githubusercontent.com/43675156/66922917-8a541580-f05a-11e9-9317-e2ea11f06b2f.png)

**Comment by februarysea** [comment]
这个图片是要放在博客根目录下的`source`里面不是`theme`的`source`

**Comment by yansheng836** [comment]
@zhoushiwang99 突然发现，你这头像和我微信头像一模一样:laughing:
