### ISSUE TITLE
翻页按钮问题

### ISSUE THREAD

**Issue by LourisXu** [litten/hexo-theme-yilia#855]
![image](https://user-images.githubusercontent.com/25266205/71609310-5355c080-2bc2-11ea-9acd-dfba25ca11d9.png)
如图所示，最近忽然出现这个问题，之前都没有

**Comment by yansheng836** [comment]
HTML字符转义问题

```
转义字符，意义，字符
&nbsp; 空格 
&lt; 小于 <
&gt; 大于 >
&laquo; 双小于  <<
&raquo; 双大于 >>
```

**Comment by LourisXu** [comment]
> HTML字符转义问题
> 
> ```
> 转义字符，意义，字符
> &nbsp; 空格 
> &lt; 小于 <
> &gt; 大于 >
> &laquo; 双小于  <<
> &raquo; 双大于 >>
> ```

这不是主题弄好的嘛，感觉是识别的问题，不知道咋回事

**Comment by yaolang-hpc** [comment]
我得也出现了同样的问题，请问修复好了么
$ hexo -v
hexo-cli: 3.1.0
os: Windows_NT 10.0.17763 win32 x64
node: 12.14.0
v8: 7.7.299.13-node.16
uv: 1.33.1
zlib: 1.2.11
brotli: 1.0.7
ares: 1.15.0
modules: 72
nghttp2: 1.39.2
napi: 5
llhttp: 1.1.4
http_parser: 2.8.0
openssl: 1.1.1d
cldr: 35.1
icu: 64.2
tz: 2019c
unicode: 12.1

**Comment by yolia-ed** [comment]
降低hexo版本就行，但是降低版本会有其他一些小问题。。

**Comment by caoxingdong** [comment]
同问

**Comment by caoxingdong** [comment]
一个思路：
在\themes\yilia\layout\_partial 文件夹下面，把所有的 &laquo &raquo 改成 &lt &gt
![Snipaste_2020-02-21_19-21-56](https://user-images.githubusercontent.com/32877011/75084764-a7ed2c00-54df-11ea-893d-381003c03fba.png)
https://caoxingdong.github.io/

**Comment by b1gdea1** [comment]
有没有操作能把所有文章放在同一页

**Comment by shona3n** [comment]
我也出现了这个问题，请问有解么？

**Comment by carytseng** [comment]
求解，同问

**Comment by yangbh** [comment]
只把这个文件里的&laquo; &raquo;替换下就好了themes/yilia/layout/_partial/archive.ejs

```
    <nav id="page-nav">
      <%- paginator({
        prev_text: "« Prev",
        next_text: "Next »"
      }) %>
    </nav>
```

**Comment by moxia** [comment]
正确的解决办法：
```
<%- paginator({
  prev_text: '&laquo; Prev',
  next_text: 'Next &raquo;',
  escape: false
}) %>
```

**Comment by LourisXu** [comment]
> 正确的解决办法：
> 
> ```
> <%- paginator({
>   prev_text: '&laquo; Prev',
>   next_text: 'Next &raquo;',
>   escape: false
> }) %>
> ```

已解决
