### ISSUE TITLE
请教一下代码块行间距过大的问题

### ISSUE THREAD

**Issue by sunxingboo** [litten/hexo-theme-yilia#863]
<img width="532" alt="截屏2020-03-19下午10 11 05" src="https://user-images.githubusercontent.com/32425066/77077021-a0159e80-6a2f-11ea-8e64-84ffa8a01e6f.png">

如图，我克隆主题之后没有改动什么，但是代码块的行间隔很大，看着太难受了，有大佬知道怎么改吗？

**Comment by yansheng836** [comment]
印象中默认的好像不会很大啊？（才能和各种版本有关……）能给个地址吗？

**Comment by sunxingboo** [comment]
> 印象中默认的好像不会很大啊？（才能和各种版本有关……）能给个地址吗？

https://github.com/sunxingboo/BlogBackup 这是我的博客代码库

我看了一下代码块的html结构，我的和作者的有区别：

我的代码块：
<img width="392" alt="截屏2020-03-30下午8 28 53" src="https://user-images.githubusercontent.com/32425066/77912639-7b3de880-72c5-11ea-97bd-3c9e8a6b2e22.png">
`<table>`标签内没一行代码生成了一行`<tr>`

作者的代码块：
<img width="369" alt="截屏2020-03-30下午8 29 08" src="https://user-images.githubusercontent.com/32425066/77912627-75480780-72c5-11ea-97c5-1af2f4f14280.png">
这里所有代码行在一个`<tr>`内

请问问题在哪里呢？

**Comment by sunxingboo** [comment]
已解决
是因为 `hexo` 版本导致的，使用 `4.2.1` 版本就没问题了
