### ISSUE TITLE
希望能更新内置Valine

### ISSUE THREAD

**Issue by LnksW** [litten/hexo-theme-yilia#866]

**Comment by sujit-168** [comment]
兄弟，你完全可以自己搞定，可以看看[这篇文章](http://xiaqunfeng.cc/2019/11/06/hexo-valine/)，然后自己配置好，Fighting

**Comment by LnksW** [comment]
> 兄弟，你完全可以自己搞定，可以看看[这篇文章](http://xiaqunfeng.cc/2019/11/06/hexo-valine/)，然后自己配置好，Fighting

多谢，已经解决了
