### ISSUE TITLE
一个数据包问题

### ISSUE THREAD

**Issue by liuyunfz** [litten/hexo-theme-yilia#867]
你好，我在我的网站访问过程中，发现一个数据包极大的延长了我的网站加载时间，它的网址指向是litten.me:9005
以下是该包的数据：
```bash
Request URL: http://litten.me:9005/badjs/?id=1&uin=http://blog.6yfz.cn&msg=yilia-blog.6yfz.cn&ext=%7B%7D&from=http%3A%2F%2Fblog.6yfz.cn%2Ftutorial%2Fhexo-busuanzi.html&level=4&_t=1586918719969

Referrer Policy: no-referrer-when-downgrade
Provisional headers are shown
Referer: http://blog.6yfz.cn/tutorial/hexo-busuanzi.html
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.163 Safari/537.36

id: 1
uin: http://blog.6yfz.cn
msg: yilia-blog.6yfz.cn
ext: {}
from: http://blog.6yfz.cn/tutorial/hexo-busuanzi.html
level: 4
_t: 1586918719969
```
总共耗时2.46秒，请问这个包的作用是用来？是否必须要保留或者可以去除，否则我的网址速度访问则会很慢。希望能得到您的关注，谢谢

**Comment by deepred5** [comment]
[把这行上报数据js去掉](https://github.com/litten/hexo-theme-yilia/blob/master/source-src/js/main.js#L4)

然后重新打包即可:
```bash
cd  /themes/yilia/
npm i
npm run dist
```

**Comment by liuyunfz** [comment]
> [把这行上报数据js去掉](https://github.com/litten/hexo-theme-yilia/blob/master/source-src/js/main.js#L4)
> 
> 然后重新打包即可:
> ```bash
> cd  /themes/yilia/
> npm i
> npm run dist
> ```
> 

感谢您的回复，我已成功找到了这串数据包发送的代码文件位置，但因为我本人原因，我本地的npm无法重新进行编译，并且会报错，可能是曾经我修改过的代码遗留错误或是其他吧，他会提示让我修复，但是并不起效果。目前我已经改换了主题，所以也就对这个问题不再深入了。
