### ISSUE TITLE
在article.ejs中添加多说的代码之后出现多个输入框和评论列表

### ISSUE THREAD

**Issue by lynulzy** [litten/hexo-theme-yilia#99]
参照网上的多说教程添加多说组件之后在主页也会显示多个输入框以及输入列表，多说的js代码应该在article.ejs中添加吗

www.lynulzy.info

**Comment by tlongzou** [comment]
多说好像默认就是开启的, 
你可以在`hexodir/themes/yilia/_config.yml`中设置

**Comment by lynulzy** [comment]
@tlongzou  不太懂 能详细解释一下嘛

**Comment by lynulzy** [comment]
@litten   是不是因为每个article的多说组件都被重新加载了一遍

**Comment by korvin101** [comment]
多说已经集成在主题里了，你只要在主题的配置文件`_config.yml
`里设置下多说`duoshuo-key`就可以了

**Comment by lynulzy** [comment]
@korvin101  在_config.yml中设置之后，并把article.ejs中的多说通用代码移除后没有评论框了

**Comment by korvin101** [comment]
`article.ejs`文件里有这么段代码，这个主题自己的，你是不是删除掉了
```
<% if (!index && theme.duoshuo && post.comments){ %>
<%- partial('post/duoshuo', {
    key: post.slug,
    title: post.title,
    url: config.url+url_for(post.path)
  }) %>
<% } %>
```

**Comment by lynulzy** [comment]
@korvin101 这段代码没删除，目前是有分享按钮的，但是没有评论框  http://lynulzy.info

**Comment by korvin101** [comment]
![ashampoo_snap_2015 08 12_11h22m53s_001_](https://cloud.githubusercontent.com/assets/3283023/9215972/afee57ee-40e4-11e5-8536-2d04b98064a7.png)
控制台已经报错了，应该是你配置里的`duoshuo`填错了，你把密钥填进去了
`http://b216e5546f4497c0880*********.duoshuo.com/api/threads/listPosts.json?thread_key=%E5%BC%80%E5%8F%91%E7%AC%94%E8%AE%B0%E6%95%B4%E7%90%86&url=http%3A%2F%2Flynulzy.info%2F2015%2F08%2F11%2F%E5%BC%80%E5%8F%91%E7%AC%94%E8%AE%B0%E6%95%B4%E7%90%86%2F&title=%E5%BC%80%E5%8F%91%E7%AC%94%E8%AE%B0%E6%95%B4%E7%90%86&require=site%2Cvisitor%2Cnonce%2Clang%2Cunread%2Clog%2CextraCss&referer=http%3A%2F%2Flynulzy.info%2F&v=15.4.27`

**Comment by korvin101** [comment]
![qq 20150812113813](https://cloud.githubusercontent.com/assets/3283023/9216105/b6ec9c48-40e6-11e5-983e-ee3e1e38a0d4.png)
`/theme/yilia/_config.yml`的`duoshuo`填绿色的，而不是填红色的内容

**Comment by lynulzy** [comment]
@korvin101 非常感谢！在您的帮助下解决了！
